;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-sort Top_input_m 0)

;; "Top_input_m"
(declare-fun Top_input_m1 () ty)

(declare-sort M1 0)

;; "M1"
(declare-fun M11 () ty)

(declare-sort M2 0)

;; "M2"
(declare-fun M21 () ty)

(declare-sort A 0)

;; "A"
(declare-fun A1 () ty)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "pre"
(declare-fun pre (Top_input_m
  Top_input_m
  M1
  M2) Bool)

;; "x"
(declare-fun x () Bool)

;; "eA"
(assert x)

;; "x"
(declare-fun x1 () Bool)

;; "eNA"
(assert x1)

;; "x"
(declare-fun x2 () Bool)

;; "e1"
(assert x2)

;; "x"
(declare-fun x3 () Bool)

;; "e2"
(assert x3)

;; "x"
(declare-fun x4 () Bool)

;; "ll1"
(assert x4)

;; "x"
(declare-fun x5 () Bool)

;; "ll2"
(assert x5)

;; "&m1"
(declare-fun etm1 () memory)

;; "&m2"
(declare-fun etm2 () memory)

;; "vx1"
(declare-fun vx1 () Top_input_m)

;; "vx2"
(declare-fun vx2 () Top_input_m)

;; "M1"
(declare-fun M12 (memory) M1)

;; "M2"
(declare-fun M22 (memory) M2)

;; "Hpre"
(assert (pre vx1 vx2 (M12 etm1) (M22 etm2)))

;; "A"
(declare-fun A2 (memory) A)

;; "HglobA"
(assert (= (A2 etm1) (A2 etm2)))

;; "&m"
(declare-fun etm () memory)

;; "vx"
(declare-fun vx () Top_input_m)

;; Goal "goal"
(assert
  (not true))

(check-sat)

