;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "memory"
(declare-fun memory () ty)

;; "tuple4"
(declare-fun tuple4 (ty
  ty
  ty
  ty) ty)

;; "Tuple4"
(declare-fun Tuple4 (ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni) uni)

;; "Tuple4_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni))
      (sort (tuple4 a3 a2 a1 a) (Tuple4 a3 a2 a1 a x x1 x2 x3)))))

;; "proj4_0"
(declare-fun proj4_0 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_0_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a3 (proj4_0 a3 a2 a1 a x)))))

;; "proj4_0'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a3 u)
        (= (proj4_0 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u)))))

;; "proj4_1"
(declare-fun proj4_1 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_1_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a2 (proj4_1 a3 a2 a1 a x)))))

;; "proj4_1'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a2 u1)
        (= (proj4_1 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u1)))))

;; "proj4_2"
(declare-fun proj4_2 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_2_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a1 (proj4_2 a3 a2 a1 a x)))))

;; "proj4_2'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a1 u2)
        (= (proj4_2 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u2)))))

;; "proj4_3"
(declare-fun proj4_3 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_3_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a (proj4_3 a3 a2 a1 a x)))))

;; "proj4_3'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a u3)
        (= (proj4_3 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u3)))))

;; "tuple4_inversion"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple4 a3 a2 a1 a) u)
        (= u (Tuple4
               a3
               a2
               a1
               a
               (proj4_0 a3 a2 a1 a u)
               (proj4_1 a3 a2 a1 a u)
               (proj4_2 a3 a2 a1 a u)
               (proj4_3 a3 a2 a1 a u)))))))

;; "tuple2"
(declare-fun tuple2 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple2 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple2 a1 a) (Tuple2 a1 a x x1)))))

;; "proj2_0"
(declare-fun proj2_0 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a ty) (a1 ty)) (forall ((x uni)) (sort a1 (proj2_0 a1 a x)))))

;; "proj2_0'def"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a1 u) (= (proj2_0 a1 a (Tuple2 a1 a u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_1 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a ty) (a1 ty)) (forall ((x uni)) (sort a (proj2_1 a1 a x)))))

;; "proj2_1'def"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a u1) (= (proj2_1 a1 a (Tuple2 a1 a u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni))
      (=>
        (sort (tuple2 a1 a) u)
        (= u (Tuple2 a1 a (proj2_0 a1 a u) (proj2_1 a1 a u)))))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "&m"
(declare-fun etm () uni)

;; "&m_sort"
(assert (sort memory etm))

;; "Top_q"
(declare-fun Top_q () Int)

(declare-datatypes ((tuple0 0))
  (((Tuple0))))

;; "tuple0"
(declare-fun tuple01 () ty)

;; "&1"
(declare-fun et1 () uni)

;; "&1_sort"
(assert (sort (tuple2 (tuple4 tuple01 int tuple01 tuple01) memory) et1))

;; "&2"
(declare-fun et2 () uni)

;; "&2_sort"
(assert (sort (tuple2 (tuple4 tuple01 int tuple01 tuple01) memory) et2))

;; "bR"
(declare-fun bR () Bool)

;; "kR"
(declare-fun kR () Int)

;; "iL"
(declare-fun iL () Int)

;; "Top_gt0_q"
(assert (< 0 Top_q))

;; Goal "goal"
(assert
  (not (not (= Top_q 0))))

(check-sat)

