;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

;; "Top_COMPOSITION_Pi_REAL_ask_backdoor"
(declare-fun Top_COMPOSITION_Pi_REAL_ask_backdoor () ty)

(declare-sort Top_COMPOSITION_Pi_IDEAL_ask_backdoor 0)

;; "Top_COMPOSITION_Pi_IDEAL_ask_backdoor"
(declare-fun Top_COMPOSITION_Pi_IDEAL_ask_backdoor1 () ty)

(declare-datatypes ((Top_Logic_option 1))
  ((par (qta) ((Top_Logic_None) (Top_Logic_Some (Top_Logic_Some_proj qta))))))

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None1 (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta1 ty)) (sort (Top_Logic_option1 qta1) (Top_Logic_None1 qta1))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some1 (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni))
      (sort (Top_Logic_option1 qta1) (Top_Logic_Some1 qta1 x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta1 ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_Logic_option a qta1 x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_Logic_option a qta1 (Top_Logic_None1 qta1) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z1)
        (= (match_Top_Logic_option a qta1 (Top_Logic_Some1 qta1 u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty))
    (= (index_Top_Logic_option qta1 (Top_Logic_None1 qta1)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta1 (Top_Logic_Some1 qta1 u)) 1) :pattern (
      (Top_Logic_Some1
        qta1
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni)) (sort qta1 (Top_Logic_Some_proj_1 qta1 x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort qta1 u)
        (= (Top_Logic_Some_proj_1 qta1 (Top_Logic_Some1 qta1 u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta1) u)
        (or
          (= u (Top_Logic_None1 qta1))
          (= u (Top_Logic_Some1 qta1 (Top_Logic_Some_proj_1 qta1 u))))))))

(declare-sort Top_COMPOSITION_Pi_IDEAL_backdoor 0)

;; "Top_COMPOSITION_Pi_IDEAL_backdoor"
(declare-fun Top_COMPOSITION_Pi_IDEAL_backdoor1 () ty)

(declare-sort tuple2 2)

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple2 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a1 a) (Tuple2 a1 a x x1)))))

;; "proj2_0"
(declare-fun proj2_0 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a ty) (a1 ty)) (forall ((x uni)) (sort a1 (proj2_0 a1 a x)))))

;; "proj2_0'def"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a1 u) (= (proj2_0 a1 a (Tuple2 a1 a u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_1 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a ty) (a1 ty)) (forall ((x uni)) (sort a (proj2_1 a1 a x)))))

;; "proj2_1'def"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a u1) (= (proj2_1 a1 a (Tuple2 a1 a u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a1 a) u)
        (= u (Tuple2 a1 a (proj2_0 a1 a u) (proj2_1 a1 a u)))))))

(declare-sort Top_sum 2)

;; "Top_sum"
(declare-fun Top_sum1 (ty
  ty) ty)

;; "Top_Left"
(declare-fun Top_Left (ty
  ty
  uni) uni)

;; "Top_Left_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni)) (sort (Top_sum1 qta1 qtb) (Top_Left qtb qta1 x)))))

;; "Top_Right"
(declare-fun Top_Right (ty
  ty
  uni) uni)

;; "Top_Right_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni)) (sort (Top_sum1 qta1 qtb) (Top_Right qtb qta1 x)))))

;; "match_Top_sum"
(declare-fun match_Top_sum (ty
  ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_sum_sort"
(assert
  (forall ((qta1 ty) (qtb ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_sum a qtb qta1 x x1 x2)))))

;; "match_Top_sum_Top_Left"
(assert
  (forall ((qta1 ty) (qtb ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z)
        (= (match_Top_sum a qtb qta1 (Top_Left qtb qta1 u) z z1) z)))))

;; "match_Top_sum_Top_Right"
(assert
  (forall ((qta1 ty) (qtb ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z1)
        (= (match_Top_sum a qtb qta1 (Top_Right qtb qta1 u) z z1) z1)))))

;; "index_Top_sum"
(declare-fun index_Top_sum (ty
  ty
  uni) Int)

;; "index_Top_sum_Top_Left"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((u uni))
      (! (= (index_Top_sum qtb qta1 (Top_Left qtb qta1 u)) 0) :pattern (
      (Top_Left
        qtb
        qta1
        u)) ))))

;; "index_Top_sum_Top_Right"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((u uni))
      (! (= (index_Top_sum qtb qta1 (Top_Right qtb qta1 u)) 1) :pattern (
      (Top_Right
        qtb
        qta1
        u)) ))))

;; "Top_Left_proj_1"
(declare-fun Top_Left_proj_1 (ty
  ty
  uni) uni)

;; "Top_Left_proj_1_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni)) (sort qta1 (Top_Left_proj_1 qtb qta1 x)))))

;; "Top_Left_proj_1'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((u uni))
      (=>
        (sort qta1 u)
        (= (Top_Left_proj_1 qtb qta1 (Top_Left qtb qta1 u)) u)))))

;; "Top_Right_proj_1"
(declare-fun Top_Right_proj_1 (ty
  ty
  uni) uni)

;; "Top_Right_proj_1_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni)) (sort qtb (Top_Right_proj_1 qtb qta1 x)))))

;; "Top_Right_proj_1'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((u uni))
      (=>
        (sort qtb u)
        (= (Top_Right_proj_1 qtb qta1 (Top_Right qtb qta1 u)) u)))))

;; "Top_sum_inversion"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((u uni))
      (=>
        (sort (Top_sum1 qta1 qtb) u)
        (or
          (= u (Top_Left qtb qta1 (Top_Left_proj_1 qtb qta1 u)))
          (= u (Top_Right qtb qta1 (Top_Right_proj_1 qtb qta1 u))))))))

(declare-sort Top_COMPOSITION_R_ask_backdoor 0)

;; "Top_COMPOSITION_R_ask_backdoor"
(declare-fun Top_COMPOSITION_R_ask_backdoor1 () ty)

(declare-sort Top_COMPOSITION_R_backdoor 0)

;; "Top_COMPOSITION_R_backdoor"
(declare-fun Top_COMPOSITION_R_backdoor1 () ty)

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a x x1)))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "&m"
(declare-fun etm () uni)

;; "&m_sort"
(assert (sort memory1 etm))

;; "m1"
(declare-fun m1 () uni)

;; "m1_sort"
(assert (sort Top_COMPOSITION_Pi_REAL_ask_backdoor m1))

;; "m2"
(declare-fun m2 () uni)

;; "m2_sort"
(assert (sort Top_COMPOSITION_Pi_REAL_ask_backdoor m2))

;; "`&2"
(declare-fun bqet2 () (tuple2 (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor
  (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))
  memory))

;; "Top_get_as_Right"
(declare-fun Top_get_as_Right (ty
  ty
  uni) uni)

;; "Top_get_as_Right_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni))
      (sort (Top_Logic_option1 qtb) (Top_get_as_Right qtb qta1 x)))))

;; "t2tb"
(declare-fun t2tb ((Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (sort (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1) j)
         (= (t2tb (tb2t j)) j)) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_COMPOSITION_Pi_IDEAL_backdoor) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_COMPOSITION_Pi_IDEAL_backdoor))
    (sort Top_COMPOSITION_Pi_IDEAL_backdoor1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_COMPOSITION_Pi_IDEAL_backdoor)

;; "BridgeL"
(assert
  (forall ((i Top_COMPOSITION_Pi_IDEAL_backdoor))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort Top_COMPOSITION_Pi_IDEAL_backdoor1 j)
         (= (t2tb1 (tb2t1 j)) j)) :pattern ((t2tb1 (tb2t1 j))) )))

;; "Top_get_as_Right'def"
(assert
  (forall ((qta1 ty))
    (and
      (forall ((x uni))
        (= (tb2t
             (Top_get_as_Right
               Top_COMPOSITION_Pi_IDEAL_backdoor1
               qta1
               (Top_Left Top_COMPOSITION_Pi_IDEAL_backdoor1 qta1 x))) 
        (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
      (forall ((x Top_COMPOSITION_Pi_IDEAL_backdoor))
        (= (tb2t
             (Top_get_as_Right
               Top_COMPOSITION_Pi_IDEAL_backdoor1
               qta1
               (Top_Right Top_COMPOSITION_Pi_IDEAL_backdoor1 qta1 (t2tb1 x)))) 
        (Top_Logic_Some
          x))))))

;; "Top_get_as_Right'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (and
      (forall ((x uni))
        (= (Top_get_as_Right qtb qta1 (Top_Left qtb qta1 x)) (Top_Logic_None1
                                                               qtb)))
      (forall ((x uni))
        (= (Top_get_as_Right qtb qta1 (Top_Right qtb qta1 x)) (Top_Logic_Some1
                                                                qtb
                                                                x))))))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt (ty
  uni
  uni) uni)

;; "Top_Logic_odflt_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni) (x1 uni)) (sort qta1 (Top_Logic_odflt qta1 x x1)))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((d Top_COMPOSITION_Pi_IDEAL_backdoor) (ox (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (match ox ((Top_Logic_None (= (tb2t1
                                    (Top_Logic_odflt
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      (t2tb1 d)
                                      (t2tb ox))) d))
               ((Top_Logic_Some x) (= (tb2t1
                                        (Top_Logic_odflt
                                          Top_COMPOSITION_Pi_IDEAL_backdoor1
                                          (t2tb1 d)
                                          (t2tb ox))) x))))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((qta1 ty))
    (forall ((d uni))
      (=>
        (sort qta1 d)
        (and
          (= (Top_Logic_odflt qta1 d (Top_Logic_None1 qta1)) d)
          (forall ((x1 uni))
            (=>
              (sort qta1 x1)
              (= (Top_Logic_odflt qta1 d (Top_Logic_Some1 qta1 x1)) x1))))))))

;; "t2tb"
(declare-fun t2tb2 ((Top_Logic_option Top_COMPOSITION_Pi_IDEAL_ask_backdoor)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_ask_backdoor)))
    (sort
      (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_ask_backdoor1)
      (t2tb2 x1))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_ask_backdoor))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_ask_backdoor)))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_ask_backdoor1) j)
         (= (t2tb2 (tb2t2 j)) j)) :pattern ((t2tb2 (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 ((Top_sum Top_COMPOSITION_R_ask_backdoor
  Top_COMPOSITION_Pi_IDEAL_ask_backdoor)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_sum Top_COMPOSITION_R_ask_backdoor Top_COMPOSITION_Pi_IDEAL_ask_backdoor)))
    (sort
      (Top_sum1
        Top_COMPOSITION_R_ask_backdoor1
        Top_COMPOSITION_Pi_IDEAL_ask_backdoor1)
      (t2tb3 x1))))

;; "tb2t"
(declare-fun tb2t3 (uni) (Top_sum Top_COMPOSITION_R_ask_backdoor
  Top_COMPOSITION_Pi_IDEAL_ask_backdoor))

;; "BridgeL"
(assert
  (forall ((i (Top_sum Top_COMPOSITION_R_ask_backdoor Top_COMPOSITION_Pi_IDEAL_ask_backdoor)))
    (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (Top_sum1
             Top_COMPOSITION_R_ask_backdoor1
             Top_COMPOSITION_Pi_IDEAL_ask_backdoor1)
           j)
         (= (t2tb3 (tb2t3 j)) j)) :pattern ((t2tb3 (tb2t3 j))) )))

;; "t2tb"
(declare-fun t2tb4 ((tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor
  (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (sort
      (tuple21
        Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
        (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
      (t2tb4 x1))))

;; "tb2t"
(declare-fun tb2t4 (uni) (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor
  (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "BridgeL"
(assert
  (forall ((i (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (! (= (tb2t4 (t2tb4 i)) i) :pattern ((t2tb4 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (tuple21
             Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
             (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
           j)
         (= (t2tb4 (tb2t4 j)) j)) :pattern ((t2tb4 (tb2t4 j))) )))

;; "t2tb"
(declare-fun t2tb5 ((tuple2 (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor
  (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))
  memory)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (tuple2 (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)) memory)))
    (sort
      (tuple21
        (tuple21
          Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
          (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
        memory1)
      (t2tb5 x1))))

;; "tb2t"
(declare-fun tb2t5 (uni) (tuple2 (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor
  (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))
  memory))

;; "BridgeL"
(assert
  (forall ((i (tuple2 (tuple2 Top_COMPOSITION_Pi_IDEAL_ask_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)) memory)))
    (! (= (tb2t5 (t2tb5 i)) i) :pattern ((t2tb5 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (tuple21
             (tuple21
               Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
               (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
             memory1)
           j)
         (= (t2tb5 (tb2t5 j)) j)) :pattern ((t2tb5 (tb2t5 j))) )))

;; "t2tb"
(declare-fun t2tb6 (Top_COMPOSITION_Pi_IDEAL_ask_backdoor) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 Top_COMPOSITION_Pi_IDEAL_ask_backdoor))
    (sort Top_COMPOSITION_Pi_IDEAL_ask_backdoor1 (t2tb6 x1))))

;; "tb2t"
(declare-fun tb2t6 (uni) Top_COMPOSITION_Pi_IDEAL_ask_backdoor)

;; "BridgeL"
(assert
  (forall ((i Top_COMPOSITION_Pi_IDEAL_ask_backdoor))
    (! (= (tb2t6 (t2tb6 i)) i) :pattern ((t2tb6 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort Top_COMPOSITION_Pi_IDEAL_ask_backdoor1 j)
         (= (t2tb6 (tb2t6 j)) j)) :pattern ((t2tb6 (tb2t6 j))) )))

;; "_"
(assert
  (= (tb2t6
       (Top_Logic_odflt
         Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
         (witness1 Top_COMPOSITION_Pi_IDEAL_ask_backdoor1)
         (Top_get_as_Right
           Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
           Top_COMPOSITION_R_ask_backdoor1
           (Top_Right
             Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
             Top_COMPOSITION_R_ask_backdoor1
             (proj2_0
               Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
               (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1)
               (proj2_0
                 (tuple21
                   Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
                   (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
                 memory1
                 (t2tb5 bqet2))))))) (tb2t6
                                       (proj2_0
                                         Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
                                         (Top_Logic_option1
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1)
                                         (proj2_0
                                           (tuple21
                                             Top_COMPOSITION_Pi_IDEAL_ask_backdoor1
                                             (Top_Logic_option1
                                               Top_COMPOSITION_Pi_IDEAL_backdoor1))
                                           memory1
                                           (t2tb5 bqet2))))))

;; "rr"
(declare-fun rr () (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))

;; "Top_getr"
(declare-fun Top_getr (ty
  ty
  uni) uni)

;; "Top_getr_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x1 uni)) (sort (Top_Logic_option1 qtb) (Top_getr qtb qta1 x1)))))

;; "Top_getr'def"
(assert
  (forall ((qta1 ty))
    (and
      (forall ((a uni))
        (= (tb2t
             (Top_getr
               Top_COMPOSITION_Pi_IDEAL_backdoor1
               qta1
               (Top_Left Top_COMPOSITION_Pi_IDEAL_backdoor1 qta1 a))) 
        (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
      (forall ((b Top_COMPOSITION_Pi_IDEAL_backdoor))
        (= (tb2t
             (Top_getr
               Top_COMPOSITION_Pi_IDEAL_backdoor1
               qta1
               (Top_Right Top_COMPOSITION_Pi_IDEAL_backdoor1 qta1 (t2tb1 b)))) 
        (Top_Logic_Some
          b))))))

;; "Top_getr'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (and
      (forall ((a uni))
        (= (Top_getr qtb qta1 (Top_Left qtb qta1 a)) (Top_Logic_None1 qtb)))
      (forall ((b uni))
        (= (Top_getr qtb qta1 (Top_Right qtb qta1 b)) (Top_Logic_Some1 qtb b))))))

;; "Top_getr_ho_ho"
(declare-fun Top_getr_ho_ho (ty
  ty) uni)

;; "Top_getr_ho_ho_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (sort
      (infix_mngt (Top_sum1 qta1 qtb) (Top_Logic_option1 qtb))
      (Top_getr_ho_ho qtb qta1))))

;; "Top_getr_ho_ho"
(declare-fun Top_getr_ho_ho1 () (Array (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "t2tb"
(declare-fun t2tb7 ((Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (sort
      (Top_sum1
        Top_COMPOSITION_R_backdoor1
        Top_COMPOSITION_Pi_IDEAL_backdoor1)
      (t2tb7 x1))))

;; "tb2t"
(declare-fun tb2t7 (uni) (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor))

;; "BridgeL"
(assert
  (forall ((i (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (! (= (tb2t7 (t2tb7 i)) i) :pattern ((t2tb7 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (Top_sum1
             Top_COMPOSITION_R_backdoor1
             Top_COMPOSITION_Pi_IDEAL_backdoor1)
           j)
         (= (t2tb7 (tb2t7 j)) j)) :pattern ((t2tb7 (tb2t7 j))) )))

;; "Top_getr_ho_ho_spec"
(assert
  (forall ((x1 (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (= (select Top_getr_ho_ho1 x1) (tb2t
                                     (Top_getr
                                       Top_COMPOSITION_Pi_IDEAL_backdoor1
                                       Top_COMPOSITION_R_backdoor1
                                       (t2tb7 x1))))))

;; "Top_getr_ho_ho_spec"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x1 uni))
      (= (infix_at
           (Top_Logic_option1 qtb)
           (Top_sum1 qta1 qtb)
           (Top_getr_ho_ho qtb qta1)
           x1) (Top_getr qtb qta1 x1)))))

;; "Right_ho"
(declare-fun Right_ho (ty
  ty) uni)

;; "Right_ho_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (sort (infix_mngt qtb (Top_sum1 qta1 qtb)) (Right_ho qtb qta1))))

;; "Right_ho"
(declare-fun Right_ho1 () (Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "Right_ho_spec"
(assert
  (forall ((x1 Top_COMPOSITION_Pi_IDEAL_backdoor))
    (= (select Right_ho1 x1) (tb2t7
                               (Top_Right
                                 Top_COMPOSITION_Pi_IDEAL_backdoor1
                                 Top_COMPOSITION_R_backdoor1
                                 (t2tb1 x1))))))

;; "Right_ho_spec"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x1 uni))
      (= (infix_at (Top_sum1 qta1 qtb) qtb (Right_ho qtb qta1) x1) (Top_Right
                                                                    qtb
                                                                    qta1
                                                                    x1)))))

;; "Top_Logic_omap"
(declare-fun Top_Logic_omap (ty
  ty
  uni
  uni) uni)

;; "Top_Logic_omap_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x1 uni) (x2 uni))
      (sort (Top_Logic_option1 qtb) (Top_Logic_omap qtb qta1 x1 x2)))))

;; "Top_Logic_omap"
(declare-fun Top_Logic_omap1 ((Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor))
  (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)) (Top_Logic_option (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "Top_Logic_omap'def"
(assert
  (forall ((qta1 ty))
    (forall ((f uni))
      (and
        (= (tb2t
             (Top_Logic_omap
               Top_COMPOSITION_Pi_IDEAL_backdoor1
               qta1
               f
               (Top_Logic_None1 qta1))) (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
        (forall ((x1 uni))
          (= (tb2t
               (Top_Logic_omap
                 Top_COMPOSITION_Pi_IDEAL_backdoor1
                 qta1
                 f
                 (Top_Logic_Some1 qta1 x1))) (Top_Logic_Some
                                               (tb2t1
                                                 (infix_at
                                                   Top_COMPOSITION_Pi_IDEAL_backdoor1
                                                   qta1
                                                   f
                                                   x1)))))))))

;; "t2tb"
(declare-fun t2tb8 ((Top_Logic_option (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_Logic_option (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (sort
      (Top_Logic_option1
        (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
      (t2tb8 x1))))

;; "tb2t"
(declare-fun tb2t8 (uni) (Top_Logic_option (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (! (= (tb2t8 (t2tb8 i)) i) :pattern ((t2tb8 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (Top_Logic_option1
             (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
           j)
         (= (t2tb8 (tb2t8 j)) j)) :pattern ((t2tb8 (tb2t8 j))) )))

;; "t2tb"
(declare-fun t2tb9 ((Array (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Array (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (sort
      (infix_mngt
        (Top_sum1
          Top_COMPOSITION_R_backdoor1
          Top_COMPOSITION_Pi_IDEAL_backdoor1)
        (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
      (t2tb9 x1))))

;; "tb2t"
(declare-fun tb2t9 (uni) (Array (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "BridgeL"
(assert
  (forall ((i (Array (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (! (= (tb2t9 (t2tb9 i)) i) :pattern ((t2tb9 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             (Top_sum1
               Top_COMPOSITION_R_backdoor1
               Top_COMPOSITION_Pi_IDEAL_backdoor1)
             (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
           j)
         (= (t2tb9 (tb2t9 j)) j)) :pattern ((t2tb9 (tb2t9 j))) )))

;; "t2tb"
(declare-fun t2tb10 ((Top_Logic_option (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor))) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_Logic_option (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (sort
      (Top_Logic_option1
        (Top_sum1
          Top_COMPOSITION_R_backdoor1
          Top_COMPOSITION_Pi_IDEAL_backdoor1))
      (t2tb10 x1))))

;; "tb2t"
(declare-fun tb2t10 (uni) (Top_Logic_option (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (! (= (tb2t10 (t2tb10 i)) i) :pattern ((t2tb10 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (Top_Logic_option1
             (Top_sum1
               Top_COMPOSITION_R_backdoor1
               Top_COMPOSITION_Pi_IDEAL_backdoor1))
           j)
         (= (t2tb10 (tb2t10 j)) j)) :pattern ((t2tb10 (tb2t10 j))) )))

;; "Top_Logic_omap'def"
(assert
  (forall ((f (Array (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (and
      (= (tb2t8
           (Top_Logic_omap
             (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1)
             (Top_sum1
               Top_COMPOSITION_R_backdoor1
               Top_COMPOSITION_Pi_IDEAL_backdoor1)
             (t2tb9 f)
             (Top_Logic_None1
               (Top_sum1
                 Top_COMPOSITION_R_backdoor1
                 Top_COMPOSITION_Pi_IDEAL_backdoor1)))) (tb2t8
                                                          (Top_Logic_None1
                                                            (Top_Logic_option1
                                                              Top_COMPOSITION_Pi_IDEAL_backdoor1))))
      (forall ((x1 (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
        (= (tb2t8
             (Top_Logic_omap
               (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1)
               (Top_sum1
                 Top_COMPOSITION_R_backdoor1
                 Top_COMPOSITION_Pi_IDEAL_backdoor1)
               (t2tb9 f)
               (Top_Logic_Some1
                 (Top_sum1
                   Top_COMPOSITION_R_backdoor1
                   Top_COMPOSITION_Pi_IDEAL_backdoor1)
                 (t2tb7 x1)))) (tb2t8
                                 (Top_Logic_Some1
                                   (Top_Logic_option1
                                     Top_COMPOSITION_Pi_IDEAL_backdoor1)
                                   (t2tb (select f x1)))))))))

;; "Top_Logic_omap'def"
(assert
  (forall ((f (Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor))) (ox (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (match ox ((Top_Logic_None (= (Top_Logic_omap1 f ox) (tb2t10
                                                           (Top_Logic_None1
                                                             (Top_sum1
                                                               Top_COMPOSITION_R_backdoor1
                                                               Top_COMPOSITION_Pi_IDEAL_backdoor1)))))
               ((Top_Logic_Some x1) (= (Top_Logic_omap1 f ox) (tb2t10
                                                                (Top_Logic_Some1
                                                                  (Top_sum1
                                                                    Top_COMPOSITION_R_backdoor1
                                                                    Top_COMPOSITION_Pi_IDEAL_backdoor1)
                                                                  (t2tb7
                                                                    (select f x1))))))))))

;; "t2tb"
(declare-fun t2tb11 ((Array Top_COMPOSITION_Pi_IDEAL_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)) uni)

;; "t2tb_sort"
(assert
  (forall ((x2 (Array Top_COMPOSITION_Pi_IDEAL_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (sort
      (infix_mngt
        Top_COMPOSITION_Pi_IDEAL_backdoor1
        Top_COMPOSITION_Pi_IDEAL_backdoor1)
      (t2tb11 x2))))

;; "tb2t"
(declare-fun tb2t11 (uni) (Array Top_COMPOSITION_Pi_IDEAL_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor))

;; "BridgeL"
(assert
  (forall ((i (Array Top_COMPOSITION_Pi_IDEAL_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (! (= (tb2t11 (t2tb11 i)) i) :pattern ((t2tb11 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_COMPOSITION_Pi_IDEAL_backdoor1
             Top_COMPOSITION_Pi_IDEAL_backdoor1)
           j)
         (= (t2tb11 (tb2t11 j)) j)) :pattern ((t2tb11 (tb2t11 j))) )))

;; "Top_Logic_omap'def"
(assert
  (forall ((f (Array Top_COMPOSITION_Pi_IDEAL_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)) (ox (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (match ox ((Top_Logic_None (= (tb2t
                                    (Top_Logic_omap
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      (t2tb11 f)
                                      (t2tb ox))) (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
               ((Top_Logic_Some x2) (= (tb2t
                                         (Top_Logic_omap
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                           (t2tb11 f)
                                           (t2tb ox))) (Top_Logic_Some
                                                         (tb2t1
                                                           (infix_at
                                                             Top_COMPOSITION_Pi_IDEAL_backdoor1
                                                             Top_COMPOSITION_Pi_IDEAL_backdoor1
                                                             (t2tb11 f)
                                                             (t2tb1 x2))))))))))

;; "Top_Logic_omap'def"
(assert
  (forall ((qtb ty))
    (forall ((f uni) (ox (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
      (match ox ((Top_Logic_None (= (Top_Logic_omap
                                      qtb
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      f
                                      (t2tb ox)) (Top_Logic_None1 qtb)))
                 ((Top_Logic_Some x3) (= (Top_Logic_omap
                                           qtb
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                           f
                                           (t2tb ox)) (Top_Logic_Some1
                                                        qtb
                                                        (infix_at
                                                          qtb
                                                          Top_COMPOSITION_Pi_IDEAL_backdoor1
                                                          f
                                                          (t2tb1 x3))))))))))

;; "Top_Logic_omap'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((f uni))
      (and
        (= (Top_Logic_omap qtb qta1 f (Top_Logic_None1 qta1)) (Top_Logic_None1
                                                                qtb))
        (forall ((x4 uni))
          (= (Top_Logic_omap qtb qta1 f (Top_Logic_Some1 qta1 x4)) (Top_Logic_Some1
                                                                    qtb
                                                                    (infix_at
                                                                    qtb
                                                                    qta1
                                                                    f
                                                                    x4))))))))

;; "Top_Logic_obind"
(declare-fun Top_Logic_obind (ty
  ty
  uni
  uni) uni)

;; "Top_Logic_obind_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x4 uni) (x5 uni))
      (sort (Top_Logic_option1 qtb) (Top_Logic_obind qtb qta1 x4 x5)))))

;; "Top_Logic_obind"
(declare-fun Top_Logic_obind1 ((Array (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))
  (Top_Logic_option (Top_sum Top_COMPOSITION_R_backdoor
  Top_COMPOSITION_Pi_IDEAL_backdoor))) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))

;; "Top_Logic_obind'def"
(assert
  (forall ((qta1 ty))
    (forall ((f uni))
      (and
        (= (tb2t
             (Top_Logic_obind
               Top_COMPOSITION_Pi_IDEAL_backdoor1
               qta1
               f
               (Top_Logic_None1 qta1))) (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
        (forall ((x4 uni))
          (= (tb2t
               (Top_Logic_obind
                 Top_COMPOSITION_Pi_IDEAL_backdoor1
                 qta1
                 f
                 (Top_Logic_Some1 qta1 x4))) (tb2t
                                               (infix_at
                                                 (Top_Logic_option1
                                                   Top_COMPOSITION_Pi_IDEAL_backdoor1)
                                                 qta1
                                                 f
                                                 x4))))))))

;; "Top_Logic_obind'def"
(assert
  (forall ((f (Array (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor) (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (and
      (= (Top_Logic_obind1
           f
           (tb2t10
             (Top_Logic_None1
               (Top_sum1
                 Top_COMPOSITION_R_backdoor1
                 Top_COMPOSITION_Pi_IDEAL_backdoor1)))) (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
      (forall ((x4 (Top_sum Top_COMPOSITION_R_backdoor Top_COMPOSITION_Pi_IDEAL_backdoor)))
        (= (Top_Logic_obind1
             f
             (tb2t10
               (Top_Logic_Some1
                 (Top_sum1
                   Top_COMPOSITION_R_backdoor1
                   Top_COMPOSITION_Pi_IDEAL_backdoor1)
                 (t2tb7 x4)))) (select f x4))))))

;; "t2tb"
(declare-fun t2tb12 ((Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))) uni)

;; "t2tb_sort"
(assert
  (forall ((x4 (Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (sort
      (infix_mngt
        Top_COMPOSITION_Pi_IDEAL_backdoor1
        (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
      (t2tb12 x4))))

;; "tb2t"
(declare-fun tb2t12 (uni) (Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (! (= (tb2t12 (t2tb12 i)) i) :pattern ((t2tb12 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_COMPOSITION_Pi_IDEAL_backdoor1
             (Top_Logic_option1 Top_COMPOSITION_Pi_IDEAL_backdoor1))
           j)
         (= (t2tb12 (tb2t12 j)) j)) :pattern ((t2tb12 (tb2t12 j))) )))

;; "Top_Logic_obind'def"
(assert
  (forall ((f (Array Top_COMPOSITION_Pi_IDEAL_backdoor (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))) (ox (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
    (match ox ((Top_Logic_None (= (tb2t
                                    (Top_Logic_obind
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      (t2tb12 f)
                                      (t2tb ox))) (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
               ((Top_Logic_Some x4) (= (tb2t
                                         (Top_Logic_obind
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                           (t2tb12 f)
                                           (t2tb ox))) (tb2t
                                                         (infix_at
                                                           (Top_Logic_option1
                                                             Top_COMPOSITION_Pi_IDEAL_backdoor1)
                                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                                           (t2tb12 f)
                                                           (t2tb1 x4)))))))))

;; "Top_Logic_obind'def"
(assert
  (forall ((qtb ty))
    (forall ((f uni) (ox (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor)))
      (match ox ((Top_Logic_None (= (Top_Logic_obind
                                      qtb
                                      Top_COMPOSITION_Pi_IDEAL_backdoor1
                                      f
                                      (t2tb ox)) (Top_Logic_None1 qtb)))
                 ((Top_Logic_Some x5) (= (Top_Logic_obind
                                           qtb
                                           Top_COMPOSITION_Pi_IDEAL_backdoor1
                                           f
                                           (t2tb ox)) (infix_at
                                                        (Top_Logic_option1
                                                          qtb)
                                                        Top_COMPOSITION_Pi_IDEAL_backdoor1
                                                        f
                                                        (t2tb1 x5)))))))))

;; "Top_Logic_obind'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((f uni))
      (and
        (= (Top_Logic_obind qtb qta1 f (Top_Logic_None1 qta1)) (Top_Logic_None1
                                                                 qtb))
        (forall ((x6 uni))
          (= (Top_Logic_obind qtb qta1 f (Top_Logic_Some1 qta1 x6)) (infix_at
                                                                    (Top_Logic_option1
                                                                    qtb)
                                                                    qta1
                                                                    f
                                                                    x6)))))))

;; Goal "goal"
(assert
  (not
  (=>
    (not
      (= rr (as Top_Logic_None (Top_Logic_option Top_COMPOSITION_Pi_IDEAL_backdoor))))
    (= (Top_Logic_obind1 Top_getr_ho_ho1 (Top_Logic_omap1 Right_ho1 rr)) 
    rr))))

(check-sat)
(get-info :reason-unknown)

