;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-datatypes ((tuple2 2))
  ((par (a a1) ((Tuple2 (proj2_0 a)(proj2_1 a1))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a3 a2) (Tuple21 a3 a2 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a3 (proj2_01 a3 a2 x)))))

;; "proj2_0'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a3 u) (= (proj2_01 a3 a2 (Tuple21 a3 a2 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a2 (proj2_11 a3 a2 x)))))

;; "proj2_1'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a2 u1) (= (proj2_11 a3 a2 (Tuple21 a3 a2 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a3 a2) u)
        (= u (Tuple21 a3 a2 (proj2_01 a3 a2 u) (proj2_11 a3 a2 u)))))))

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_List_list a2 qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_List_list a2 qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a2 z1)
        (= (match_Top_List_list a2 qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-sort Top_Nonce_nonce 0)

;; "Top_Nonce_nonce"
(declare-fun Top_Nonce_nonce1 () ty)

(declare-sort Top_Block_block 0)

;; "Top_Block_block"
(declare-fun Top_Block_block1 () ty)

(declare-sort Top_Poly_in_poly_in 0)

;; "Top_Poly_in_poly_in"
(declare-fun Top_Poly_in_poly_in1 () ty)

(declare-sort Top_Poly_out_poly_out 0)

;; "Top_Poly_out_poly_out"
(declare-fun Top_Poly_out_poly_out1 () ty)

(declare-sort tuple8 8)

;; "tuple8"
(declare-fun tuple81 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty) ty)

;; "Tuple8"
(declare-fun Tuple8 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni) uni)

;; "Tuple8_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni) (x4 uni) (x5 uni) (x6 uni) (x7 uni))
      (sort
        (tuple81 a9 a8 a7 a6 a5 a4 a3 a2)
        (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 x x1 x2 x3 x4 x5 x6 x7)))))

;; "proj8_0"
(declare-fun proj8_0 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_0_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a9 (proj8_0 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_0'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a9 u)
        (= (proj8_0
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u)))))

;; "proj8_1"
(declare-fun proj8_1 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_1_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a8 (proj8_1 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_1'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a8 u1)
        (= (proj8_1
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u1)))))

;; "proj8_2"
(declare-fun proj8_2 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_2_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a7 (proj8_2 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_2'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a7 u2)
        (= (proj8_2
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u2)))))

;; "proj8_3"
(declare-fun proj8_3 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_3_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a6 (proj8_3 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_3'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a6 u3)
        (= (proj8_3
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u3)))))

;; "proj8_4"
(declare-fun proj8_4 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_4_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a5 (proj8_4 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_4'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a5 u4)
        (= (proj8_4
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u4)))))

;; "proj8_5"
(declare-fun proj8_5 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_5_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a4 (proj8_5 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_5'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a4 u5)
        (= (proj8_5
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u5)))))

;; "proj8_6"
(declare-fun proj8_6 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_6_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a3 (proj8_6 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_6'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a3 u6)
        (= (proj8_6
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u6)))))

;; "proj8_7"
(declare-fun proj8_7 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj8_7_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((x uni)) (sort a2 (proj8_7 a9 a8 a7 a6 a5 a4 a3 a2 x)))))

;; "proj8_7'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni))
      (=>
        (sort a2 u7)
        (= (proj8_7
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             (Tuple8 a9 a8 a7 a6 a5 a4 a3 a2 u u1 u2 u3 u4 u5 u6 u7)) u7)))))

;; "tuple8_inversion"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty))
    (forall ((u uni))
      (=>
        (sort (tuple81 a9 a8 a7 a6 a5 a4 a3 a2) u)
        (= u (Tuple8
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               (proj8_0 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_1 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_2 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_3 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_4 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_5 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_6 a9 a8 a7 a6 a5 a4 a3 a2 u)
               (proj8_7 a9 a8 a7 a6 a5 a4 a3 a2 u)))))))

(declare-sort Top_FMap_fmap 2)

;; "Top_FMap_fmap"
(declare-fun Top_FMap_fmap1 (ty
  ty) ty)

(declare-sort Top_C_counter 0)

;; "Top_C_counter"
(declare-fun Top_C_counter1 () ty)

(declare-sort Top_Byte_byte 0)

;; "Top_Byte_byte"
(declare-fun Top_Byte_byte1 () ty)

(declare-sort tuple4 4)

;; "tuple4"
(declare-fun tuple41 (ty
  ty
  ty
  ty) ty)

;; "Tuple4"
(declare-fun Tuple4 (ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni) uni)

;; "Tuple4_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni))
      (sort (tuple41 a5 a4 a3 a2) (Tuple4 a5 a4 a3 a2 x x1 x2 x3)))))

;; "proj4_0"
(declare-fun proj4_0 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_0_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a5 (proj4_0 a5 a4 a3 a2 x)))))

;; "proj4_0'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a5 u)
        (= (proj4_0 a5 a4 a3 a2 (Tuple4 a5 a4 a3 a2 u u1 u2 u3)) u)))))

;; "proj4_1"
(declare-fun proj4_1 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_1_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a4 (proj4_1 a5 a4 a3 a2 x)))))

;; "proj4_1'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a4 u1)
        (= (proj4_1 a5 a4 a3 a2 (Tuple4 a5 a4 a3 a2 u u1 u2 u3)) u1)))))

;; "proj4_2"
(declare-fun proj4_2 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_2_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a3 (proj4_2 a5 a4 a3 a2 x)))))

;; "proj4_2'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a3 u2)
        (= (proj4_2 a5 a4 a3 a2 (Tuple4 a5 a4 a3 a2 u u1 u2 u3)) u2)))))

;; "proj4_3"
(declare-fun proj4_3 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_3_sort"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a2 (proj4_3 a5 a4 a3 a2 x)))))

;; "proj4_3'def"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a2 u3)
        (= (proj4_3 a5 a4 a3 a2 (Tuple4 a5 a4 a3 a2 u u1 u2 u3)) u3)))))

;; "tuple4_inversion"
(assert
  (forall ((a2 ty) (a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni))
      (=>
        (sort (tuple41 a5 a4 a3 a2) u)
        (= u (Tuple4
               a5
               a4
               a3
               a2
               (proj4_0 a5 a4 a3 a2 u)
               (proj4_1 a5 a4 a3 a2 u)
               (proj4_2 a5 a4 a3 a2 u)
               (proj4_3 a5 a4 a3 a2 u)))))))

(declare-sort Top_Logic_option 1)

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta ty)) (sort (Top_Logic_option1 qta) (Top_Logic_None qta))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_Logic_option1 qta) (Top_Logic_Some qta x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_Logic_option a2 qta x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_Logic_option a2 qta (Top_Logic_None qta) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a2 z1)
        (= (match_Top_Logic_option a2 qta (Top_Logic_Some qta u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty)) (= (index_Top_Logic_option qta (Top_Logic_None qta)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta (Top_Logic_Some qta u)) 1) :pattern (
      (Top_Logic_Some
        qta
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_Logic_Some_proj_1 qta x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Logic_Some_proj_1 qta (Top_Logic_Some qta u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta) u)
        (or
          (= u (Top_Logic_None qta))
          (= u (Top_Logic_Some qta (Top_Logic_Some_proj_1 qta u))))))))

(declare-sort Top_polynomial 0)

;; "Top_polynomial"
(declare-fun Top_polynomial1 () ty)

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a2 ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a2 x x1)))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "witness"
(declare-fun witness2 () Top_Nonce_nonce)

;; "witness"
(declare-fun witness3 () Top_Block_block)

;; "&m"
(declare-fun etm () memory)

;; "&1"
(declare-fun et1 () uni)

;; "&1_sort"
(assert (sort (tuple21 bool memory1) et1))

;; "&2"
(declare-fun et2 () (tuple2 (tuple8 Bool
  (Top_List_list Top_Nonce_nonce)
  Bool
  Int
  Top_Nonce_nonce
  Top_Block_block
  Top_Poly_in_poly_in
  Top_Poly_out_poly_out)
  memory))

;; "Top_FullRO_RO_/m"
(declare-fun Top_FullRO_RO_slm (memory) (Top_FMap_fmap (tuple2 Top_Nonce_nonce
  Top_C_counter)
  Top_Block_block))

;; "unamed_lambda"
(declare-fun unamed_lambda () (Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) Top_Nonce_nonce))

;; "t2tb"
(declare-fun t2tb (Top_Nonce_nonce) uni)

;; "t2tb_sort"
(assert (forall ((x Top_Nonce_nonce)) (sort Top_Nonce_nonce1 (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) Top_Nonce_nonce)

;; "BridgeL"
(assert
  (forall ((i Top_Nonce_nonce))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Nonce_nonce1 j) (= (t2tb (tb2t j)) j)) :pattern (
    (t2tb
      (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 ((tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out)))
    (sort
      (tuple41
        Top_Nonce_nonce1
        (Top_List_list1 Top_Byte_byte1)
        (Top_List_list1 Top_Byte_byte1)
        Top_Poly_out_poly_out1)
      (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out))

;; "BridgeL"
(assert
  (forall ((i (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out)))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb1 (tb2t1 j)) j) :pattern ((t2tb1 (tb2t1 j))) )))

;; "unamed_lambda_spec"
(assert
  (forall ((p (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out)))
    (= (select unamed_lambda p) (tb2t
                                  (proj4_0
                                    Top_Nonce_nonce1
                                    (Top_List_list1 Top_Byte_byte1)
                                    (Top_List_list1 Top_Byte_byte1)
                                    Top_Poly_out_poly_out1
                                    (t2tb1 p))))))

;; "Top_SKE_RND_Mem_/lc"
(declare-fun Top_SKE_RND_Mem_sllc (memory) (Top_List_list (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out)))

;; "Top_List_map"
(declare-fun Top_List_map (ty
  ty
  uni
  uni) uni)

;; "Top_List_map_sort"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qtb) (Top_List_map qta qtb x x1)))))

;; "Top_List_map"
(declare-fun Top_List_map1 ((Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) Top_Nonce_nonce)
  (Top_List_list (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out))) (Top_List_list Top_Nonce_nonce))

;; "t2tb"
(declare-fun t2tb2 ((Top_List_list Top_Nonce_nonce)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_Nonce_nonce)))
    (sort (Top_List_list1 Top_Nonce_nonce1) (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Top_List_list Top_Nonce_nonce))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_Nonce_nonce)))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb2 (tb2t2 j)) j) :pattern ((t2tb2 (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 ((Top_List_list (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out))))
    (sort
      (Top_List_list1
        (tuple41
          Top_Nonce_nonce1
          (Top_List_list1 Top_Byte_byte1)
          (Top_List_list1 Top_Byte_byte1)
          Top_Poly_out_poly_out1))
      (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) (Top_List_list (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out)))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out))))
    (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb3 (tb2t3 j)) j) :pattern ((t2tb3 (tb2t3 j))) )))

;; "Top_List_map'def"
(assert
  (forall ((f (Array (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out) Top_Nonce_nonce)))
    (and
      (= (Top_List_map1
           f
           (tb2t3
             (Top_List_lbrb
               (tuple41
                 Top_Nonce_nonce1
                 (Top_List_list1 Top_Byte_byte1)
                 (Top_List_list1 Top_Byte_byte1)
                 Top_Poly_out_poly_out1)))) (tb2t2
                                              (Top_List_lbrb
                                                Top_Nonce_nonce1)))
      (forall ((y (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out)) (ys (Top_List_list (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out))))
        (= (Top_List_map1
             f
             (tb2t3
               (Top_List_clcl
                 (tuple41
                   Top_Nonce_nonce1
                   (Top_List_list1 Top_Byte_byte1)
                   (Top_List_list1 Top_Byte_byte1)
                   Top_Poly_out_poly_out1)
                 (t2tb1 y)
                 (t2tb3 ys)))) (tb2t2
                                 (Top_List_clcl
                                   Top_Nonce_nonce1
                                   (t2tb (select f y))
                                   (t2tb2 (Top_List_map1 f ys)))))))))

;; "Top_List_map'def"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((f uni))
      (and
        (= (Top_List_map qta qtb f (Top_List_lbrb qta)) (Top_List_lbrb qtb))
        (forall ((y uni) (ys uni))
          (= (Top_List_map qta qtb f (Top_List_clcl qta y ys)) (Top_List_clcl
                                                                 qtb
                                                                 (infix_at
                                                                   qtb
                                                                   qta
                                                                   f
                                                                   y)
                                                                 (Top_List_map
                                                                   qta
                                                                   qtb
                                                                   f
                                                                   ys))))))))

;; "Top_List_mem"
(declare-fun Top_List_mem (ty
  uni
  uni) Bool)

;; "Top_List_mem'def"
(assert
  (forall ((qta ty))
    (forall ((z uni))
      (=>
        (sort qta z)
        (and
          (not (Top_List_mem qta (Top_List_lbrb qta) z))
          (forall ((x uni) (sqt uni))
            (=>
              (sort qta x)
              (=
                (Top_List_mem qta (Top_List_clcl qta x sqt) z)
                (or (= z x) (Top_List_mem qta sqt z))))))))))

;; "Top_List_undup"
(declare-fun Top_List_undup (ty
  uni) uni)

;; "Top_List_undup_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_List_list1 qta) (Top_List_undup qta x)))))

;; "Top_List_undup"
(declare-fun Top_List_undup1 ((Top_List_list Top_Nonce_nonce)) (Top_List_list Top_Nonce_nonce))

;; "Top_List_undup'def"
(assert
  (and
    (= (Top_List_undup1 (tb2t2 (Top_List_lbrb Top_Nonce_nonce1))) (tb2t2
                                                                    (Top_List_lbrb
                                                                    Top_Nonce_nonce1)))
    (forall ((x Top_Nonce_nonce) (sqt (Top_List_list Top_Nonce_nonce)))
      (let ((s (tb2t2 (Top_List_clcl Top_Nonce_nonce1 (t2tb x) (t2tb2 sqt)))))
        (ite (Top_List_mem Top_Nonce_nonce1 (t2tb2 sqt) (t2tb x))
          (= (Top_List_undup1 s) (Top_List_undup1 sqt))
          (= (Top_List_undup1 s) (tb2t2
                                   (Top_List_clcl
                                     Top_Nonce_nonce1
                                     (t2tb x)
                                     (t2tb2 (Top_List_undup1 sqt))))))))))

;; "Top_List_undup'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_undup qta (Top_List_lbrb qta)) (Top_List_lbrb qta))
      (forall ((x uni) (sqt uni))
        (let ((s (Top_List_clcl qta x sqt)))
          (ite (Top_List_mem qta sqt x)
            (= (Top_List_undup qta s) (Top_List_undup qta sqt))
            (= (Top_List_undup qta s) (Top_List_clcl
                                        qta
                                        x
                                        (Top_List_undup qta sqt)))))))))

;; "Top_List_nth"
(declare-fun Top_List_nth (ty
  uni
  uni
  Int) uni)

;; "Top_List_nth_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni) (x2 Int))
      (sort qta (Top_List_nth qta x x1 x2)))))

;; "Top_List_nth"
(declare-fun Top_List_nth1 (Top_Nonce_nonce
  (Top_List_list Top_Nonce_nonce)
  Int) Top_Nonce_nonce)

;; "Top_List_nth'def"
(assert
  (forall ((x Top_Nonce_nonce) (n Int))
    (and
      (= (Top_List_nth1 x (tb2t2 (Top_List_lbrb Top_Nonce_nonce1)) n) x)
      (forall ((y Top_Nonce_nonce) (ys (Top_List_list Top_Nonce_nonce)))
        (let ((xs (tb2t2
                    (Top_List_clcl Top_Nonce_nonce1 (t2tb y) (t2tb2 ys)))))
          (ite (= n 0)
            (= (Top_List_nth1 x xs n) y)
            (= (Top_List_nth1 x xs n) (Top_List_nth1 x ys (+ n (- 1))))))))))

;; "Top_List_nth'def"
(assert
  (forall ((qta ty))
    (forall ((x uni) (n Int))
      (=>
        (sort qta x)
        (and
          (= (Top_List_nth qta x (Top_List_lbrb qta) n) x)
          (forall ((y uni) (ys uni))
            (=>
              (sort qta y)
              (let ((xs (Top_List_clcl qta y ys)))
                (ite (= n 0)
                  (= (Top_List_nth qta x xs n) y)
                  (= (Top_List_nth qta x xs n) (Top_List_nth
                                                 qta
                                                 x
                                                 ys
                                                 (+ n (- 1)))))))))))))

;; "Top_C_ofint"
(declare-fun Top_C_ofint (Int) (Top_Logic_option Top_C_counter))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt (ty
  uni
  uni) uni)

;; "Top_Logic_odflt_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni)) (sort qta (Top_Logic_odflt qta x x1)))))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt1 (Top_Block_block
  (Top_Logic_option Top_Block_block)) Top_Block_block)

;; "t2tb"
(declare-fun t2tb4 ((Top_Logic_option Top_Block_block)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_Block_block)))
    (sort (Top_Logic_option1 Top_Block_block1) (t2tb4 x))))

;; "tb2t"
(declare-fun tb2t4 (uni) (Top_Logic_option Top_Block_block))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_Block_block)))
    (! (= (tb2t4 (t2tb4 i)) i) :pattern ((t2tb4 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_Block_block1) j)
         (= (t2tb4 (tb2t4 j)) j)) :pattern ((t2tb4 (tb2t4 j))) )))

;; "t2tb"
(declare-fun t2tb5 (Top_Block_block) uni)

;; "t2tb_sort"
(assert (forall ((x Top_Block_block)) (sort Top_Block_block1 (t2tb5 x))))

;; "tb2t"
(declare-fun tb2t5 (uni) Top_Block_block)

;; "BridgeL"
(assert
  (forall ((i Top_Block_block))
    (! (= (tb2t5 (t2tb5 i)) i) :pattern ((t2tb5 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Block_block1 j) (= (t2tb5 (tb2t5 j)) j)) :pattern (
    (t2tb5
      (tb2t5 j))) )))

;; "Top_Logic_odflt'def"
(assert
  (forall ((d Top_Block_block))
    (and
      (= (Top_Logic_odflt1 d (tb2t4 (Top_Logic_None Top_Block_block1))) d)
      (forall ((x Top_Block_block))
        (= (Top_Logic_odflt1
             d
             (tb2t4 (Top_Logic_Some Top_Block_block1 (t2tb5 x)))) x)))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((qta ty))
    (forall ((d uni))
      (=>
        (sort qta d)
        (and
          (= (Top_Logic_odflt qta d (Top_Logic_None qta)) d)
          (forall ((x uni))
            (=>
              (sort qta x)
              (= (Top_Logic_odflt qta d (Top_Logic_Some qta x)) x))))))))

;; "Top_C_ofintd"
(declare-fun Top_C_ofintd (Int) Top_C_counter)

;; "t2tb"
(declare-fun t2tb6 ((Top_Logic_option Top_C_counter)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_C_counter)))
    (sort (Top_Logic_option1 Top_C_counter1) (t2tb6 x))))

;; "tb2t"
(declare-fun tb2t6 (uni) (Top_Logic_option Top_C_counter))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_C_counter)))
    (! (= (tb2t6 (t2tb6 i)) i) :pattern ((t2tb6 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_C_counter1) j)
         (= (t2tb6 (tb2t6 j)) j)) :pattern ((t2tb6 (tb2t6 j))) )))

;; "t2tb"
(declare-fun t2tb7 (Top_C_counter) uni)

;; "t2tb_sort"
(assert (forall ((x Top_C_counter)) (sort Top_C_counter1 (t2tb7 x))))

;; "tb2t"
(declare-fun tb2t7 (uni) Top_C_counter)

;; "BridgeL"
(assert
  (forall ((i Top_C_counter))
    (! (= (tb2t7 (t2tb7 i)) i) :pattern ((t2tb7 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_C_counter1 j) (= (t2tb7 (tb2t7 j)) j)) :pattern (
    (t2tb7
      (tb2t7 j))) )))

;; "Top_C_ofintd'def"
(assert
  (forall ((x Int))
    (= (Top_C_ofintd x) (tb2t7
                          (Top_Logic_odflt
                            Top_C_counter1
                            (witness1 Top_C_counter1)
                            (t2tb6 (Top_C_ofint x)))))))

;; "Top_FMap_tomap"
(declare-fun Top_FMap_tomap (ty
  ty
  uni) uni)

;; "Top_FMap_tomap_sort"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((x uni))
      (sort
        (infix_mngt qta (Top_Logic_option1 qtb))
        (Top_FMap_tomap qtb qta x)))))

;; "Top_FMap___[_]"
(declare-fun Top_FMap___lb_rb (ty
  ty
  uni
  uni) uni)

;; "Top_FMap___[_]_sort"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_Logic_option1 qtb) (Top_FMap___lb_rb qtb qta x x1)))))

;; "Top_FMap___[_]"
(declare-fun Top_FMap___lb_rb1 ((Top_FMap_fmap (tuple2 Top_Nonce_nonce
  Top_C_counter)
  Top_Block_block)
  (tuple2 Top_Nonce_nonce
  Top_C_counter)) (Top_Logic_option Top_Block_block))

;; "t2tb"
(declare-fun t2tb8 ((tuple2 Top_Nonce_nonce
  Top_C_counter)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (tuple2 Top_Nonce_nonce Top_C_counter)))
    (sort (tuple21 Top_Nonce_nonce1 Top_C_counter1) (t2tb8 x))))

;; "tb2t"
(declare-fun tb2t8 (uni) (tuple2 Top_Nonce_nonce
  Top_C_counter))

;; "BridgeL"
(assert
  (forall ((i (tuple2 Top_Nonce_nonce Top_C_counter)))
    (! (= (tb2t8 (t2tb8 i)) i) :pattern ((t2tb8 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (tuple21 Top_Nonce_nonce1 Top_C_counter1) j)
         (= (t2tb8 (tb2t8 j)) j)) :pattern ((t2tb8 (tb2t8 j))) )))

;; "t2tb"
(declare-fun t2tb9 ((Array (tuple2 Top_Nonce_nonce
  Top_C_counter) (Top_Logic_option Top_Block_block))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array (tuple2 Top_Nonce_nonce Top_C_counter) (Top_Logic_option Top_Block_block))))
    (sort
      (infix_mngt
        (tuple21 Top_Nonce_nonce1 Top_C_counter1)
        (Top_Logic_option1 Top_Block_block1))
      (t2tb9 x))))

;; "tb2t"
(declare-fun tb2t9 (uni) (Array (tuple2 Top_Nonce_nonce
  Top_C_counter) (Top_Logic_option Top_Block_block)))

;; "BridgeL"
(assert
  (forall ((i (Array (tuple2 Top_Nonce_nonce Top_C_counter) (Top_Logic_option Top_Block_block))))
    (! (= (tb2t9 (t2tb9 i)) i) :pattern ((t2tb9 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             (tuple21 Top_Nonce_nonce1 Top_C_counter1)
             (Top_Logic_option1 Top_Block_block1))
           j)
         (= (t2tb9 (tb2t9 j)) j)) :pattern ((t2tb9 (tb2t9 j))) )))

;; "t2tb"
(declare-fun t2tb10 ((Top_FMap_fmap (tuple2 Top_Nonce_nonce
  Top_C_counter)
  Top_Block_block)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_FMap_fmap (tuple2 Top_Nonce_nonce Top_C_counter) Top_Block_block)))
    (sort
      (Top_FMap_fmap1
        (tuple21 Top_Nonce_nonce1 Top_C_counter1)
        Top_Block_block1)
      (t2tb10 x))))

;; "tb2t"
(declare-fun tb2t10 (uni) (Top_FMap_fmap (tuple2 Top_Nonce_nonce
  Top_C_counter)
  Top_Block_block))

;; "BridgeL"
(assert
  (forall ((i (Top_FMap_fmap (tuple2 Top_Nonce_nonce Top_C_counter) Top_Block_block)))
    (! (= (tb2t10 (t2tb10 i)) i) :pattern ((t2tb10 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (Top_FMap_fmap1
             (tuple21 Top_Nonce_nonce1 Top_C_counter1)
             Top_Block_block1)
           j)
         (= (t2tb10 (tb2t10 j)) j)) :pattern ((t2tb10 (tb2t10 j))) )))

;; "Top_FMap___[_]'def"
(assert
  (forall ((m (Top_FMap_fmap (tuple2 Top_Nonce_nonce Top_C_counter) Top_Block_block)) (x (tuple2 Top_Nonce_nonce Top_C_counter)))
    (= (Top_FMap___lb_rb1 m x) (tb2t4
                                 (infix_at
                                   (Top_Logic_option1 Top_Block_block1)
                                   (tuple21 Top_Nonce_nonce1 Top_C_counter1)
                                   (Top_FMap_tomap
                                     Top_Block_block1
                                     (tuple21
                                       Top_Nonce_nonce1
                                       Top_C_counter1)
                                     (t2tb10 m))
                                   (t2tb8 x))))))

;; "Top_FMap___[_]'def"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((m uni) (x uni))
      (= (Top_FMap___lb_rb qtb qta m x) (infix_at
                                          (Top_Logic_option1 qtb)
                                          qta
                                          (Top_FMap_tomap qtb qta m)
                                          x)))))

;; "Top_Poly_in_poly_in_size"
(declare-fun Top_Poly_in_poly_in_size () Int)

;; "Top_Poly_out_poly_out_size"
(declare-fun Top_Poly_out_poly_out_size () Int)

;; "Top_Block_bytes_of_block"
(declare-fun Top_Block_bytes_of_block (Top_Block_block) (Top_List_list Top_Byte_byte))

;; "Top_List_take"
(declare-fun Top_List_take (ty
  Int
  uni) uni)

;; "Top_List_take_sort"
(assert
  (forall ((qta ty))
    (forall ((x Int) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_take qta x x1)))))

;; "Top_List_take'def"
(assert
  (forall ((qta ty))
    (forall ((n Int))
      (and
        (= (Top_List_take qta n (Top_List_lbrb qta)) (Top_List_lbrb qta))
        (forall ((y uni) (ys uni))
          (let ((xs (Top_List_clcl qta y ys)))
            (ite (<= n 0)
              (= (Top_List_take qta n xs) (Top_List_lbrb qta))
              (= (Top_List_take qta n xs) (Top_List_clcl
                                            qta
                                            y
                                            (Top_List_take
                                              qta
                                              (+ n (- 1))
                                              ys))))))))))

;; "Top_Poly_in_poly_in_of_bytes"
(declare-fun Top_Poly_in_poly_in_of_bytes ((Top_List_list Top_Byte_byte)) (Top_Logic_option Top_Poly_in_poly_in))

;; "Top_Poly_in_poly_in_of_bytesd"
(declare-fun Top_Poly_in_poly_in_of_bytesd ((Top_List_list Top_Byte_byte)) Top_Poly_in_poly_in)

;; "t2tb"
(declare-fun t2tb11 ((Top_Logic_option Top_Poly_in_poly_in)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_Poly_in_poly_in)))
    (sort (Top_Logic_option1 Top_Poly_in_poly_in1) (t2tb11 x))))

;; "tb2t"
(declare-fun tb2t11 (uni) (Top_Logic_option Top_Poly_in_poly_in))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_Poly_in_poly_in)))
    (! (= (tb2t11 (t2tb11 i)) i) :pattern ((t2tb11 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_Poly_in_poly_in1) j)
         (= (t2tb11 (tb2t11 j)) j)) :pattern ((t2tb11 (tb2t11 j))) )))

;; "t2tb"
(declare-fun t2tb12 (Top_Poly_in_poly_in) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_Poly_in_poly_in)) (sort Top_Poly_in_poly_in1 (t2tb12 x))))

;; "tb2t"
(declare-fun tb2t12 (uni) Top_Poly_in_poly_in)

;; "BridgeL"
(assert
  (forall ((i Top_Poly_in_poly_in))
    (! (= (tb2t12 (t2tb12 i)) i) :pattern ((t2tb12 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Poly_in_poly_in1 j) (= (t2tb12 (tb2t12 j)) j)) :pattern (
    (t2tb12
      (tb2t12 j))) )))

;; "Top_Poly_in_poly_in_of_bytesd'def"
(assert
  (forall ((x (Top_List_list Top_Byte_byte)))
    (= (Top_Poly_in_poly_in_of_bytesd x) (tb2t12
                                           (Top_Logic_odflt
                                             Top_Poly_in_poly_in1
                                             (witness1 Top_Poly_in_poly_in1)
                                             (t2tb11
                                               (Top_Poly_in_poly_in_of_bytes
                                                 x)))))))

;; "Top_List_drop"
(declare-fun Top_List_drop (ty
  Int
  uni) uni)

;; "Top_List_drop_sort"
(assert
  (forall ((qta ty))
    (forall ((x Int) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_drop qta x x1)))))

;; "Top_List_drop'def"
(assert
  (forall ((qta ty))
    (forall ((n Int))
      (and
        (= (Top_List_drop qta n (Top_List_lbrb qta)) (Top_List_lbrb qta))
        (forall ((y uni) (ys uni))
          (let ((xs (Top_List_clcl qta y ys)))
            (ite (<= n 0)
              (= (Top_List_drop qta n xs) xs)
              (= (Top_List_drop qta n xs) (Top_List_drop qta (+ n (- 1)) ys)))))))))

;; "Top_Poly_out_poly_out_of_bytes"
(declare-fun Top_Poly_out_poly_out_of_bytes ((Top_List_list Top_Byte_byte)) (Top_Logic_option Top_Poly_out_poly_out))

;; "Top_Poly_out_poly_out_of_bytesd"
(declare-fun Top_Poly_out_poly_out_of_bytesd ((Top_List_list Top_Byte_byte)) Top_Poly_out_poly_out)

;; "t2tb"
(declare-fun t2tb13 ((Top_Logic_option Top_Poly_out_poly_out)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_Poly_out_poly_out)))
    (sort (Top_Logic_option1 Top_Poly_out_poly_out1) (t2tb13 x))))

;; "tb2t"
(declare-fun tb2t13 (uni) (Top_Logic_option Top_Poly_out_poly_out))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_Poly_out_poly_out)))
    (! (= (tb2t13 (t2tb13 i)) i) :pattern ((t2tb13 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_Poly_out_poly_out1) j)
         (= (t2tb13 (tb2t13 j)) j)) :pattern ((t2tb13 (tb2t13 j))) )))

;; "t2tb"
(declare-fun t2tb14 (Top_Poly_out_poly_out) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_Poly_out_poly_out))
    (sort Top_Poly_out_poly_out1 (t2tb14 x))))

;; "tb2t"
(declare-fun tb2t14 (uni) Top_Poly_out_poly_out)

;; "BridgeL"
(assert
  (forall ((i Top_Poly_out_poly_out))
    (! (= (tb2t14 (t2tb14 i)) i) :pattern ((t2tb14 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Poly_out_poly_out1 j) (= (t2tb14 (tb2t14 j)) j)) :pattern (
    (t2tb14
      (tb2t14 j))) )))

;; "Top_Poly_out_poly_out_of_bytesd'def"
(assert
  (forall ((x (Top_List_list Top_Byte_byte)))
    (= (Top_Poly_out_poly_out_of_bytesd x) (tb2t14
                                             (Top_Logic_odflt
                                               Top_Poly_out_poly_out1
                                               (witness1
                                                 Top_Poly_out_poly_out1)
                                               (t2tb13
                                                 (Top_Poly_out_poly_out_of_bytes
                                                   x)))))))

;; "Top_mk_rs"
(declare-fun Top_mk_rs (Top_Block_block) (tuple2 Top_Poly_in_poly_in
  Top_Poly_out_poly_out))

;; "t2tb"
(declare-fun t2tb15 ((Top_List_list Top_Byte_byte)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_Byte_byte)))
    (sort (Top_List_list1 Top_Byte_byte1) (t2tb15 x))))

;; "tb2t"
(declare-fun tb2t15 (uni) (Top_List_list Top_Byte_byte))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_Byte_byte)))
    (! (= (tb2t15 (t2tb15 i)) i) :pattern ((t2tb15 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb15 (tb2t15 j)) j) :pattern ((t2tb15 (tb2t15 j))) )))

;; "Top_mk_rs'def"
(assert
  (forall ((b Top_Block_block))
    (let ((b1 (tb2t15
                (Top_List_take
                  Top_Byte_byte1
                  (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size)
                  (t2tb15 (Top_Block_bytes_of_block b))))))
      (= (Top_mk_rs b) (Tuple2
                         (Top_Poly_in_poly_in_of_bytesd
                           (tb2t15
                             (Top_List_take
                               Top_Byte_byte1
                               Top_Poly_in_poly_in_size
                               (t2tb15 b1))))
                         (Top_Poly_out_poly_out_of_bytesd
                           (tb2t15
                             (Top_List_drop
                               Top_Byte_byte1
                               Top_Poly_in_poly_in_size
                               (t2tb15 b1)))))))))

;; "Top_topol"
(declare-fun Top_topol ((Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)) Top_polynomial)

;; "unamed_lambda"
(declare-fun unamed_lambda1 () (Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) (tuple2 Top_polynomial
  Top_Poly_out_poly_out)))

;; "t2tb"
(declare-fun t2tb16 (Top_polynomial) uni)

;; "t2tb_sort"
(assert (forall ((x Top_polynomial)) (sort Top_polynomial1 (t2tb16 x))))

;; "tb2t"
(declare-fun tb2t16 (uni) Top_polynomial)

;; "BridgeL"
(assert
  (forall ((i Top_polynomial))
    (! (= (tb2t16 (t2tb16 i)) i) :pattern ((t2tb16 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_polynomial1 j) (= (t2tb16 (tb2t16 j)) j)) :pattern (
    (t2tb16
      (tb2t16 j))) )))

;; "t2tb"
(declare-fun t2tb17 ((tuple2 Top_polynomial
  Top_Poly_out_poly_out)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (tuple2 Top_polynomial Top_Poly_out_poly_out)))
    (sort (tuple21 Top_polynomial1 Top_Poly_out_poly_out1) (t2tb17 x))))

;; "tb2t"
(declare-fun tb2t17 (uni) (tuple2 Top_polynomial
  Top_Poly_out_poly_out))

;; "BridgeL"
(assert
  (forall ((i (tuple2 Top_polynomial Top_Poly_out_poly_out)))
    (! (= (tb2t17 (t2tb17 i)) i) :pattern ((t2tb17 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (tuple21 Top_polynomial1 Top_Poly_out_poly_out1) j)
         (= (t2tb17 (tb2t17 j)) j)) :pattern ((t2tb17 (tb2t17 j))) )))

;; "t2tb"
(declare-fun t2tb18 ((Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) (tuple2 Top_polynomial
  Top_Poly_out_poly_out))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out) (tuple2 Top_polynomial Top_Poly_out_poly_out))))
    (sort
      (infix_mngt
        (tuple41
          Top_Nonce_nonce1
          (Top_List_list1 Top_Byte_byte1)
          (Top_List_list1 Top_Byte_byte1)
          Top_Poly_out_poly_out1)
        (tuple21 Top_polynomial1 Top_Poly_out_poly_out1))
      (t2tb18 x))))

;; "tb2t"
(declare-fun tb2t18 (uni) (Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) (tuple2 Top_polynomial
  Top_Poly_out_poly_out)))

;; "BridgeL"
(assert
  (forall ((i (Array (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out) (tuple2 Top_polynomial Top_Poly_out_poly_out))))
    (! (= (tb2t18 (t2tb18 i)) i) :pattern ((t2tb18 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             (tuple41
               Top_Nonce_nonce1
               (Top_List_list1 Top_Byte_byte1)
               (Top_List_list1 Top_Byte_byte1)
               Top_Poly_out_poly_out1)
             (tuple21 Top_polynomial1 Top_Poly_out_poly_out1))
           j)
         (= (t2tb18 (tb2t18 j)) j)) :pattern ((t2tb18 (tb2t18 j))) )))

;; "unamed_lambda_spec"
(assert
  (forall ((c (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out)))
    (= (tb2t17
         (infix_at
           (tuple21 Top_polynomial1 Top_Poly_out_poly_out1)
           (tuple41
             Top_Nonce_nonce1
             (Top_List_list1 Top_Byte_byte1)
             (Top_List_list1 Top_Byte_byte1)
             Top_Poly_out_poly_out1)
           (t2tb18 unamed_lambda1)
           (t2tb1 c))) (tb2t17
                         (Tuple21
                           Top_polynomial1
                           Top_Poly_out_poly_out1
                           (t2tb16
                             (Top_topol
                               (tb2t15
                                 (proj4_1
                                   Top_Nonce_nonce1
                                   (Top_List_list1 Top_Byte_byte1)
                                   (Top_List_list1 Top_Byte_byte1)
                                   Top_Poly_out_poly_out1
                                   (t2tb1 c)))
                               (tb2t15
                                 (proj4_2
                                   Top_Nonce_nonce1
                                   (Top_List_list1 Top_Byte_byte1)
                                   (Top_List_list1 Top_Byte_byte1)
                                   Top_Poly_out_poly_out1
                                   (t2tb1 c)))))
                           (proj4_3
                             Top_Nonce_nonce1
                             (Top_List_list1 Top_Byte_byte1)
                             (Top_List_list1 Top_Byte_byte1)
                             Top_Poly_out_poly_out1
                             (t2tb1 c)))))))

;; "unamed_lambda"
(declare-fun unamed_lambda2 (Top_Nonce_nonce) (Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) Bool))

;; "t2tb"
(declare-fun t2tb19 (Bool) uni)

;; "t2tb_sort"
(assert (forall ((x Bool)) (sort bool (t2tb19 x))))

;; "tb2t"
(declare-fun tb2t19 (uni) Bool)

;; "BridgeL"
(assert
  (forall ((i Bool)) (! (= (tb2t19 (t2tb19 i)) i) :pattern ((t2tb19 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort bool j) (= (t2tb19 (tb2t19 j)) j)) :pattern ((t2tb19
                                                                (tb2t19 j))) )))

;; "t2tb"
(declare-fun t2tb20 ((Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out) Bool)))
    (sort
      (infix_mngt
        (tuple41
          Top_Nonce_nonce1
          (Top_List_list1 Top_Byte_byte1)
          (Top_List_list1 Top_Byte_byte1)
          Top_Poly_out_poly_out1)
        bool)
      (t2tb20 x))))

;; "tb2t"
(declare-fun tb2t20 (uni) (Array (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out) Bool))

;; "BridgeL"
(assert
  (forall ((i (Array (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out) Bool)))
    (! (= (tb2t20 (t2tb20 i)) i) :pattern ((t2tb20 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             (tuple41
               Top_Nonce_nonce1
               (Top_List_list1 Top_Byte_byte1)
               (Top_List_list1 Top_Byte_byte1)
               Top_Poly_out_poly_out1)
             bool)
           j)
         (= (t2tb20 (tb2t20 j)) j)) :pattern ((t2tb20 (tb2t20 j))) )))

;; "unamed_lambda_spec"
(assert
  (forall ((n Top_Nonce_nonce) (c (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out)))
    (=
      (= (tb2t19
           (infix_at
             bool
             (tuple41
               Top_Nonce_nonce1
               (Top_List_list1 Top_Byte_byte1)
               (Top_List_list1 Top_Byte_byte1)
               Top_Poly_out_poly_out1)
             (t2tb20 (unamed_lambda2 n))
             (t2tb1 c))) true)
      (= (tb2t
           (proj4_0
             Top_Nonce_nonce1
             (Top_List_list1 Top_Byte_byte1)
             (Top_List_list1 Top_Byte_byte1)
             Top_Poly_out_poly_out1
             (t2tb1 c))) n))))

;; "Top_List_filter"
(declare-fun Top_List_filter (ty
  uni
  uni) uni)

;; "Top_List_filter_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_filter qta x x1)))))

;; "Top_List_filter'def"
(assert
  (forall ((qta ty))
    (forall ((p uni))
      (and
        (= (Top_List_filter qta p (Top_List_lbrb qta)) (Top_List_lbrb qta))
        (forall ((y uni) (ys uni))
          (let ((xs (Top_List_clcl qta y ys)))
            (ite (= (tb2t19 (infix_at bool qta p y)) true)
              (= (Top_List_filter qta p xs) (Top_List_clcl
                                              qta
                                              y
                                              (Top_List_filter qta p ys)))
              (= (Top_List_filter qta p xs) (Top_List_filter qta p ys)))))))))

;; "Top_poly1305_eval"
(declare-fun Top_poly1305_eval (Top_Poly_in_poly_in
  Top_polynomial) Top_Poly_out_poly_out)

;; "Top_+"
(declare-fun Top_pl (Top_Poly_out_poly_out
  Top_Poly_out_poly_out) Top_Poly_out_poly_out)

;; "Top_poly1305"
(declare-fun Top_poly1305 (Top_Poly_in_poly_in
  Top_Poly_out_poly_out
  Top_polynomial) Top_Poly_out_poly_out)

;; "Top_poly1305'def"
(assert
  (forall ((r Top_Poly_in_poly_in) (s Top_Poly_out_poly_out) (p Top_polynomial))
    (= (Top_poly1305 r s p) (Top_pl s (Top_poly1305_eval r p)))))

;; "unamed_lambda"
(declare-fun unamed_lambda3 (Top_Poly_in_poly_in
  Top_Poly_out_poly_out) (Array (tuple2 Top_polynomial
  Top_Poly_out_poly_out) Bool))

;; "t2tb"
(declare-fun t2tb21 ((Array (tuple2 Top_polynomial
  Top_Poly_out_poly_out) Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array (tuple2 Top_polynomial Top_Poly_out_poly_out) Bool)))
    (sort
      (infix_mngt (tuple21 Top_polynomial1 Top_Poly_out_poly_out1) bool)
      (t2tb21 x))))

;; "tb2t"
(declare-fun tb2t21 (uni) (Array (tuple2 Top_polynomial
  Top_Poly_out_poly_out) Bool))

;; "BridgeL"
(assert
  (forall ((i (Array (tuple2 Top_polynomial Top_Poly_out_poly_out) Bool)))
    (! (= (tb2t21 (t2tb21 i)) i) :pattern ((t2tb21 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt (tuple21 Top_polynomial1 Top_Poly_out_poly_out1) bool)
           j)
         (= (t2tb21 (tb2t21 j)) j)) :pattern ((t2tb21 (tb2t21 j))) )))

;; "unamed_lambda_spec"
(assert
  (forall ((r Top_Poly_in_poly_in) (s Top_Poly_out_poly_out) (pt (tuple2 Top_polynomial Top_Poly_out_poly_out)))
    (=
      (= (tb2t19
           (infix_at
             bool
             (tuple21 Top_polynomial1 Top_Poly_out_poly_out1)
             (t2tb21 (unamed_lambda3 r s))
             (t2tb17 pt))) true)
      (= (tb2t14
           (proj2_11 Top_polynomial1 Top_Poly_out_poly_out1 (t2tb17 pt))) 
      (Top_poly1305
        r
        s
        (tb2t16
          (proj2_01 Top_polynomial1 Top_Poly_out_poly_out1 (t2tb17 pt))))))))

;; "Top_List_has"
(declare-fun Top_List_has (ty
  uni
  uni) Bool)

;; "Top_List_has'def"
(assert
  (forall ((qta ty))
    (forall ((p uni))
      (and
        (not (Top_List_has qta p (Top_List_lbrb qta)))
        (forall ((y uni) (ys uni))
          (=
            (Top_List_has qta p (Top_List_clcl qta y ys))
            (or
              (= (tb2t19 (infix_at bool qta p y)) true)
              (Top_List_has qta p ys))))))))

;; "Top_test_poly"
(declare-fun Top_test_poly (Top_Nonce_nonce
  (Top_List_list (tuple4 Top_Nonce_nonce
  (Top_List_list Top_Byte_byte)
  (Top_List_list Top_Byte_byte)
  Top_Poly_out_poly_out))
  Top_Poly_in_poly_in
  Top_Poly_out_poly_out) Bool)

;; "t2tb"
(declare-fun t2tb22 ((Top_List_list (tuple2 Top_polynomial
  Top_Poly_out_poly_out))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list (tuple2 Top_polynomial Top_Poly_out_poly_out))))
    (sort
      (Top_List_list1 (tuple21 Top_polynomial1 Top_Poly_out_poly_out1))
      (t2tb22 x))))

;; "tb2t"
(declare-fun tb2t22 (uni) (Top_List_list (tuple2 Top_polynomial
  Top_Poly_out_poly_out)))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list (tuple2 Top_polynomial Top_Poly_out_poly_out))))
    (! (= (tb2t22 (t2tb22 i)) i) :pattern ((t2tb22 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb22 (tb2t22 j)) j) :pattern ((t2tb22 (tb2t22 j))) )))

;; "Top_test_poly'def"
(assert
  (forall ((n Top_Nonce_nonce) (lc (Top_List_list (tuple4 Top_Nonce_nonce (Top_List_list Top_Byte_byte) (Top_List_list Top_Byte_byte) Top_Poly_out_poly_out))) (r Top_Poly_in_poly_in) (s Top_Poly_out_poly_out))
    (=
      (Top_test_poly n lc r s)
      (Top_List_has
        (tuple21 Top_polynomial1 Top_Poly_out_poly_out1)
        (t2tb21 (unamed_lambda3 r s))
        (Top_List_map
          (tuple41
            Top_Nonce_nonce1
            (Top_List_list1 Top_Byte_byte1)
            (Top_List_list1 Top_Byte_byte1)
            Top_Poly_out_poly_out1)
          (tuple21 Top_polynomial1 Top_Poly_out_poly_out1)
          (t2tb18 unamed_lambda1)
          (Top_List_filter
            (tuple41
              Top_Nonce_nonce1
              (Top_List_list1 Top_Byte_byte1)
              (Top_List_list1 Top_Byte_byte1)
              Top_Poly_out_poly_out1)
            (t2tb20 (unamed_lambda2 n))
            (t2tb3 lc)))))))

;; Goal "goal"
(assert
  (not
  (not
    (exists ((j Int))
      (and
        (and (<= 0 j) (< j 0))
        (match (Top_mk_rs
                 (Top_Logic_odflt1
                   witness3
                   (Top_FMap___lb_rb1
                     (Top_FullRO_RO_slm (proj2_1 et2))
                     (Tuple2
                       (Top_List_nth1
                         witness2
                         (Top_List_undup1
                           (Top_List_map1
                             unamed_lambda
                             (Top_SKE_RND_Mem_sllc (proj2_1 et2))))
                         j)
                       (Top_C_ofintd 0))))) (((Tuple2 x x1) (Top_test_poly
                                                              (Top_List_nth1
                                                                witness2
                                                                (Top_List_undup1
                                                                  (Top_List_map1
                                                                    unamed_lambda
                                                                    (Top_SKE_RND_Mem_sllc
                                                                    (proj2_1
                                                                    et2))))
                                                                j)
                                                              (Top_SKE_RND_Mem_sllc
                                                                (proj2_1 et2))
                                                              x
                                                              x1)))))))))

(check-sat)

