;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "Top_DH_GP_ZModE_exp"
(declare-fun Top_DH_GP_ZModE_exp () ty)

(declare-sort Top_DH_G_group 0)

;; "Top_DH_G_group"
(declare-fun Top_DH_G_group1 () ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "x"
(declare-fun x () uni)

;; "x_sort"
(assert (sort Top_DH_GP_ZModE_exp x))

;; "Top_DH_G_elems"
(declare-fun Top_DH_G_elems () (Top_List_list Top_DH_G_group))

;; "Top_List_mem"
(declare-fun Top_List_mem (ty
  uni
  uni) Bool)

;; "Top_List_mem'def"
(assert
  (forall ((qta ty))
    (forall ((z uni))
      (=>
        (sort qta z)
        (and
          (not (Top_List_mem qta (Top_List_lbrb qta) z))
          (forall ((x1 uni) (sqt uni))
            (=>
              (sort qta x1)
              (=
                (Top_List_mem qta (Top_List_clcl qta x1 sqt) z)
                (or (= z x1) (Top_List_mem qta sqt z))))))))))

;; "t2tb"
(declare-fun t2tb (Top_DH_G_group) uni)

;; "t2tb_sort"
(assert (forall ((x1 Top_DH_G_group)) (sort Top_DH_G_group1 (t2tb x1))))

;; "tb2t"
(declare-fun tb2t (uni) Top_DH_G_group)

;; "BridgeL"
(assert
  (forall ((i Top_DH_G_group))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_DH_G_group1 j) (= (t2tb (tb2t j)) j)) :pattern (
    (t2tb
      (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 ((Top_List_list Top_DH_G_group)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_List_list Top_DH_G_group)))
    (sort (Top_List_list1 Top_DH_G_group1) (t2tb1 x1))))

;; "tb2t"
(declare-fun tb2t1 (uni) (Top_List_list Top_DH_G_group))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_DH_G_group)))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb1 (tb2t1 j)) j) :pattern ((t2tb1 (tb2t1 j))) )))

;; "Top_DH_G_elemsP"
(assert
  (forall ((x1 Top_DH_G_group))
    (Top_List_mem Top_DH_G_group1 (t2tb1 Top_DH_G_elems) (t2tb x1))))

;; Goal "goal"
(assert
  (not true))

(check-sat)
(get-info :reason-unknown)

