;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
;;; SMT-LIB2: real arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort distr 1)

;; "distr"
(declare-fun distr1 (ty) ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-sort Top_t 0)

;; "Top_t"
(declare-fun Top_t1 () ty)

(declare-datatypes ((tuple3 3))
  ((par (a a1 a2) ((Tuple3 (proj3_0 a)(proj3_1 a1)(proj3_2 a2))))))

;; "tuple3"
(declare-fun tuple31 (ty
  ty
  ty) ty)

;; "Tuple3"
(declare-fun Tuple31 (ty
  ty
  ty
  uni
  uni
  uni) uni)

;; "Tuple3_sort"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort (tuple31 a5 a4 a3) (Tuple31 a5 a4 a3 x x1 x2)))))

;; "proj3_0"
(declare-fun proj3_01 (ty
  ty
  ty
  uni) uni)

;; "proj3_0_sort"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a5 (proj3_01 a5 a4 a3 x)))))

;; "proj3_0'def"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a5 u) (= (proj3_01 a5 a4 a3 (Tuple31 a5 a4 a3 u u1 u2)) u)))))

;; "proj3_1"
(declare-fun proj3_11 (ty
  ty
  ty
  uni) uni)

;; "proj3_1_sort"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a4 (proj3_11 a5 a4 a3 x)))))

;; "proj3_1'def"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a4 u1) (= (proj3_11 a5 a4 a3 (Tuple31 a5 a4 a3 u u1 u2)) u1)))))

;; "proj3_2"
(declare-fun proj3_21 (ty
  ty
  ty
  uni) uni)

;; "proj3_2_sort"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((x uni)) (sort a3 (proj3_21 a5 a4 a3 x)))))

;; "proj3_2'def"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a3 u2) (= (proj3_21 a5 a4 a3 (Tuple31 a5 a4 a3 u u1 u2)) u2)))))

;; "tuple3_inversion"
(assert
  (forall ((a3 ty) (a4 ty) (a5 ty))
    (forall ((u uni))
      (=>
        (sort (tuple31 a5 a4 a3) u)
        (= u (Tuple31
               a5
               a4
               a3
               (proj3_01 a5 a4 a3 u)
               (proj3_11 a5 a4 a3 u)
               (proj3_21 a5 a4 a3 u)))))))

(declare-datatypes ((tuple2 2))
  ((par (a3 a4) ((Tuple2 (proj2_0 a3)(proj2_1 a4))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a5 ty) (a6 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a6 a5) (Tuple21 a6 a5 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a5 ty) (a6 ty)) (forall ((x uni)) (sort a6 (proj2_01 a6 a5 x)))))

;; "proj2_0'def"
(assert
  (forall ((a5 ty) (a6 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a6 u) (= (proj2_01 a6 a5 (Tuple21 a6 a5 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a5 ty) (a6 ty)) (forall ((x uni)) (sort a5 (proj2_11 a6 a5 x)))))

;; "proj2_1'def"
(assert
  (forall ((a5 ty) (a6 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a5 u1) (= (proj2_11 a6 a5 (Tuple21 a6 a5 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a5 ty) (a6 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a6 a5) u)
        (= u (Tuple21 a6 a5 (proj2_01 a6 a5 u) (proj2_11 a6 a5 u)))))))

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a5 ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a5 x x1)))))

;; "mu"
(declare-fun mu (ty
  uni
  uni) Real)

;; "mu"
(declare-fun mu1 ((distr Top_t)
  (Array Top_t Bool)) Real)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "i'"
(declare-fun iqt () Int)

;; "&m"
(declare-fun etm () memory)

;; "ge1_i'"
(assert (<= 1 iqt))

;; "Top_m"
(declare-fun Top_m () Int)

;; "lt_i'_m"
(assert (< iqt Top_m))

;; "z"
(declare-fun z () Int)

;; "Top_dt"
(declare-fun Top_dt () (distr Top_t))

;; "Top_Logic_predT_ho"
(declare-fun Top_Logic_predT_ho (ty) uni)

;; "Top_Logic_predT_ho_sort"
(assert
  (forall ((qta ty)) (sort (infix_mngt qta bool) (Top_Logic_predT_ho qta))))

;; "Top_Logic_predT_ho"
(declare-fun Top_Logic_predT_ho1 () (Array Top_t Bool))

;; "Top_Logic_predT_ho_spec"
(assert (forall ((x Top_t)) (= (select Top_Logic_predT_ho1 x) true)))

;; "t2tb"
(declare-fun t2tb (Bool) uni)

;; "t2tb_sort"
(assert (forall ((x Bool)) (sort bool (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) Bool)

;; "BridgeL"
(assert (forall ((i Bool)) (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort bool j) (= (t2tb (tb2t j)) j)) :pattern ((t2tb (tb2t j))) )))

;; "Top_Logic_predT_ho_spec"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (= (tb2t (infix_at bool qta (Top_Logic_predT_ho qta) x)) true))))

;; "Top_Logic_pred1_ho"
(declare-fun Top_Logic_pred1_ho (ty) uni)

;; "Top_Logic_pred1_ho_sort"
(assert
  (forall ((qta ty))
    (sort (infix_mngt qta (infix_mngt qta bool)) (Top_Logic_pred1_ho qta))))

;; "t2tb"
(declare-fun t2tb1 ((Array Top_t Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_t Bool))) (sort (infix_mngt Top_t1 bool) (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) (Array Top_t Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Top_t Bool)))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (infix_mngt Top_t1 bool) j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "t2tb"
(declare-fun t2tb2 (Top_t) uni)

;; "t2tb_sort"
(assert (forall ((x Top_t)) (sort Top_t1 (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) Top_t)

;; "BridgeL"
(assert
  (forall ((i Top_t)) (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_t1 j) (= (t2tb2 (tb2t2 j)) j)) :pattern ((t2tb2
                                                                (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 ((Array Top_t (Array Top_t Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_t (Array Top_t Bool))))
    (sort (infix_mngt Top_t1 (infix_mngt Top_t1 bool)) (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) (Array Top_t (Array Top_t Bool)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_t (Array Top_t Bool))))
    (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_t1 (infix_mngt Top_t1 bool)) j)
         (= (t2tb3 (tb2t3 j)) j)) :pattern ((t2tb3 (tb2t3 j))) )))

;; "Top_Logic_pred1_ho_spec"
(assert
  (forall ((x Top_t) (x1 Top_t))
    (=
      (= (select (tb2t1
                   (infix_at
                     (infix_mngt Top_t1 bool)
                     Top_t1
                     (Top_Logic_pred1_ho Top_t1)
                     (t2tb2 x))) x1) true)
      (= x1 x))))

;; "Top_Logic_pred1_ho_spec"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (=>
        (sort qta x)
        (=>
          (sort qta x1)
          (=
            (= (tb2t
                 (infix_at
                   bool
                   qta
                   (infix_at
                     (infix_mngt qta bool)
                     qta
                     (Top_Logic_pred1_ho qta)
                     x)
                   x1)) true)
            (= x1 x)))))))

;; "Top_Distr_support"
(declare-fun Top_Distr_support (ty
  uni
  uni) Bool)

;; "Top_Distr_support"
(declare-fun Top_Distr_support1 ((distr Top_t)
  Top_t) Bool)

;; "Top_Distr_support'def"
(assert
  (forall ((d (distr Top_t)) (x Top_t))
    (=
      (Top_Distr_support1 d x)
      (< 0.0 (mu1
               d
               (tb2t1
                 (infix_at
                   (infix_mngt Top_t1 bool)
                   Top_t1
                   (Top_Logic_pred1_ho Top_t1)
                   (t2tb2 x))))))))

;; "Top_Distr_support'def"
(assert
  (forall ((qta ty))
    (forall ((d uni) (x uni))
      (=
        (Top_Distr_support qta d x)
        (< 0.0 (mu
                 qta
                 d
                 (infix_at
                   (infix_mngt qta bool)
                   qta
                   (Top_Logic_pred1_ho qta)
                   x)))))))

;; "Top_Distr_is_lossless"
(declare-fun Top_Distr_is_lossless (ty
  uni) Bool)

;; "t2tb"
(declare-fun t2tb4 ((distr Top_t)) uni)

;; "t2tb_sort"
(assert (forall ((x (distr Top_t))) (sort (distr1 Top_t1) (t2tb4 x))))

;; "tb2t"
(declare-fun tb2t4 (uni) (distr Top_t))

;; "BridgeL"
(assert
  (forall ((i (distr Top_t)))
    (! (= (tb2t4 (t2tb4 i)) i) :pattern ((t2tb4 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (distr1 Top_t1) j) (= (t2tb4 (tb2t4 j)) j)) :pattern (
    (t2tb4
      (tb2t4 j))) )))

;; "Top_Distr_is_lossless'def"
(assert
  (forall ((d (distr Top_t)))
    (=
      (Top_Distr_is_lossless Top_t1 (t2tb4 d))
      (= (mu1 d Top_Logic_predT_ho1) 1.0))))

;; "Top_Distr_is_lossless'def"
(assert
  (forall ((qta ty))
    (forall ((d uni))
      (=
        (Top_Distr_is_lossless qta d)
        (= (mu qta d (Top_Logic_predT_ho qta)) 1.0)))))

;; "Top_dt_ll"
(assert (Top_Distr_is_lossless Top_t1 (t2tb4 Top_dt)))

;; Goal "goal"
(assert
  (not
  (forall ((ethr (tuple2 (tuple3 Int Bool Top_t) memory)))
    (=>
      (and
        (< (proj3_0 (proj2_0 ethr)) Top_m)
        (= (+ Top_m (- (proj3_0 (proj2_0 ethr)))) z))
      (and
        (= (mu1 Top_dt Top_Logic_predT_ho1) 1.0)
        (forall ((v Top_t))
          (=>
            (Top_Distr_support1 Top_dt v)
            (< (+ Top_m (- (+ (proj3_0 (proj2_0 ethr)) 1))) z))))))))

(check-sat)
(get-info :reason-unknown)

