;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "bool"
(declare-fun bool () ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-datatypes ((tuple2 2))
  ((par (a a1) ((Tuple2 (proj2_0 a)(proj2_1 a1))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a3 a2) (Tuple21 a3 a2 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a3 (proj2_01 a3 a2 x)))))

;; "proj2_0'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a3 u) (= (proj2_01 a3 a2 (Tuple21 a3 a2 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a2 (proj2_11 a3 a2 x)))))

;; "proj2_1'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a2 u1) (= (proj2_11 a3 a2 (Tuple21 a3 a2 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a3 a2) u)
        (= u (Tuple21 a3 a2 (proj2_01 a3 a2 u) (proj2_11 a3 a2 u)))))))

(declare-sort Top_SKE_RND_ciphertext 0)

;; "Top_SKE_RND_ciphertext"
(declare-fun Top_SKE_RND_ciphertext1 () ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_List_list a2 qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_List_list a2 qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a2 z1)
        (= (match_Top_List_list a2 qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-sort Top_SKE_RND_CCA_CPA_UFCMA_globS 0)

;; "Top_SKE_RND_CCA_CPA_UFCMA_globS"
(declare-fun Top_SKE_RND_CCA_CPA_UFCMA_globS1 () ty)

(declare-sort Top_SKE_RND_key 0)

;; "Top_SKE_RND_key"
(declare-fun Top_SKE_RND_key1 () ty)

(declare-datatypes ((Top_Logic_option 1))
  ((par (qta) ((Top_Logic_None) (Top_Logic_Some (Top_Logic_Some_proj qta))))))

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None1 (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta1 ty)) (sort (Top_Logic_option1 qta1) (Top_Logic_None1 qta1))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some1 (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni))
      (sort (Top_Logic_option1 qta1) (Top_Logic_Some1 qta1 x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta1 ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_Logic_option a2 qta1 x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_Logic_option a2 qta1 (Top_Logic_None1 qta1) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a2 z1)
        (= (match_Top_Logic_option a2 qta1 (Top_Logic_Some1 qta1 u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty))
    (= (index_Top_Logic_option qta1 (Top_Logic_None1 qta1)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta1 (Top_Logic_Some1 qta1 u)) 1) :pattern (
      (Top_Logic_Some1
        qta1
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni)) (sort qta1 (Top_Logic_Some_proj_1 qta1 x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort qta1 u)
        (= (Top_Logic_Some_proj_1 qta1 (Top_Logic_Some1 qta1 u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta1) u)
        (or
          (= u (Top_Logic_None1 qta1))
          (= u (Top_Logic_Some1 qta1 (Top_Logic_Some_proj_1 qta1 u))))))))

(declare-sort Top_SKE_RND_plaintext 0)

;; "Top_SKE_RND_plaintext"
(declare-fun Top_SKE_RND_plaintext1 () ty)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "&m"
(declare-fun etm () memory)

;; "Top_SKE_RND_Mem_/lc"
(declare-fun Top_SKE_RND_Mem_sllc (memory) (Top_List_list Top_SKE_RND_ciphertext))

;; "Top_List_mem"
(declare-fun Top_List_mem (ty
  uni
  uni) Bool)

;; "Top_List_mem"
(declare-fun Top_List_mem1 ((Top_List_list Top_SKE_RND_ciphertext)
  Top_SKE_RND_ciphertext) Bool)

;; "t2tb"
(declare-fun t2tb ((Top_List_list Top_SKE_RND_ciphertext)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_SKE_RND_ciphertext)))
    (sort (Top_List_list1 Top_SKE_RND_ciphertext1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_List_list Top_SKE_RND_ciphertext))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_SKE_RND_ciphertext)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni)) (! (= (t2tb (tb2t j)) j) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_SKE_RND_ciphertext) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_SKE_RND_ciphertext))
    (sort Top_SKE_RND_ciphertext1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_SKE_RND_ciphertext)

;; "BridgeL"
(assert
  (forall ((i Top_SKE_RND_ciphertext))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_SKE_RND_ciphertext1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "Top_List_mem'def"
(assert
  (forall ((z Top_SKE_RND_ciphertext))
    (and
      (not (Top_List_mem1 (tb2t (Top_List_lbrb Top_SKE_RND_ciphertext1)) z))
      (forall ((x Top_SKE_RND_ciphertext) (sqt (Top_List_list Top_SKE_RND_ciphertext)))
        (=
          (Top_List_mem1
            (tb2t
              (Top_List_clcl Top_SKE_RND_ciphertext1 (t2tb1 x) (t2tb sqt)))
            z)
          (or (= z x) (Top_List_mem1 sqt z)))))))

;; "Top_List_mem'def"
(assert
  (forall ((qta1 ty))
    (forall ((z uni))
      (=>
        (sort qta1 z)
        (and
          (not (Top_List_mem qta1 (Top_List_lbrb qta1) z))
          (forall ((x uni) (sqt uni))
            (=>
              (sort qta1 x)
              (=
                (Top_List_mem qta1 (Top_List_clcl qta1 x sqt) z)
                (or (= z x) (Top_List_mem qta1 sqt z))))))))))

;; "Top_SKE_RND_CCA_CPA_UFCMA_StLSke_/gs"
(declare-fun Top_SKE_RND_CCA_CPA_UFCMA_StLSke_slgs (memory) Top_SKE_RND_CCA_CPA_UFCMA_globS)

;; "Top_SKE_RND_Mem_/k"
(declare-fun Top_SKE_RND_Mem_slk (memory) Top_SKE_RND_key)

;; "Top_SKE_RND_CCA_CPA_UFCMA_dec"
(declare-fun Top_SKE_RND_CCA_CPA_UFCMA_dec (Top_SKE_RND_CCA_CPA_UFCMA_globS
  Top_SKE_RND_key
  Top_SKE_RND_ciphertext) (Top_Logic_option Top_SKE_RND_plaintext))

;; Goal "goal"
(assert
  (not
  (forall ((et1 (tuple2 Bool memory)) (et2 (tuple2 Bool memory)))
    (=>
      (=>
        (not
          (exists ((c Top_SKE_RND_ciphertext))
            (and
              (Top_List_mem1 (Top_SKE_RND_Mem_sllc (proj2_1 et2)) c)
              (not
                (= (Top_SKE_RND_CCA_CPA_UFCMA_dec
                     (Top_SKE_RND_CCA_CPA_UFCMA_StLSke_slgs (proj2_1 et2))
                     (Top_SKE_RND_Mem_slk (proj2_1 et2))
                     c) (as Top_Logic_None (Top_Logic_option Top_SKE_RND_plaintext)))))))
        (= (= (proj2_0 et1) true) (= (proj2_0 et2) true)))
      (=>
        (not
          (exists ((c Top_SKE_RND_ciphertext))
            (and
              (Top_List_mem1 (Top_SKE_RND_Mem_sllc (proj2_1 et2)) c)
              (not
                (= (Top_SKE_RND_CCA_CPA_UFCMA_dec
                     (Top_SKE_RND_CCA_CPA_UFCMA_StLSke_slgs (proj2_1 et2))
                     (Top_SKE_RND_Mem_slk (proj2_1 et2))
                     c) (as Top_Logic_None (Top_Logic_option Top_SKE_RND_plaintext)))))))
        (=> (= (proj2_0 et1) true) (= (proj2_0 et2) true)))))))

(check-sat)

