;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "memory"
(declare-fun memory () ty)

;; "Top_Composition_sum"
(declare-fun Top_Composition_sum (ty
  ty) ty)

;; "Top_Composition_Left"
(declare-fun Top_Composition_Left (ty
  ty
  uni) uni)

;; "Top_Composition_Left_sort"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((x uni))
      (sort (Top_Composition_sum qta qtb) (Top_Composition_Left qtb qta x)))))

;; "Top_Composition_Right"
(declare-fun Top_Composition_Right (ty
  ty
  uni) uni)

;; "Top_Composition_Right_sort"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((x uni))
      (sort (Top_Composition_sum qta qtb) (Top_Composition_Right qtb qta x)))))

;; "match_Top_Composition_sum"
(declare-fun match_Top_Composition_sum (ty
  ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Composition_sum_sort"
(assert
  (forall ((qta ty) (qtb ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_Composition_sum a qtb qta x x1 x2)))))

;; "match_Top_Composition_sum_Top_Composition_Left"
(assert
  (forall ((qta ty) (qtb ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z)
        (= (match_Top_Composition_sum
             a
             qtb
             qta
             (Top_Composition_Left qtb qta u)
             z
             z1) z)))))

;; "match_Top_Composition_sum_Top_Composition_Right"
(assert
  (forall ((qta ty) (qtb ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z1)
        (= (match_Top_Composition_sum
             a
             qtb
             qta
             (Top_Composition_Right qtb qta u)
             z
             z1) z1)))))

;; "index_Top_Composition_sum"
(declare-fun index_Top_Composition_sum (ty
  ty
  uni) Int)

;; "index_Top_Composition_sum_Top_Composition_Left"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((u uni))
      (! (= (index_Top_Composition_sum
              qtb
              qta
              (Top_Composition_Left qtb qta u)) 0) :pattern ((Top_Composition_Left
                                                               qtb
                                                               qta
                                                               u)) ))))

;; "index_Top_Composition_sum_Top_Composition_Right"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((u uni))
      (! (= (index_Top_Composition_sum
              qtb
              qta
              (Top_Composition_Right qtb qta u)) 1) :pattern ((Top_Composition_Right
                                                                qtb
                                                                qta
                                                                u)) ))))

;; "Top_Composition_Left_proj_1"
(declare-fun Top_Composition_Left_proj_1 (ty
  ty
  uni) uni)

;; "Top_Composition_Left_proj_1_sort"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((x uni)) (sort qta (Top_Composition_Left_proj_1 qtb qta x)))))

;; "Top_Composition_Left_proj_1'def"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Composition_Left_proj_1
             qtb
             qta
             (Top_Composition_Left qtb qta u)) u)))))

;; "Top_Composition_Right_proj_1"
(declare-fun Top_Composition_Right_proj_1 (ty
  ty
  uni) uni)

;; "Top_Composition_Right_proj_1_sort"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((x uni)) (sort qtb (Top_Composition_Right_proj_1 qtb qta x)))))

;; "Top_Composition_Right_proj_1'def"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((u uni))
      (=>
        (sort qtb u)
        (= (Top_Composition_Right_proj_1
             qtb
             qta
             (Top_Composition_Right qtb qta u)) u)))))

;; "Top_Composition_sum_inversion"
(assert
  (forall ((qta ty) (qtb ty))
    (forall ((u uni))
      (=>
        (sort (Top_Composition_sum qta qtb) u)
        (or
          (= u (Top_Composition_Left
                 qtb
                 qta
                 (Top_Composition_Left_proj_1 qtb qta u)))
          (= u (Top_Composition_Right
                 qtb
                 qta
                 (Top_Composition_Right_proj_1 qtb qta u))))))))

(declare-datatypes ((Top_role 0))
  (((Top_I) (Top_R))))

;; "Top_role"
(declare-fun Top_role1 () ty)

;; "tuple2"
(declare-fun tuple2 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple2 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple2 a1 a) (Tuple2 a1 a x x1)))))

;; "proj2_0"
(declare-fun proj2_0 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a ty) (a1 ty)) (forall ((x uni)) (sort a1 (proj2_0 a1 a x)))))

;; "proj2_0'def"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a1 u) (= (proj2_0 a1 a (Tuple2 a1 a u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_1 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a ty) (a1 ty)) (forall ((x uni)) (sort a (proj2_1 a1 a x)))))

;; "proj2_1'def"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a u1) (= (proj2_1 a1 a (Tuple2 a1 a u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a ty) (a1 ty))
    (forall ((u uni))
      (=>
        (sort (tuple2 a1 a) u)
        (= u (Tuple2 a1 a (proj2_0 a1 a u) (proj2_1 a1 a u)))))))

;; "Top_Logic_option"
(declare-fun Top_Logic_option (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta ty)) (sort (Top_Logic_option qta) (Top_Logic_None qta))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_Logic_option qta) (Top_Logic_Some qta x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_Logic_option a qta x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_Logic_option a qta (Top_Logic_None qta) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z1)
        (= (match_Top_Logic_option a qta (Top_Logic_Some qta u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty)) (= (index_Top_Logic_option qta (Top_Logic_None qta)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta (Top_Logic_Some qta u)) 1) :pattern (
      (Top_Logic_Some
        qta
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_Logic_Some_proj_1 qta x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Logic_Some_proj_1 qta (Top_Logic_Some qta u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option qta) u)
        (or
          (= u (Top_Logic_None qta))
          (= u (Top_Logic_Some qta (Top_Logic_Some_proj_1 qta u))))))))

(declare-sort Top_party 0)

;; "Top_party"
(declare-fun Top_party1 () ty)

(declare-sort tuple3 3)

;; "tuple3"
(declare-fun tuple31 (ty
  ty
  ty) ty)

;; "Tuple3"
(declare-fun Tuple3 (ty
  ty
  ty
  uni
  uni
  uni) uni)

;; "Tuple3_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort (tuple31 a2 a1 a) (Tuple3 a2 a1 a x x1 x2)))))

;; "proj3_0"
(declare-fun proj3_0 (ty
  ty
  ty
  uni) uni)

;; "proj3_0_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a2 (proj3_0 a2 a1 a x)))))

;; "proj3_0'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a2 u) (= (proj3_0 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u)))))

;; "proj3_1"
(declare-fun proj3_1 (ty
  ty
  ty
  uni) uni)

;; "proj3_1_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a1 (proj3_1 a2 a1 a x)))))

;; "proj3_1'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a1 u1) (= (proj3_1 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u1)))))

;; "proj3_2"
(declare-fun proj3_2 (ty
  ty
  ty
  uni) uni)

;; "proj3_2_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a (proj3_2 a2 a1 a x)))))

;; "proj3_2'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a u2) (= (proj3_2 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u2)))))

;; "tuple3_inversion"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni))
      (=>
        (sort (tuple31 a2 a1 a) u)
        (= u (Tuple3
               a2
               a1
               a
               (proj3_0 a2 a1 a u)
               (proj3_1 a2 a1 a u)
               (proj3_2 a2 a1 a u)))))))

(declare-datatypes ((tuple0 0))
  (((Tuple0))))

;; "tuple0"
(declare-fun tuple01 () ty)

(declare-datatypes ((Top_DHKE_FKE_kestate 0))
  (((Top_DHKE_FKE_KE_Init)
   (Top_DHKE_FKE_KE_Blocked1 (Top_DHKE_FKE_KE_Blocked1_proj (tuple3 Top_party
   Top_party tuple0)))
   (Top_DHKE_FKE_KE_Wait (Top_DHKE_FKE_KE_Wait_proj (tuple3 Top_party
   Top_party tuple0)))
   (Top_DHKE_FKE_KE_Blocked2 (Top_DHKE_FKE_KE_Blocked2_proj (tuple3 Top_party
   Top_party tuple0)))
   (Top_DHKE_FKE_KE_Available
   (Top_DHKE_FKE_KE_Available_proj (tuple3 Top_party Top_party tuple0))))))

;; "Top_DHKE_FKE_kestate"
(declare-fun Top_DHKE_FKE_kestate1 () ty)

;; "Top_DH_G_group"
(declare-fun Top_DH_G_group () ty)

;; "tuple15"
(declare-fun tuple15 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty) ty)

;; "Tuple15"
(declare-fun Tuple15 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni) uni)

;; "Tuple15_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni) (x4 uni) (x5 uni) (x6 uni) (x7 uni) (x8 uni) (x9 uni) (x10 uni) (x11 uni) (x12 uni) (x13 uni) (x14 uni))
      (sort
        (tuple15 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a)
        (Tuple15
          a14
          a13
          a12
          a11
          a10
          a9
          a8
          a7
          a6
          a5
          a4
          a3
          a2
          a1
          a
          x
          x1
          x2
          x3
          x4
          x5
          x6
          x7
          x8
          x9
          x10
          x11
          x12
          x13
          x14)))))

;; "proj15_0"
(declare-fun proj15_0 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_0_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a14
        (proj15_0 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_0'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a14 u)
        (= (proj15_0
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u)))))

;; "proj15_1"
(declare-fun proj15_1 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_1_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a13
        (proj15_1 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_1'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a13 u1)
        (= (proj15_1
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u1)))))

;; "proj15_2"
(declare-fun proj15_2 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_2_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a12
        (proj15_2 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_2'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a12 u2)
        (= (proj15_2
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u2)))))

;; "proj15_3"
(declare-fun proj15_3 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_3_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a11
        (proj15_3 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_3'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a11 u3)
        (= (proj15_3
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u3)))))

;; "proj15_4"
(declare-fun proj15_4 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_4_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a10
        (proj15_4 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_4'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a10 u4)
        (= (proj15_4
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u4)))))

;; "proj15_5"
(declare-fun proj15_5 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_5_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort a9 (proj15_5 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_5'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a9 u5)
        (= (proj15_5
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u5)))))

;; "proj15_6"
(declare-fun proj15_6 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_6_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort a8 (proj15_6 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_6'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a8 u6)
        (= (proj15_6
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u6)))))

;; "proj15_7"
(declare-fun proj15_7 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_7_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort a7 (proj15_7 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_7'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a7 u7)
        (= (proj15_7
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u7)))))

;; "proj15_8"
(declare-fun proj15_8 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_8_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort a6 (proj15_8 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_8'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a6 u8)
        (= (proj15_8
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u8)))))

;; "proj15_9"
(declare-fun proj15_9 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_9_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort a5 (proj15_9 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_9'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a5 u9)
        (= (proj15_9
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u9)))))

;; "proj15_10"
(declare-fun proj15_10 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_10_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a4
        (proj15_10 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_10'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a4 u10)
        (= (proj15_10
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u10)))))

;; "proj15_11"
(declare-fun proj15_11 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_11_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a3
        (proj15_11 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_11'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a3 u11)
        (= (proj15_11
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u11)))))

;; "proj15_12"
(declare-fun proj15_12 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_12_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a2
        (proj15_12 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_12'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a2 u12)
        (= (proj15_12
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u12)))))

;; "proj15_13"
(declare-fun proj15_13 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_13_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort
        a1
        (proj15_13 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_13'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a1 u13)
        (= (proj15_13
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u13)))))

;; "proj15_14"
(declare-fun proj15_14 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj15_14_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((x uni))
      (sort a (proj15_14 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a x)))))

;; "proj15_14'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni))
      (=>
        (sort a u14)
        (= (proj15_14
             a14
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             a6
             a5
             a4
             a3
             a2
             a1
             a
             (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14)) u14)))))

;; "tuple15_inversion"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty) (a4 ty) (a5 ty) (a6 ty) (a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty) (a14 ty))
    (forall ((u uni))
      (=>
        (sort (tuple15 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a) u)
        (= u (Tuple15
               a14
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               a6
               a5
               a4
               a3
               a2
               a1
               a
               (proj15_0 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_1 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_2 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_3 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_4 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_5 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_6 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_7 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_8 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_9 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_10 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_11 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_12 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_13 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)
               (proj15_14 a14 a13 a12 a11 a10 a9 a8 a7 a6 a5 a4 a3 a2 a1 a u)))))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "&m"
(declare-fun etm () uni)

;; "&m_sort"
(assert (sort memory etm))

;; "m2"
(declare-fun m2 () uni)

;; "m2_sort"
(assert (sort (Top_Composition_sum tuple01 tuple01) m2))

;; "p"
(declare-fun p () uni)

;; "p_sort"
(assert (sort (Top_Composition_sum tuple01 tuple01) p))

;; "&1"
(declare-fun et1 () uni)

;; "&1_sort"
(assert
  (sort
    (tuple2
      (tuple2
        (Top_Composition_sum Top_role1 (Top_Composition_sum tuple01 tuple01))
        (Top_Composition_sum tuple01 tuple01))
      memory)
    et1))

;; "&2"
(declare-fun et2 () uni)

;; "&2_sort"
(assert
  (sort
    (tuple2
      (tuple15
        (Top_Composition_sum Top_role1 (Top_Composition_sum tuple01 tuple01))
        (Top_Logic_option Top_DHKE_FKE_kestate1)
        (Top_Logic_option
          (Top_Composition_sum Top_DH_G_group Top_DH_G_group))
        (Top_Composition_sum
          (tuple2 Top_role1 (tuple31 Top_party1 Top_party1 Top_DH_G_group))
          (tuple2 Top_role1 (tuple31 Top_party1 Top_party1 Top_DH_G_group)))
        (Top_Composition_sum tuple01 tuple01)
        (Top_Composition_sum
          (tuple2 Top_role1 (tuple31 Top_party1 Top_party1 Top_DH_G_group))
          (tuple2 Top_role1 (tuple31 Top_party1 Top_party1 Top_DH_G_group)))
        (Top_Composition_sum tuple01 tuple01)
        Top_role1
        (tuple31 Top_party1 Top_party1 Top_DH_G_group)
        Top_role1
        (tuple31 Top_party1 Top_party1 Top_DH_G_group)
        Top_role1
        (tuple31 Top_party1 Top_party1 Top_DH_G_group)
        Top_role1
        (tuple31 Top_party1 Top_party1 Top_DH_G_group))
      memory)
    et2))

;; Goal "goal"
(assert
  (not true))

(check-sat)
(get-info :reason-unknown)

