"""Tests for Pr-layer ProofIR action rendering helpers."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import _pathsetup  # noqa: F401,E402  (repo root on sys.path)

from core.easycrypt.analysis.ec_pr_actions import (  # noqa: E402
    pr_byequiv_fallback_menu_items,
    pr_clone_bound_apply_menu_items,
    pr_decomposition_bridge_menu_items,
    pr_normalization_menu_items,
    pr_rewrite_menu_items,
    visible_pr_rewrites,
)


def test_visible_pr_rewrites_filters_recent_leaf_name() -> None:
    assert visible_pr_rewrites({
        "recently_rewritten_pr_lemma": "bridge_eq",
        "pr_rewrite_candidates": ["Local.bridge_eq", "other_bridge"],
    }) == ["other_bridge"]


def test_pr_normalization_menu_items_render_congr_probe() -> None:
    items = pr_normalization_menu_items({
        "pr_normal_form": {
            "available": True,
            "normalization_kind": "common_unary_minus",
            "recommended_tactic": "congr.",
            "reason": "same arithmetic shell",
            "goal_form": "eq",
        },
    })

    assert items[0]["id"] == "pr_normalize_congr"
    assert items[0]["tactic"] == "congr."
    assert items[0]["action_type"] == "tactic_candidate"


def test_pr_decomposition_bridge_menu_items_render_direct_bridge() -> None:
    items = pr_decomposition_bridge_menu_items({
        "pr_decomposition_bridge_obligation": {
            "available": True,
            "reason": "bridge generated by latest have",
        },
    })

    assert items[0]["id"] == "pr_direct_byequiv_bridge"
    assert items[0]["tactic"] == "byequiv => //."
    assert items[0]["cost_factors"]["obligation_source"] == (
        "latest_have_decomposition"
    )


def test_pr_byequiv_fallback_menu_items_keep_probe_when_no_pr_action() -> None:
    items = pr_byequiv_fallback_menu_items(
        {"pr_byequiv_frontend": {"available": True}},
        goal_kind="Pr_eq",
        pr_rewrites=[],
        pr_bridge_obligation={},
        has_live_typed_bridge_path=False,
        has_runnable_pr_frontend=False,
    )

    assert items[0]["id"] == "pr_byequiv_fallback"
    assert items[0]["action_type"] == "tactic_candidate"
    assert items[0]["cost_factors"]["has_runnable_pr_frontend"] is False


def test_pr_rewrite_menu_items_downgrade_unresolved_bound_context() -> None:
    items = pr_rewrite_menu_items(
        {
            "pr_rewrite_candidates": ["Bridge"],
            "name_resolution": {
                "items": [{
                    "name": "Bridge",
                    "exact_signature_known": False,
                    "resolution_status": "needs_lookup",
                    "signature_lookup_action": "-where Bridge",
                }],
            },
            "native_ast_search": {
                "available": True,
                "suggested_queries": [{"query": "Pr bound"}],
            },
            "pr_path_plan": {},
        },
        goal_kind="Pr_ineq",
        pr_rewrites=["Bridge"],
    )

    assert [item["id"] for item in items] == ["rewrite_pr_handle", "sig_Bridge"]
    assert items[0]["action_type"] == "strategy_hint"
    assert items[0]["cost"] == "expensive"
    assert items[1]["cost"] == "expensive"


def test_pr_clone_bound_apply_menu_items_render_concrete_apply() -> None:
    # the kept skeleton: a concrete, probeable `apply <lemma>.` candidate (no
    # arithmetic-plan / recommended-path strategy rendering, which were deleted).
    items = pr_clone_bound_apply_menu_items({
        "pr_clone_bound_apply_candidates": [{
            "lemma": "BoundClone.bound",
            "tactic": "apply BoundClone.bound.",
        }],
    })

    assert [item["id"] for item in items] == ["pr_clone_bound_apply_0"]
    assert items[0]["tactic"] == "apply BoundClone.bound."
    assert items[0]["cost_factors"]["lemma"] == "BoundClone.bound"
