;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: real arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "Top_StdOrder_RealOrder_ler_pmul2l"
(assert
  (forall ((x Real))
    (=>
      (< 0.0 x)
      (forall ((y Real) (z Real)) (= (<= (* x y) (* x z)) (<= y z))))))

;; Goal "goal"
(assert
  (not
  (forall ((p Real) (q Real) (r Real))
    (=> (<= 0.0 r) (=> (<= p q) (<= (* r p) (* r q)))))))

(check-sat)

