;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
;;; SMT-LIB2: real arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort distr 1)

;; "distr"
(declare-fun distr1 (ty) ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-sort Top_key 0)

;; "Top_key"
(declare-fun Top_key1 () ty)

(declare-sort tuple3 3)

;; "tuple3"
(declare-fun tuple31 (ty
  ty
  ty) ty)

;; "Tuple3"
(declare-fun Tuple3 (ty
  ty
  ty
  uni
  uni
  uni) uni)

;; "Tuple3_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort (tuple31 a2 a1 a) (Tuple3 a2 a1 a x x1 x2)))))

;; "proj3_0"
(declare-fun proj3_0 (ty
  ty
  ty
  uni) uni)

;; "proj3_0_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a2 (proj3_0 a2 a1 a x)))))

;; "proj3_0'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a2 u) (= (proj3_0 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u)))))

;; "proj3_1"
(declare-fun proj3_1 (ty
  ty
  ty
  uni) uni)

;; "proj3_1_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a1 (proj3_1 a2 a1 a x)))))

;; "proj3_1'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a1 u1) (= (proj3_1 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u1)))))

;; "proj3_2"
(declare-fun proj3_2 (ty
  ty
  ty
  uni) uni)

;; "proj3_2_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a (proj3_2 a2 a1 a x)))))

;; "proj3_2'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a u2) (= (proj3_2 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u2)))))

;; "tuple3_inversion"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni))
      (=>
        (sort (tuple31 a2 a1 a) u)
        (= u (Tuple3
               a2
               a1
               a
               (proj3_0 a2 a1 a u)
               (proj3_1 a2 a1 a u)
               (proj3_2 a2 a1 a u)))))))

(declare-sort Top_exp 0)

;; "Top_exp"
(declare-fun Top_exp1 () ty)

(declare-sort tuple4 4)

;; "tuple4"
(declare-fun tuple41 (ty
  ty
  ty
  ty) ty)

;; "Tuple4"
(declare-fun Tuple4 (ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni) uni)

;; "Tuple4_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni))
      (sort (tuple41 a3 a2 a1 a) (Tuple4 a3 a2 a1 a x x1 x2 x3)))))

;; "proj4_0"
(declare-fun proj4_0 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_0_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a3 (proj4_0 a3 a2 a1 a x)))))

;; "proj4_0'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a3 u)
        (= (proj4_0 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u)))))

;; "proj4_1"
(declare-fun proj4_1 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_1_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a2 (proj4_1 a3 a2 a1 a x)))))

;; "proj4_1'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a2 u1)
        (= (proj4_1 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u1)))))

;; "proj4_2"
(declare-fun proj4_2 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_2_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a1 (proj4_2 a3 a2 a1 a x)))))

;; "proj4_2'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a1 u2)
        (= (proj4_2 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u2)))))

;; "proj4_3"
(declare-fun proj4_3 (ty
  ty
  ty
  ty
  uni) uni)

;; "proj4_3_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((x uni)) (sort a (proj4_3 a3 a2 a1 a x)))))

;; "proj4_3'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni))
      (=>
        (sort a u3)
        (= (proj4_3 a3 a2 a1 a (Tuple4 a3 a2 a1 a u u1 u2 u3)) u3)))))

;; "tuple4_inversion"
(assert
  (forall ((a ty) (a1 ty) (a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple41 a3 a2 a1 a) u)
        (= u (Tuple4
               a3
               a2
               a1
               a
               (proj4_0 a3 a2 a1 a u)
               (proj4_1 a3 a2 a1 a u)
               (proj4_2 a3 a2 a1 a u)
               (proj4_3 a3 a2 a1 a u)))))))

(declare-datatypes ((tuple2 2))
  ((par (a a1) ((Tuple2 (proj2_0 a)(proj2_1 a1))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a3 a2) (Tuple21 a3 a2 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a3 (proj2_01 a3 a2 x)))))

;; "proj2_0'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a3 u) (= (proj2_01 a3 a2 (Tuple21 a3 a2 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a2 (proj2_11 a3 a2 x)))))

;; "proj2_1'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a2 u1) (= (proj2_11 a3 a2 (Tuple21 a3 a2 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a3 a2) u)
        (= u (Tuple21 a3 a2 (proj2_01 a3 a2 u) (proj2_11 a3 a2 u)))))))

(declare-sort Top_FMap_fmap 2)

;; "Top_FMap_fmap"
(declare-fun Top_FMap_fmap1 (ty
  ty) ty)

(declare-datatypes ((Top_ro_in_t 0))
  (((Top_A) (Top_B) (Top_C))))

;; "Top_ro_in_t"
(declare-fun Top_ro_in_t1 () ty)

(declare-datatypes ((Top_Logic_option 1))
  ((par (qta) ((Top_Logic_None) (Top_Logic_Some (Top_Logic_Some_proj qta))))))

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None1 (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta1 ty)) (sort (Top_Logic_option1 qta1) (Top_Logic_None1 qta1))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some1 (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni))
      (sort (Top_Logic_option1 qta1) (Top_Logic_Some1 qta1 x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta1 ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_Logic_option a2 qta1 x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_Logic_option a2 qta1 (Top_Logic_None1 qta1) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a2 z1)
        (= (match_Top_Logic_option a2 qta1 (Top_Logic_Some1 qta1 u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty))
    (= (index_Top_Logic_option qta1 (Top_Logic_None1 qta1)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta1 (Top_Logic_Some1 qta1 u)) 1) :pattern (
      (Top_Logic_Some1
        qta1
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni)) (sort qta1 (Top_Logic_Some_proj_1 qta1 x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort qta1 u)
        (= (Top_Logic_Some_proj_1 qta1 (Top_Logic_Some1 qta1 u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta1) u)
        (or
          (= u (Top_Logic_None1 qta1))
          (= u (Top_Logic_Some1 qta1 (Top_Logic_Some_proj_1 qta1 u))))))))

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a2 ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a2 x x1)))))

;; "mu"
(declare-fun mu (ty
  uni
  uni) Real)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "i'"
(declare-fun iqt () Int)

;; "ge1_i'"
(assert (<= 1 iqt))

;; "Top_m"
(declare-fun Top_m () Int)

;; "le_i'_m"
(assert (<= iqt Top_m))

;; "Top_Hybrid_Or_/ctr"
(declare-fun Top_Hybrid_Or_slctr (memory) Int)

;; "Top_RO_Disting2_Or_/ctr"
(declare-fun Top_RO_Disting2_Or_slctr (memory) Int)

;; "Top_Hybrid_/i"
(declare-fun Top_Hybrid_sli (memory) Int)

;; "Top_RO_Disting2_/i"
(declare-fun Top_RO_Disting2_sli (memory) Int)

;; "Top_FullRO_RO_/m"
(declare-fun Top_FullRO_RO_slm (memory) (Top_FMap_fmap Top_ro_in_t
  Top_exp))

;; "const"
(declare-fun const1 (ty
  ty
  uni) uni)

;; "const_sort"
(assert
  (forall ((a2 ty) (b ty))
    (forall ((x uni)) (sort (infix_mngt a2 b) (const1 b a2 x)))))

;; "const"
(declare-fun const2 ((Top_Logic_option Top_exp)) (Array Top_ro_in_t (Top_Logic_option Top_exp)))

;; "const'def"
(assert
  (forall ((v (Top_Logic_option Top_exp)))
    (forall ((us Top_ro_in_t)) (= (select (const2 v) us) v))))

;; "const'def"
(assert
  (forall ((a2 ty) (b ty))
    (forall ((v uni))
      (=>
        (sort b v)
        (forall ((us uni)) (= (infix_at b a2 (const1 b a2 v) us) v))))))

;; "Top_FMap_ofmap"
(declare-fun Top_FMap_ofmap (ty
  ty
  uni) uni)

;; "Top_FMap_ofmap_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni))
      (sort (Top_FMap_fmap1 qta1 qtb) (Top_FMap_ofmap qtb qta1 x)))))

;; "Top_FMap_ofmap"
(declare-fun Top_FMap_ofmap1 ((Array Top_ro_in_t (Top_Logic_option Top_exp))) (Top_FMap_fmap Top_ro_in_t
  Top_exp))

;; "Top_dexp"
(declare-fun Top_dexp () (distr Top_exp))

;; "Top_Logic_pred1_ho"
(declare-fun Top_Logic_pred1_ho (ty) uni)

;; "Top_Logic_pred1_ho_sort"
(assert
  (forall ((qta1 ty))
    (sort (infix_mngt qta1 (infix_mngt qta1 bool)) (Top_Logic_pred1_ho qta1))))

;; "t2tb"
(declare-fun t2tb (Bool) uni)

;; "t2tb_sort"
(assert (forall ((x Bool)) (sort bool (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) Bool)

;; "BridgeL"
(assert (forall ((i Bool)) (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort bool j) (= (t2tb (tb2t j)) j)) :pattern ((t2tb (tb2t j))) )))

;; "Top_Logic_pred1_ho_spec"
(assert
  (forall ((qta1 ty))
    (forall ((x uni) (x1 uni))
      (=>
        (sort qta1 x)
        (=>
          (sort qta1 x1)
          (=
            (= (tb2t
                 (infix_at
                   bool
                   qta1
                   (infix_at
                     (infix_mngt qta1 bool)
                     qta1
                     (Top_Logic_pred1_ho qta1)
                     x)
                   x1)) true)
            (= x1 x)))))))

;; "Top_Distr_support"
(declare-fun Top_Distr_support (ty
  uni
  uni) Bool)

;; "Top_Distr_support"
(declare-fun Top_Distr_support1 ((distr Top_exp)
  Top_exp) Bool)

;; "t2tb"
(declare-fun t2tb1 ((distr Top_exp)) uni)

;; "t2tb_sort"
(assert (forall ((x (distr Top_exp))) (sort (distr1 Top_exp1) (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) (distr Top_exp))

;; "BridgeL"
(assert
  (forall ((i (distr Top_exp)))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (distr1 Top_exp1) j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "t2tb"
(declare-fun t2tb2 ((Array Top_exp Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_exp Bool)))
    (sort (infix_mngt Top_exp1 bool) (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Array Top_exp Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Top_exp Bool)))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (infix_mngt Top_exp1 bool) j) (= (t2tb2 (tb2t2 j)) j)) :pattern (
    (t2tb2
      (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 (Top_exp) uni)

;; "t2tb_sort"
(assert (forall ((x Top_exp)) (sort Top_exp1 (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) Top_exp)

;; "BridgeL"
(assert
  (forall ((i Top_exp)) (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_exp1 j) (= (t2tb3 (tb2t3 j)) j)) :pattern ((t2tb3
                                                                  (tb2t3 j))) )))

;; "t2tb"
(declare-fun t2tb4 ((Array Top_exp (Array Top_exp Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_exp (Array Top_exp Bool))))
    (sort (infix_mngt Top_exp1 (infix_mngt Top_exp1 bool)) (t2tb4 x))))

;; "tb2t"
(declare-fun tb2t4 (uni) (Array Top_exp (Array Top_exp Bool)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_exp (Array Top_exp Bool))))
    (! (= (tb2t4 (t2tb4 i)) i) :pattern ((t2tb4 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_exp1 (infix_mngt Top_exp1 bool)) j)
         (= (t2tb4 (tb2t4 j)) j)) :pattern ((t2tb4 (tb2t4 j))) )))

;; "Top_Distr_support'def"
(assert
  (forall ((d (distr Top_exp)) (x Top_exp))
    (=
      (Top_Distr_support1 d x)
      (< 0.0 (mu
               Top_exp1
               (t2tb1 d)
               (infix_at
                 (infix_mngt Top_exp1 bool)
                 Top_exp1
                 (Top_Logic_pred1_ho Top_exp1)
                 (t2tb3 x)))))))

;; "Top_Distr_support'def"
(assert
  (forall ((qta1 ty))
    (forall ((d uni) (x uni))
      (=
        (Top_Distr_support qta1 d x)
        (< 0.0 (mu
                 qta1
                 d
                 (infix_at
                   (infix_mngt qta1 bool)
                   qta1
                   (Top_Logic_pred1_ho qta1)
                   x)))))))

;; Goal "goal"
(assert
  (not
  (forall ((et1 (tuple2 (tuple4 (tuple3 Top_key Top_key Top_key) Top_exp Top_exp Top_exp) memory)) (et2 (tuple2 (tuple4 (tuple3 Top_key Top_key Top_key) Top_exp Top_exp Top_exp) memory)))
    (=>
      (and
        (and
          (and
            (and
              (= (Top_Hybrid_Or_slctr (proj2_1 et1)) (Top_RO_Disting2_Or_slctr
                                                       (proj2_1 et2)))
              (and
                (and
                  (<= 1 (Top_Hybrid_Or_slctr (proj2_1 et1)))
                  (<= (Top_Hybrid_Or_slctr (proj2_1 et1)) (+ Top_m 1)))
                (and
                  (= (Top_Hybrid_sli (proj2_1 et1)) iqt)
                  (and
                    (= (Top_RO_Disting2_sli (proj2_1 et2)) iqt)
                    (=>
                      (<= (Top_Hybrid_Or_slctr (proj2_1 et1)) iqt)
                      (= (Top_FullRO_RO_slm (proj2_1 et2)) (Top_FMap_ofmap1
                                                             (const2
                                                               (as Top_Logic_None (Top_Logic_option Top_exp))))))))))
            (<= (Top_Hybrid_Or_slctr (proj2_1 et1)) Top_m))
          (not
            (< (Top_Hybrid_Or_slctr (proj2_1 et1)) (Top_Hybrid_sli
                                                     (proj2_1 et1)))))
        (not
          (= (Top_Hybrid_Or_slctr (proj2_1 et1)) (Top_Hybrid_sli
                                                   (proj2_1 et1)))))
      (forall ((xL Top_exp))
        (=>
          (Top_Distr_support1 Top_dexp xL)
          (forall ((yL Top_exp))
            (=>
              (Top_Distr_support1 Top_dexp yL)
              (and
                (= (+ (Top_Hybrid_Or_slctr (proj2_1 et1)) 1) (+ (Top_RO_Disting2_Or_slctr
                                                                  (proj2_1
                                                                    et2)) 1))
                (and
                  (and
                    (<= 1 (+ (Top_Hybrid_Or_slctr (proj2_1 et1)) 1))
                    (<= (+ (Top_Hybrid_Or_slctr (proj2_1 et1)) 1) (+ 
                    Top_m 1)))
                  (and
                    (= (Top_Hybrid_sli (proj2_1 et1)) iqt)
                    (and
                      (= (Top_RO_Disting2_sli (proj2_1 et2)) iqt)
                      (=>
                        (<= (+ (Top_Hybrid_Or_slctr (proj2_1 et1)) 1) 
                        iqt)
                        (= (Top_FullRO_RO_slm (proj2_1 et2)) (Top_FMap_ofmap1
                                                               (const2
                                                                 (as Top_Logic_None (Top_Logic_option Top_exp))))))))))))))))))

(check-sat)

