;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-datatypes ((tuple2 2))
  ((par (a a1) ((Tuple2 (proj2_0 a)(proj2_1 a1))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a3 a2) (Tuple21 a3 a2 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a3 (proj2_01 a3 a2 x)))))

;; "proj2_0'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a3 u) (= (proj2_01 a3 a2 (Tuple21 a3 a2 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a2 (proj2_11 a3 a2 x)))))

;; "proj2_1'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a2 u1) (= (proj2_11 a3 a2 (Tuple21 a3 a2 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a3 a2) u)
        (= u (Tuple21 a3 a2 (proj2_01 a3 a2 u) (proj2_11 a3 a2 u)))))))

(declare-sort Adv 0)

;; "Adv"
(declare-fun Adv1 () ty)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "i'"
(declare-fun iqt () Int)

;; "ge1_i'"
(assert (<= 1 iqt))

;; "Top_m"
(declare-fun Top_m () Int)

;; "le_i'_m"
(assert (<= iqt Top_m))

;; "Adv"
(declare-fun Adv2 (memory) Adv)

;; "Top_RO_Disting2_/i"
(declare-fun Top_RO_Disting2_sli (memory) Int)

;; "Top_RO_Disting2_Or_/ctr"
(declare-fun Top_RO_Disting2_Or_slctr (memory) Int)

(declare-datatypes ((tuple0 0))
  (((Tuple0))))

;; "tuple0"
(declare-fun tuple01 () ty)

;; Goal "goal"
(assert
  (not
  (forall ((et1 (tuple2 (tuple2 tuple0 Int) memory)) (et2 (tuple2 Int memory)))
    (=>
      (and
        (= (Adv2 (proj2_1 et1)) (Adv2 (proj2_1 et2)))
        (and (= (proj2_1 (proj2_0 et1)) iqt) (= (proj2_0 et2) iqt)))
      (exists ((Adv3 Adv) (i Int) (ctr Int) (arg Int))
        (and
          (and
            (= (Adv2 (proj2_1 et1)) Adv3)
            (and (= (proj2_1 (proj2_0 et1)) iqt) (= arg iqt)))
          (and
            (and
              (= Adv3 (Adv2 (proj2_1 et2)))
              (and
                (= i (Top_RO_Disting2_sli (proj2_1 et2)))
                (= ctr (Top_RO_Disting2_Or_slctr (proj2_1 et2)))))
            (= arg (proj2_0 et2)))))))))

(check-sat)
(get-info :reason-unknown)

