;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-sort Top_key 0)

;; "Top_key"
(declare-fun Top_key1 () ty)

(declare-sort tuple3 3)

;; "tuple3"
(declare-fun tuple31 (ty
  ty
  ty) ty)

;; "Tuple3"
(declare-fun Tuple3 (ty
  ty
  ty
  uni
  uni
  uni) uni)

;; "Tuple3_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort (tuple31 a2 a1 a) (Tuple3 a2 a1 a x x1 x2)))))

;; "proj3_0"
(declare-fun proj3_0 (ty
  ty
  ty
  uni) uni)

;; "proj3_0_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a2 (proj3_0 a2 a1 a x)))))

;; "proj3_0'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a2 u) (= (proj3_0 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u)))))

;; "proj3_1"
(declare-fun proj3_1 (ty
  ty
  ty
  uni) uni)

;; "proj3_1_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a1 (proj3_1 a2 a1 a x)))))

;; "proj3_1'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a1 u1) (= (proj3_1 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u1)))))

;; "proj3_2"
(declare-fun proj3_2 (ty
  ty
  ty
  uni) uni)

;; "proj3_2_sort"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((x uni)) (sort a (proj3_2 a2 a1 a x)))))

;; "proj3_2'def"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni) (u1 uni) (u2 uni))
      (=> (sort a u2) (= (proj3_2 a2 a1 a (Tuple3 a2 a1 a u u1 u2)) u2)))))

;; "tuple3_inversion"
(assert
  (forall ((a ty) (a1 ty) (a2 ty))
    (forall ((u uni))
      (=>
        (sort (tuple31 a2 a1 a) u)
        (= u (Tuple3
               a2
               a1
               a
               (proj3_0 a2 a1 a u)
               (proj3_1 a2 a1 a u)
               (proj3_2 a2 a1 a u)))))))

(declare-sort Top_exp 0)

;; "Top_exp"
(declare-fun Top_exp1 () ty)

(declare-datatypes ((tuple7 7))
  ((par (a a1 a2 a3 a4 a5
   a6) ((Tuple7
        (proj7_0 a)(proj7_1 a1)(proj7_2 a2)(proj7_3 a3)(proj7_4 a4)(proj7_5 a5)(proj7_6 a6))))))

;; "tuple7"
(declare-fun tuple71 (ty
  ty
  ty
  ty
  ty
  ty
  ty) ty)

;; "Tuple7"
(declare-fun Tuple71 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni
  uni
  uni
  uni) uni)

;; "Tuple7_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni) (x4 uni) (x5 uni) (x6 uni))
      (sort
        (tuple71 a13 a12 a11 a10 a9 a8 a7)
        (Tuple71 a13 a12 a11 a10 a9 a8 a7 x x1 x2 x3 x4 x5 x6)))))

;; "proj7_0"
(declare-fun proj7_01 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_0_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a13 (proj7_01 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_0'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a13 u)
        (= (proj7_01
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u)))))

;; "proj7_1"
(declare-fun proj7_11 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_1_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a12 (proj7_11 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_1'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a12 u1)
        (= (proj7_11
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u1)))))

;; "proj7_2"
(declare-fun proj7_21 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_2_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a11 (proj7_21 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_2'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a11 u2)
        (= (proj7_21
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u2)))))

;; "proj7_3"
(declare-fun proj7_31 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_3_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a10 (proj7_31 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_3'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a10 u3)
        (= (proj7_31
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u3)))))

;; "proj7_4"
(declare-fun proj7_41 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_4_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a9 (proj7_41 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_4'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a9 u4)
        (= (proj7_41
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u4)))))

;; "proj7_5"
(declare-fun proj7_51 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_5_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a8 (proj7_51 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_5'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a8 u5)
        (= (proj7_51
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u5)))))

;; "proj7_6"
(declare-fun proj7_61 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj7_6_sort"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((x uni)) (sort a7 (proj7_61 a13 a12 a11 a10 a9 a8 a7 x)))))

;; "proj7_6'def"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni))
      (=>
        (sort a7 u6)
        (= (proj7_61
             a13
             a12
             a11
             a10
             a9
             a8
             a7
             (Tuple71 a13 a12 a11 a10 a9 a8 a7 u u1 u2 u3 u4 u5 u6)) u6)))))

;; "tuple7_inversion"
(assert
  (forall ((a7 ty) (a8 ty) (a9 ty) (a10 ty) (a11 ty) (a12 ty) (a13 ty))
    (forall ((u uni))
      (=>
        (sort (tuple71 a13 a12 a11 a10 a9 a8 a7) u)
        (= u (Tuple71
               a13
               a12
               a11
               a10
               a9
               a8
               a7
               (proj7_01 a13 a12 a11 a10 a9 a8 a7 u)
               (proj7_11 a13 a12 a11 a10 a9 a8 a7 u)
               (proj7_21 a13 a12 a11 a10 a9 a8 a7 u)
               (proj7_31 a13 a12 a11 a10 a9 a8 a7 u)
               (proj7_41 a13 a12 a11 a10 a9 a8 a7 u)
               (proj7_51 a13 a12 a11 a10 a9 a8 a7 u)
               (proj7_61 a13 a12 a11 a10 a9 a8 a7 u)))))))

(declare-datatypes ((tuple2 2))
  ((par (a7 a8) ((Tuple2 (proj2_0 a7)(proj2_1 a8))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a9 ty) (a10 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a10 a9) (Tuple21 a10 a9 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a9 ty) (a10 ty))
    (forall ((x uni)) (sort a10 (proj2_01 a10 a9 x)))))

;; "proj2_0'def"
(assert
  (forall ((a9 ty) (a10 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a10 u) (= (proj2_01 a10 a9 (Tuple21 a10 a9 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a9 ty) (a10 ty))
    (forall ((x uni)) (sort a9 (proj2_11 a10 a9 x)))))

;; "proj2_1'def"
(assert
  (forall ((a9 ty) (a10 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a9 u1) (= (proj2_11 a10 a9 (Tuple21 a10 a9 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a9 ty) (a10 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a10 a9) u)
        (= u (Tuple21 a10 a9 (proj2_01 a10 a9 u) (proj2_11 a10 a9 u)))))))

(declare-datatypes ((Top_ro_in_t 0))
  (((Top_A) (Top_B) (Top_C))))

;; "Top_ro_in_t"
(declare-fun Top_ro_in_t1 () ty)

(declare-datatypes ((tuple10 10))
  ((par (a9 a10 a11 a12 a13 a14 a15 a16 a17
   a18) ((Tuple10
         (proj10_0 a9)(proj10_1 a10)(proj10_2 a11)(proj10_3 a12)(proj10_4 a13)(proj10_5 a14)(proj10_6 a15)(proj10_7 a16)(proj10_8 a17)(proj10_9 a18))))))

;; "tuple10"
(declare-fun tuple101 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty) ty)

;; "Tuple10"
(declare-fun Tuple101 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni) uni)

;; "Tuple10_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni) (x4 uni) (x5 uni) (x6 uni) (x7 uni) (x8 uni) (x9 uni))
      (sort
        (tuple101 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19)
        (Tuple101
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          a20
          a19
          x
          x1
          x2
          x3
          x4
          x5
          x6
          x7
          x8
          x9)))))

;; "proj10_0"
(declare-fun proj10_01 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_0_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a28 (proj10_01 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_0'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a28 u)
        (= (proj10_01
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u)))))

;; "proj10_1"
(declare-fun proj10_11 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_1_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a27 (proj10_11 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_1'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a27 u1)
        (= (proj10_11
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u1)))))

;; "proj10_2"
(declare-fun proj10_21 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_2_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a26 (proj10_21 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_2'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a26 u2)
        (= (proj10_21
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u2)))))

;; "proj10_3"
(declare-fun proj10_31 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_3_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a25 (proj10_31 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_3'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a25 u3)
        (= (proj10_31
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u3)))))

;; "proj10_4"
(declare-fun proj10_41 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_4_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a24 (proj10_41 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_4'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a24 u4)
        (= (proj10_41
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u4)))))

;; "proj10_5"
(declare-fun proj10_51 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_5_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a23 (proj10_51 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_5'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a23 u5)
        (= (proj10_51
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u5)))))

;; "proj10_6"
(declare-fun proj10_61 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_6_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a22 (proj10_61 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_6'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a22 u6)
        (= (proj10_61
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u6)))))

;; "proj10_7"
(declare-fun proj10_71 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_7_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a21 (proj10_71 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_7'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a21 u7)
        (= (proj10_71
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u7)))))

;; "proj10_8"
(declare-fun proj10_81 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_8_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a20 (proj10_81 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_8'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a20 u8)
        (= (proj10_81
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u8)))))

;; "proj10_9"
(declare-fun proj10_91 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj10_9_sort"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((x uni))
      (sort a19 (proj10_91 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 x)))))

;; "proj10_9'def"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni))
      (=>
        (sort a19 u9)
        (= (proj10_91
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             a20
             a19
             (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9)) u9)))))

;; "tuple10_inversion"
(assert
  (forall ((a19 ty) (a20 ty) (a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty))
    (forall ((u uni))
      (=>
        (sort (tuple101 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19) u)
        (= u (Tuple101
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               a20
               a19
               (proj10_01 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_11 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_21 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_31 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_41 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_51 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_61 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_71 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_81 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)
               (proj10_91 a28 a27 a26 a25 a24 a23 a22 a21 a20 a19 u)))))))

(declare-sort Top_FMap_fmap 2)

;; "Top_FMap_fmap"
(declare-fun Top_FMap_fmap1 (ty
  ty) ty)

(declare-datatypes ((Top_Logic_option 1))
  ((par (qta) ((Top_Logic_None) (Top_Logic_Some (Top_Logic_Some_proj qta))))))

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None1 (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta1 ty)) (sort (Top_Logic_option1 qta1) (Top_Logic_None1 qta1))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some1 (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni))
      (sort (Top_Logic_option1 qta1) (Top_Logic_Some1 qta1 x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta1 ty) (a19 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a19 (match_Top_Logic_option a19 qta1 x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty) (a19 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a19 z)
        (= (match_Top_Logic_option a19 qta1 (Top_Logic_None1 qta1) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty) (a19 ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a19 z1)
        (= (match_Top_Logic_option a19 qta1 (Top_Logic_Some1 qta1 u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta1 ty))
    (= (index_Top_Logic_option qta1 (Top_Logic_None1 qta1)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta1 (Top_Logic_Some1 qta1 u)) 1) :pattern (
      (Top_Logic_Some1
        qta1
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni)) (sort qta1 (Top_Logic_Some_proj_1 qta1 x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort qta1 u)
        (= (Top_Logic_Some_proj_1 qta1 (Top_Logic_Some1 qta1 u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta1 ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta1) u)
        (or
          (= u (Top_Logic_None1 qta1))
          (= u (Top_Logic_Some1 qta1 (Top_Logic_Some_proj_1 qta1 u))))))))

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a19 ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a19 x x1)))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "witness"
(declare-fun witness2 () Top_exp)

;; "set"
(declare-fun set (ty
  ty
  uni
  uni
  uni) uni)

;; "set_sort"
(assert
  (forall ((a19 ty) (b ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort (infix_mngt a19 b) (set b a19 x x1 x2)))))

;; "i'"
(declare-fun iqt () Int)

;; "ge1_i'"
(assert (<= 1 iqt))

;; "Top_m"
(declare-fun Top_m () Int)

;; "le_i'_m"
(assert (<= iqt Top_m))

;; "&m"
(declare-fun etm () (tuple2 (tuple7 (tuple3 Top_key
  Top_key
  Top_key)
  Top_exp
  Top_exp
  Top_exp
  Top_exp
  Top_exp
  Top_exp)
  memory))

;; "Top_FullRO_RO_/m"
(declare-fun Top_FullRO_RO_slm (memory) (Top_FMap_fmap Top_ro_in_t
  Top_exp))

;; "Top_FMap_tomap"
(declare-fun Top_FMap_tomap (ty
  ty
  uni) uni)

;; "Top_FMap_tomap_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni))
      (sort
        (infix_mngt qta1 (Top_Logic_option1 qtb))
        (Top_FMap_tomap qtb qta1 x)))))

;; "Top_FMap_ofmap"
(declare-fun Top_FMap_ofmap (ty
  ty
  uni) uni)

;; "Top_FMap_ofmap_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni))
      (sort (Top_FMap_fmap1 qta1 qtb) (Top_FMap_ofmap qtb qta1 x)))))

;; "Top_FMap_ofmap"
(declare-fun Top_FMap_ofmap1 ((Array Top_ro_in_t (Top_Logic_option Top_exp))) (Top_FMap_fmap Top_ro_in_t
  Top_exp))

;; "Top_FMap___[_<-_]"
(declare-fun Top_FMap___lb_lsmn_rb (ty
  ty
  uni
  uni
  uni) uni)

;; "Top_FMap___[_<-_]_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort
        (Top_FMap_fmap1 qta1 qtb)
        (Top_FMap___lb_lsmn_rb qtb qta1 x x1 x2)))))

;; "Top_FMap___[_<-_]"
(declare-fun Top_FMap___lb_lsmn_rb1 ((Top_FMap_fmap Top_ro_in_t
  Top_exp)
  Top_ro_in_t
  Top_exp) (Top_FMap_fmap Top_ro_in_t
  Top_exp))

;; "t2tb"
(declare-fun t2tb ((Top_Logic_option Top_exp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_exp)))
    (sort (Top_Logic_option1 Top_exp1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_Logic_option Top_exp))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_exp)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (Top_Logic_option1 Top_exp1) j) (= (t2tb (tb2t j)) j)) :pattern (
    (t2tb
      (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_exp) uni)

;; "t2tb_sort"
(assert (forall ((x Top_exp)) (sort Top_exp1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_exp)

;; "BridgeL"
(assert
  (forall ((i Top_exp)) (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_exp1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern ((t2tb1
                                                                  (tb2t1 j))) )))

;; "Top_FMap___[_<-_]'def"
(assert
  (forall ((qta1 ty))
    (forall ((m uni) (x uni) (v Top_exp))
      (= (Top_FMap___lb_lsmn_rb Top_exp1 qta1 m x (t2tb1 v)) (Top_FMap_ofmap
                                                               Top_exp1
                                                               qta1
                                                               (set
                                                                 (Top_Logic_option1
                                                                   Top_exp1)
                                                                 qta1
                                                                 (Top_FMap_tomap
                                                                   Top_exp1
                                                                   qta1
                                                                   m)
                                                                 x
                                                                 (t2tb
                                                                   (Top_Logic_Some
                                                                    v))))))))

;; "t2tb"
(declare-fun t2tb2 ((Array Top_ro_in_t (Top_Logic_option Top_exp))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_ro_in_t (Top_Logic_option Top_exp))))
    (sort (infix_mngt Top_ro_in_t1 (Top_Logic_option1 Top_exp1)) (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Array Top_ro_in_t (Top_Logic_option Top_exp)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_ro_in_t (Top_Logic_option Top_exp))))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_ro_in_t1 (Top_Logic_option1 Top_exp1)) j)
         (= (t2tb2 (tb2t2 j)) j)) :pattern ((t2tb2 (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 ((Top_FMap_fmap Top_ro_in_t
  Top_exp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_FMap_fmap Top_ro_in_t Top_exp)))
    (sort (Top_FMap_fmap1 Top_ro_in_t1 Top_exp1) (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) (Top_FMap_fmap Top_ro_in_t
  Top_exp))

;; "BridgeL"
(assert
  (forall ((i (Top_FMap_fmap Top_ro_in_t Top_exp)))
    (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_FMap_fmap1 Top_ro_in_t1 Top_exp1) j)
         (= (t2tb3 (tb2t3 j)) j)) :pattern ((t2tb3 (tb2t3 j))) )))

;; "Top_FMap___[_<-_]'def"
(assert
  (forall ((m (Top_FMap_fmap Top_ro_in_t Top_exp)) (x Top_ro_in_t) (v Top_exp))
    (= (Top_FMap___lb_lsmn_rb1 m x v) (Top_FMap_ofmap1
                                        (store (tb2t2
                                                 (Top_FMap_tomap
                                                   Top_exp1
                                                   Top_ro_in_t1
                                                   (t2tb3 m))) x (Top_Logic_Some
                                                                   v))))))

;; "Top_FMap___[_<-_]'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((m uni) (x uni) (v uni))
      (= (Top_FMap___lb_lsmn_rb qtb qta1 m x v) (Top_FMap_ofmap
                                                  qtb
                                                  qta1
                                                  (set
                                                    (Top_Logic_option1 qtb)
                                                    qta1
                                                    (Top_FMap_tomap
                                                      qtb
                                                      qta1
                                                      m)
                                                    x
                                                    (Top_Logic_Some1 qtb v)))))))

;; "Top_FMap___[_]"
(declare-fun Top_FMap___lb_rb (ty
  ty
  uni
  uni) uni)

;; "Top_FMap___[_]_sort"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_Logic_option1 qtb) (Top_FMap___lb_rb qtb qta1 x x1)))))

;; "Top_FMap___[_]"
(declare-fun Top_FMap___lb_rb1 ((Top_FMap_fmap Top_ro_in_t
  Top_exp)
  Top_ro_in_t) (Top_Logic_option Top_exp))

;; "Top_FMap___[_]'def"
(assert
  (forall ((m (Top_FMap_fmap Top_ro_in_t Top_exp)) (x Top_ro_in_t))
    (= (Top_FMap___lb_rb1 m x) (select (tb2t2
                                         (Top_FMap_tomap
                                           Top_exp1
                                           Top_ro_in_t1
                                           (t2tb3 m))) x))))

;; "Top_FMap___[_]'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((m uni) (x uni))
      (= (Top_FMap___lb_rb qtb qta1 m x) (infix_at
                                           (Top_Logic_option1 qtb)
                                           qta1
                                           (Top_FMap_tomap qtb qta1 m)
                                           x)))))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt (ty
  uni
  uni) uni)

;; "Top_Logic_odflt_sort"
(assert
  (forall ((qta1 ty))
    (forall ((x uni) (x1 uni)) (sort qta1 (Top_Logic_odflt qta1 x x1)))))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt1 (Top_exp
  (Top_Logic_option Top_exp)) Top_exp)

;; "Top_Logic_odflt'def"
(assert
  (forall ((d Top_exp) (ox (Top_Logic_option Top_exp)))
    (match ox ((Top_Logic_None (= (Top_Logic_odflt1 d ox) d))
               ((Top_Logic_Some x) (= (Top_Logic_odflt1 d ox) x))))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((qta1 ty))
    (forall ((d uni))
      (=>
        (sort qta1 d)
        (and
          (= (Top_Logic_odflt qta1 d (Top_Logic_None1 qta1)) d)
          (forall ((x1 uni))
            (=>
              (sort qta1 x1)
              (= (Top_Logic_odflt qta1 d (Top_Logic_Some1 qta1 x1)) x1))))))))

;; "Top_Hybrid_Or_/ctr"
(declare-fun Top_Hybrid_Or_slctr (memory) Int)

;; "Top_RO_Disting2_Or_/ctr"
(declare-fun Top_RO_Disting2_Or_slctr (memory) Int)

;; "Top_Hybrid_/i"
(declare-fun Top_Hybrid_sli (memory) Int)

;; "Top_RO_Disting2_/i"
(declare-fun Top_RO_Disting2_sli (memory) Int)

;; "const"
(declare-fun const1 (ty
  ty
  uni) uni)

;; "const_sort"
(assert
  (forall ((a19 ty) (b ty))
    (forall ((x1 uni)) (sort (infix_mngt a19 b) (const1 b a19 x1)))))

;; "const"
(declare-fun const2 ((Top_Logic_option Top_exp)) (Array Top_ro_in_t (Top_Logic_option Top_exp)))

;; "const'def"
(assert
  (forall ((v (Top_Logic_option Top_exp)))
    (forall ((us Top_ro_in_t)) (= (select (const2 v) us) v))))

;; "const'def"
(assert
  (forall ((a19 ty) (b ty))
    (forall ((v uni))
      (=>
        (sort b v)
        (forall ((us uni)) (= (infix_at b a19 (const1 b a19 v) us) v))))))

;; "Top_FMap_dom"
(declare-fun Top_FMap_dom (ty
  ty
  uni
  uni) Bool)

;; "Top_FMap_dom"
(declare-fun Top_FMap_dom1 ((Top_FMap_fmap Top_ro_in_t
  Top_exp)
  Top_ro_in_t) Bool)

;; "Top_FMap_dom'def"
(assert
  (forall ((qta1 ty))
    (forall ((m uni) (x1 uni))
      (=
        (Top_FMap_dom Top_exp1 qta1 m x1)
        (not
          (= (tb2t (Top_FMap___lb_rb Top_exp1 qta1 m x1)) (as Top_Logic_None (Top_Logic_option Top_exp))))))))

;; "Top_FMap_dom'def"
(assert
  (forall ((m (Top_FMap_fmap Top_ro_in_t Top_exp)) (x1 Top_ro_in_t))
    (=
      (Top_FMap_dom1 m x1)
      (not
        (= (Top_FMap___lb_rb1 m x1) (as Top_Logic_None (Top_Logic_option Top_exp)))))))

;; "Top_FMap_dom'def"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((m uni) (x1 uni))
      (=
        (Top_FMap_dom qtb qta1 m x1)
        (not (= (Top_FMap___lb_rb qtb qta1 m x1) (Top_Logic_None1 qtb)))))))

;; "Top_FMap_mem_empty"
(assert
  (forall ((qta1 ty))
    (forall ((x1 uni))
      (not
        (Top_FMap_dom
          Top_exp1
          qta1
          (Top_FMap_ofmap
            Top_exp1
            qta1
            (const1
              (Top_Logic_option1 Top_exp1)
              qta1
              (t2tb (as Top_Logic_None (Top_Logic_option Top_exp)))))
          x1)))))

;; "Top_FMap_mem_empty"
(assert
  (forall ((x1 Top_ro_in_t))
    (not
      (Top_FMap_dom1
        (Top_FMap_ofmap1
          (const2 (as Top_Logic_None (Top_Logic_option Top_exp))))
        x1))))

;; "Top_FMap_mem_empty"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((x1 uni))
      (not
        (Top_FMap_dom
          qtb
          qta1
          (Top_FMap_ofmap
            qtb
            qta1
            (const1 (Top_Logic_option1 qtb) qta1 (Top_Logic_None1 qtb)))
          x1)))))

;; "Top_FMap_mem_set"
(assert
  (forall ((m (Top_FMap_fmap Top_ro_in_t Top_exp)) (x1 Top_ro_in_t) (b Top_exp) (y Top_ro_in_t))
    (=
      (Top_FMap_dom1 (Top_FMap___lb_lsmn_rb1 m x1 b) y)
      (or (Top_FMap_dom1 m y) (= y x1)))))

;; "Top_FMap_mem_set"
(assert
  (forall ((qta1 ty) (qtb ty))
    (forall ((m uni) (x1 uni) (b uni) (y uni))
      (=>
        (sort qta1 x1)
        (=>
          (sort qta1 y)
          (=
            (Top_FMap_dom qtb qta1 (Top_FMap___lb_lsmn_rb qtb qta1 m x1 b) y)
            (or (Top_FMap_dom qtb qta1 m y) (= y x1))))))))

;; Goal "goal"
(assert
  (not
  (forall ((ethr (tuple2 (tuple10 (tuple3 Top_key Top_key Top_key) Top_exp Top_exp Top_exp Top_ro_in_t Top_exp Top_ro_in_t Top_exp Top_ro_in_t Top_exp) memory)))
    (=>
      (exists ((m_R (Top_FMap_fmap Top_ro_in_t Top_exp)))
        (and
          (= (Top_FullRO_RO_slm (proj2_1 ethr)) (Top_FMap___lb_lsmn_rb1
                                                  m_R
                                                  (proj10_6 (proj2_0 ethr))
                                                  (proj10_7 (proj2_0 ethr))))
          (and
            (= (proj10_2 (proj2_0 ethr)) (Top_Logic_odflt1
                                           witness2
                                           (Top_FMap___lb_rb1
                                             (Top_FullRO_RO_slm
                                               (proj2_1 ethr))
                                             (proj10_6 (proj2_0 ethr)))))
            (and
              (= (proj10_8 (proj2_0 ethr)) Top_C)
              (exists ((m_R1 (Top_FMap_fmap Top_ro_in_t Top_exp)))
                (and
                  (= m_R (Top_FMap___lb_lsmn_rb1
                           m_R1
                           (proj10_4 (proj2_0 ethr))
                           (proj10_5 (proj2_0 ethr))))
                  (and
                    (= (proj10_1 (proj2_0 ethr)) (Top_Logic_odflt1
                                                   witness2
                                                   (Top_FMap___lb_rb1
                                                     m_R
                                                     (proj10_4
                                                       (proj2_0 ethr)))))
                    (and
                      (= (proj10_6 (proj2_0 ethr)) Top_B)
                      (and
                        (and
                          (and
                            (and
                              (and
                                (= (Top_Hybrid_Or_slctr (proj2_1 etm)) 
                                (Top_RO_Disting2_Or_slctr
                                  (proj2_1 ethr)))
                                (and
                                  (and
                                    (<= 1 (Top_Hybrid_Or_slctr (proj2_1 etm)))
                                    (<= (Top_Hybrid_Or_slctr (proj2_1 etm)) (+ 
                                    Top_m 1)))
                                  (and
                                    (= (Top_Hybrid_sli (proj2_1 etm)) 
                                    iqt)
                                    (and
                                      (= (Top_RO_Disting2_sli (proj2_1 ethr)) 
                                      iqt)
                                      (=>
                                        (<= (Top_Hybrid_Or_slctr
                                              (proj2_1 etm)) iqt)
                                        (= m_R1 (Top_FMap_ofmap1
                                                  (const2
                                                    (as Top_Logic_None (Top_Logic_option Top_exp))))))))))
                              (<= (Top_Hybrid_Or_slctr (proj2_1 etm)) 
                              Top_m))
                            (not
                              (< (Top_Hybrid_Or_slctr (proj2_1 etm)) 
                              (Top_Hybrid_sli
                                (proj2_1 etm)))))
                          (= (Top_Hybrid_Or_slctr (proj2_1 etm)) (Top_Hybrid_sli
                                                                   (proj2_1
                                                                    etm))))
                        (and
                          (= (proj7_4 (proj2_0 etm)) (proj10_5
                                                       (proj2_0 ethr)))
                          (and
                            (= (proj7_5 (proj2_0 etm)) (proj10_7
                                                         (proj2_0 ethr)))
                            (and
                              (= (proj7_6 (proj2_0 etm)) (proj10_9
                                                           (proj2_0 ethr)))
                              (= (proj10_4 (proj2_0 ethr)) Top_A)))))))))))))
      (not
        (Top_FMap_dom1
          (Top_FullRO_RO_slm (proj2_1 ethr))
          (proj10_8 (proj2_0 ethr))))))))

(check-sat)
(get-info :reason-unknown)

