;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: real arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort distr 1)

;; "distr"
(declare-fun distr1 (ty) ty)

;; "Top_List_list"
(declare-fun Top_List_list (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-sort Top_r 0)

;; "Top_r"
(declare-fun Top_r1 () ty)

(declare-sort Top_Xreal_Rp_realp 0)

;; "Top_Xreal_Rp_realp"
(declare-fun Top_Xreal_Rp_realp1 () ty)

(declare-sort Top_Logic_option 1)

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta ty)) (sort (Top_Logic_option1 qta) (Top_Logic_None qta))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_Logic_option1 qta) (Top_Logic_Some qta x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_Logic_option a qta x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_Logic_option a qta (Top_Logic_None qta) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z1)
        (= (match_Top_Logic_option a qta (Top_Logic_Some qta u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty)) (= (index_Top_Logic_option qta (Top_Logic_None qta)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta (Top_Logic_Some qta u)) 1) :pattern (
      (Top_Logic_Some
        qta
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_Logic_Some_proj_1 qta x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Logic_Some_proj_1 qta (Top_Logic_Some qta u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta) u)
        (or
          (= u (Top_Logic_None qta))
          (= u (Top_Logic_Some qta (Top_Logic_Some_proj_1 qta u))))))))

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a x x1)))))

;; "mu"
(declare-fun mu (ty
  uni
  uni) Real)

;; "mu"
(declare-fun mu1 ((distr Top_r)
  (Array Top_r Bool)) Real)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "t"
(declare-fun t () Bool)

;; "log"
(declare-fun log () uni)

;; "log_sort"
(assert (sort (Top_List_list Top_r1) log))

;; "ntest"
(assert (not t))

;; "x"
(declare-fun x () Top_r)

;; "Top_dr"
(declare-fun Top_dr () (distr Top_r))

;; "Top_Logic_pred1_ho"
(declare-fun Top_Logic_pred1_ho (ty) uni)

;; "Top_Logic_pred1_ho_sort"
(assert
  (forall ((qta ty))
    (sort (infix_mngt qta (infix_mngt qta bool)) (Top_Logic_pred1_ho qta))))

;; "t2tb"
(declare-fun t2tb ((Array Top_r Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Array Top_r Bool)))
    (sort (infix_mngt Top_r1 bool) (t2tb x1))))

;; "tb2t"
(declare-fun tb2t (uni) (Array Top_r Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Top_r Bool)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (infix_mngt Top_r1 bool) j) (= (t2tb (tb2t j)) j)) :pattern (
    (t2tb
      (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_r) uni)

;; "t2tb_sort"
(assert (forall ((x1 Top_r)) (sort Top_r1 (t2tb1 x1))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_r)

;; "BridgeL"
(assert
  (forall ((i Top_r)) (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_r1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern ((t2tb1
                                                                (tb2t1 j))) )))

;; "t2tb"
(declare-fun t2tb2 ((Array Top_r (Array Top_r Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Array Top_r (Array Top_r Bool))))
    (sort (infix_mngt Top_r1 (infix_mngt Top_r1 bool)) (t2tb2 x1))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Array Top_r (Array Top_r Bool)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_r (Array Top_r Bool))))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_r1 (infix_mngt Top_r1 bool)) j)
         (= (t2tb2 (tb2t2 j)) j)) :pattern ((t2tb2 (tb2t2 j))) )))

;; "Top_Logic_pred1_ho_spec"
(assert
  (forall ((x1 Top_r) (x2 Top_r))
    (=
      (= (select (tb2t
                   (infix_at
                     (infix_mngt Top_r1 bool)
                     Top_r1
                     (Top_Logic_pred1_ho Top_r1)
                     (t2tb1 x1))) x2) true)
      (= x2 x1))))

;; "t2tb"
(declare-fun t2tb3 (Bool) uni)

;; "t2tb_sort"
(assert (forall ((x1 Bool)) (sort bool (t2tb3 x1))))

;; "tb2t"
(declare-fun tb2t3 (uni) Bool)

;; "BridgeL"
(assert
  (forall ((i Bool)) (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort bool j) (= (t2tb3 (tb2t3 j)) j)) :pattern ((t2tb3 (tb2t3 j))) )))

;; "Top_Logic_pred1_ho_spec"
(assert
  (forall ((qta ty))
    (forall ((x1 uni) (x2 uni))
      (=>
        (sort qta x1)
        (=>
          (sort qta x2)
          (=
            (= (tb2t3
                 (infix_at
                   bool
                   qta
                   (infix_at
                     (infix_mngt qta bool)
                     qta
                     (Top_Logic_pred1_ho qta)
                     x1)
                   x2)) true)
            (= x2 x1)))))))

;; "Top_Distr_support"
(declare-fun Top_Distr_support (ty
  uni
  uni) Bool)

;; "t2tb"
(declare-fun t2tb4 ((distr Top_r)) uni)

;; "t2tb_sort"
(assert (forall ((x1 (distr Top_r))) (sort (distr1 Top_r1) (t2tb4 x1))))

;; "tb2t"
(declare-fun tb2t4 (uni) (distr Top_r))

;; "BridgeL"
(assert
  (forall ((i (distr Top_r)))
    (! (= (tb2t4 (t2tb4 i)) i) :pattern ((t2tb4 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (distr1 Top_r1) j) (= (t2tb4 (tb2t4 j)) j)) :pattern (
    (t2tb4
      (tb2t4 j))) )))

;; "Top_Distr_support'def"
(assert
  (forall ((d (distr Top_r)) (x1 Top_r))
    (=
      (Top_Distr_support Top_r1 (t2tb4 d) (t2tb1 x1))
      (< 0.0 (mu1
               d
               (tb2t
                 (infix_at
                   (infix_mngt Top_r1 bool)
                   Top_r1
                   (Top_Logic_pred1_ho Top_r1)
                   (t2tb1 x1))))))))

;; "Top_Distr_support'def"
(assert
  (forall ((qta ty))
    (forall ((d uni) (x1 uni))
      (=
        (Top_Distr_support qta d x1)
        (< 0.0 (mu
                 qta
                 d
                 (infix_at
                   (infix_mngt qta bool)
                   qta
                   (Top_Logic_pred1_ho qta)
                   x1)))))))

;; "xx"
(assert (Top_Distr_support Top_r1 (t2tb4 Top_dr) (t2tb1 x)))

;; "Top_test"
(declare-fun Top_test (Top_r) Bool)

;; "Top_test_ho"
(declare-fun Top_test_ho () (Array Top_r Bool))

;; "Top_test_ho_spec"
(assert
  (forall ((x1 Top_r)) (= (= (select Top_test_ho x1) true) (Top_test x1))))

;; "Top_Xreal_Rp_of_real"
(declare-fun Top_Xreal_Rp_of_real (Real) (Top_Logic_option Top_Xreal_Rp_realp))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt (ty
  uni
  uni) uni)

;; "Top_Logic_odflt_sort"
(assert
  (forall ((qta ty))
    (forall ((x1 uni) (x2 uni)) (sort qta (Top_Logic_odflt qta x1 x2)))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((qta ty))
    (forall ((d uni))
      (=>
        (sort qta d)
        (and
          (= (Top_Logic_odflt qta d (Top_Logic_None qta)) d)
          (forall ((x1 uni))
            (=>
              (sort qta x1)
              (= (Top_Logic_odflt qta d (Top_Logic_Some qta x1)) x1))))))))

;; "Top_Xreal_Rp_of_reald"
(declare-fun Top_Xreal_Rp_of_reald (Real) Top_Xreal_Rp_realp)

;; "t2tb"
(declare-fun t2tb5 ((Top_Logic_option Top_Xreal_Rp_realp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 (Top_Logic_option Top_Xreal_Rp_realp)))
    (sort (Top_Logic_option1 Top_Xreal_Rp_realp1) (t2tb5 x1))))

;; "tb2t"
(declare-fun tb2t5 (uni) (Top_Logic_option Top_Xreal_Rp_realp))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_Xreal_Rp_realp)))
    (! (= (tb2t5 (t2tb5 i)) i) :pattern ((t2tb5 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_Xreal_Rp_realp1) j)
         (= (t2tb5 (tb2t5 j)) j)) :pattern ((t2tb5 (tb2t5 j))) )))

;; "t2tb"
(declare-fun t2tb6 (Top_Xreal_Rp_realp) uni)

;; "t2tb_sort"
(assert
  (forall ((x1 Top_Xreal_Rp_realp)) (sort Top_Xreal_Rp_realp1 (t2tb6 x1))))

;; "tb2t"
(declare-fun tb2t6 (uni) Top_Xreal_Rp_realp)

;; "BridgeL"
(assert
  (forall ((i Top_Xreal_Rp_realp))
    (! (= (tb2t6 (t2tb6 i)) i) :pattern ((t2tb6 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Xreal_Rp_realp1 j) (= (t2tb6 (tb2t6 j)) j)) :pattern (
    (t2tb6
      (tb2t6 j))) )))

;; "Top_Xreal_Rp_of_reald'def"
(assert
  (forall ((x1 Real))
    (= (Top_Xreal_Rp_of_reald x1) (tb2t6
                                    (Top_Logic_odflt
                                      Top_Xreal_Rp_realp1
                                      (witness1 Top_Xreal_Rp_realp1)
                                      (t2tb5 (Top_Xreal_Rp_of_real x1)))))))

;; "Top_Xreal_Rp_to_real"
(declare-fun Top_Xreal_Rp_to_real (Top_Xreal_Rp_realp) Real)

;; "Top_Xreal_Rp_*"
(declare-fun Top_Xreal_Rp_as (Top_Xreal_Rp_realp
  Top_Xreal_Rp_realp) Top_Xreal_Rp_realp)

;; "Top_Xreal_Rp_*'def"
(assert
  (forall ((x1 Top_Xreal_Rp_realp) (y Top_Xreal_Rp_realp))
    (= (Top_Xreal_Rp_as x1 y) (Top_Xreal_Rp_of_reald
                                (* (Top_Xreal_Rp_to_real x1) (Top_Xreal_Rp_to_real
                                                               y))))))

;; "Top_Xreal_Rp_of_realM"
(assert
  (forall ((x1 Real) (y Real))
    (=>
      (<= 0.0 x1)
      (=>
        (<= 0.0 y)
        (= (Top_Xreal_Rp_of_reald (* x1 y)) (Top_Xreal_Rp_as
                                              (Top_Xreal_Rp_of_reald x1)
                                              (Top_Xreal_Rp_of_reald y)))))))

;; "Top_StdOrder_RealOrder_invr_ge0"
(assert (forall ((x1 Real)) (= (<= 0.0 (/ 1.0 x1)) (<= 0.0 x1))))

;; "Top_Distr_ge0_mu"
(assert
  (forall ((d (distr Top_r)) (p (Array Top_r Bool))) (<= 0.0 (mu1 d p))))

;; "Top_Distr_ge0_mu"
(assert (forall ((qta ty)) (forall ((d uni) (p uni)) (<= 0.0 (mu qta d p)))))

;; Goal "goal"
(assert
  (not (<= 0.0 (/ 1.0 (mu1 Top_dr Top_test_ho)))))

(check-sat)

