;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: real arithmetic
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort distr 1)

;; "distr"
(declare-fun distr1 (ty) ty)

;; "Top_List_list"
(declare-fun Top_List_list (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-sort Top_r 0)

;; "Top_r"
(declare-fun Top_r1 () ty)

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a x x1)))))

;; "mu"
(declare-fun mu (ty
  uni
  uni) Real)

;; "mu"
(declare-fun mu1 ((distr Top_r)
  (Array Top_r Bool)) Real)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "t"
(declare-fun t () Bool)

;; "log"
(declare-fun log () uni)

;; "log_sort"
(assert (sort (Top_List_list Top_r1) log))

;; "ntest"
(assert (not t))

;; "Top_dr"
(declare-fun Top_dr () (distr Top_r))

;; "Top_test"
(declare-fun Top_test (Top_r) Bool)

;; "Top_test_ho"
(declare-fun Top_test_ho () (Array Top_r Bool))

;; "Top_test_ho_spec"
(assert
  (forall ((x Top_r)) (= (= (select Top_test_ho x) true) (Top_test x))))

;; "Top_dr_mu_test"
(assert (< 0.0 (mu1 Top_dr Top_test_ho)))

;; "Top_List_size"
(declare-fun Top_List_size (ty
  uni) Int)

;; "Top_List_size'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_size qta (Top_List_lbrb qta)) 0)
      (forall ((y uni) (ys uni))
        (= (Top_List_size qta (Top_List_clcl qta y ys)) (+ 1 (Top_List_size
                                                               qta
                                                               ys)))))))

;; "Top_List_size_ge0"
(assert (forall ((qta ty)) (forall ((s uni)) (<= 0 (Top_List_size qta s)))))

;; "Top_Distr_mu_bounded"
(assert
  (forall ((d (distr Top_r)) (p (Array Top_r Bool)))
    (and (<= 0.0 (mu1 d p)) (<= (mu1 d p) 1.0))))

;; "Top_Distr_mu_bounded"
(assert
  (forall ((qta ty))
    (forall ((d uni) (p uni))
      (and (<= 0.0 (mu qta d p)) (<= (mu qta d p) 1.0)))))

;; Goal "goal"
(assert
  (not (<= 0.0 (+ 1.0 (- (mu1 Top_dr Top_test_ho))))))

(check-sat)

