;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
;;; SMT-LIB2: real arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort distr 1)

;; "distr"
(declare-fun distr1 (ty) ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-sort Top_r 0)

;; "Top_r"
(declare-fun Top_r1 () ty)

(declare-datatypes ((tuple2 2))
  ((par (a a1) ((Tuple2 (proj2_0 a)(proj2_1 a1))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a3 a2) (Tuple21 a3 a2 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a3 (proj2_01 a3 a2 x)))))

;; "proj2_0'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a3 u) (= (proj2_01 a3 a2 (Tuple21 a3 a2 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a2 (proj2_11 a3 a2 x)))))

;; "proj2_1'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a2 u1) (= (proj2_11 a3 a2 (Tuple21 a3 a2 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a3 a2) u)
        (= u (Tuple21 a3 a2 (proj2_01 a3 a2 u) (proj2_11 a3 a2 u)))))))

(declare-sort Top_Xreal_Rp_realp 0)

;; "Top_Xreal_Rp_realp"
(declare-fun Top_Xreal_Rp_realp1 () ty)

(declare-sort Top_Logic_option 1)

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta ty)) (sort (Top_Logic_option1 qta) (Top_Logic_None qta))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_Logic_option1 qta) (Top_Logic_Some qta x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_Logic_option a2 qta x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_Logic_option a2 qta (Top_Logic_None qta) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a2 z1)
        (= (match_Top_Logic_option a2 qta (Top_Logic_Some qta u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty)) (= (index_Top_Logic_option qta (Top_Logic_None qta)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta (Top_Logic_Some qta u)) 1) :pattern (
      (Top_Logic_Some
        qta
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_Logic_Some_proj_1 qta x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Logic_Some_proj_1 qta (Top_Logic_Some qta u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta) u)
        (or
          (= u (Top_Logic_None qta))
          (= u (Top_Logic_Some qta (Top_Logic_Some_proj_1 qta u))))))))

(declare-datatypes ((Top_Xreal_Rpbar_xreal 0))
  (((Top_Xreal_Rpbar_rp (Top_Xreal_Rpbar_rp_proj Top_Xreal_Rp_realp))
   (Top_Xreal_Rpbar_oo))))

;; "Top_Xreal_Rpbar_xreal"
(declare-fun Top_Xreal_Rpbar_xreal1 () ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_List_list a2 qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_List_list a2 qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a2 z1)
        (= (match_Top_List_list a2 qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a2 ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a2 x x1)))))

;; "mu"
(declare-fun mu (ty
  uni
  uni) Real)

;; "mu"
(declare-fun mu1 ((distr Top_r)
  (Array Top_r Bool)) Real)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "&hr"
(declare-fun ethr () (tuple2 Top_r
  memory))

;; "Top_O_/c"
(declare-fun Top_O_slc (memory) Int)

;; "Top_Q"
(declare-fun Top_Q () Int)

;; "_"
(assert (not (= (Top_O_slc (proj2_1 ethr)) Top_Q)))

;; "Top_O_/bad"
(declare-fun Top_O_slbad (memory) Bool)

;; "Top_Xreal_Rp_of_real"
(declare-fun Top_Xreal_Rp_of_real (Real) (Top_Logic_option Top_Xreal_Rp_realp))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt (ty
  uni
  uni) uni)

;; "Top_Logic_odflt_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni)) (sort qta (Top_Logic_odflt qta x x1)))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((qta ty))
    (forall ((d uni))
      (=>
        (sort qta d)
        (and
          (= (Top_Logic_odflt qta d (Top_Logic_None qta)) d)
          (forall ((x uni))
            (=>
              (sort qta x)
              (= (Top_Logic_odflt qta d (Top_Logic_Some qta x)) x))))))))

;; "Top_Xreal_Rp_of_reald"
(declare-fun Top_Xreal_Rp_of_reald (Real) Top_Xreal_Rp_realp)

;; "t2tb"
(declare-fun t2tb ((Top_Logic_option Top_Xreal_Rp_realp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_Xreal_Rp_realp)))
    (sort (Top_Logic_option1 Top_Xreal_Rp_realp1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_Logic_option Top_Xreal_Rp_realp))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_Xreal_Rp_realp)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_Xreal_Rp_realp1) j)
         (= (t2tb (tb2t j)) j)) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_Xreal_Rp_realp) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_Xreal_Rp_realp)) (sort Top_Xreal_Rp_realp1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_Xreal_Rp_realp)

;; "BridgeL"
(assert
  (forall ((i Top_Xreal_Rp_realp))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Xreal_Rp_realp1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "Top_Xreal_Rp_of_reald'def"
(assert
  (forall ((x Real))
    (= (Top_Xreal_Rp_of_reald x) (tb2t1
                                   (Top_Logic_odflt
                                     Top_Xreal_Rp_realp1
                                     (witness1 Top_Xreal_Rp_realp1)
                                     (t2tb (Top_Xreal_Rp_of_real x)))))))

;; "Top_O_/log"
(declare-fun Top_O_sllog (memory) (Top_List_list Top_r))

;; "Top_List_size"
(declare-fun Top_List_size (ty
  uni) Int)

;; "Top_List_size"
(declare-fun Top_List_size1 ((Top_List_list Top_r)) Int)

;; "t2tb"
(declare-fun t2tb2 ((Top_List_list Top_r)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_r)))
    (sort (Top_List_list1 Top_r1) (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Top_List_list Top_r))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_r)))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb2 (tb2t2 j)) j) :pattern ((t2tb2 (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 (Top_r) uni)

;; "t2tb_sort"
(assert (forall ((x Top_r)) (sort Top_r1 (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) Top_r)

;; "BridgeL"
(assert
  (forall ((i Top_r)) (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_r1 j) (= (t2tb3 (tb2t3 j)) j)) :pattern ((t2tb3
                                                                (tb2t3 j))) )))

;; "Top_List_size'def"
(assert
  (and
    (= (Top_List_size1 (tb2t2 (Top_List_lbrb Top_r1))) 0)
    (forall ((y Top_r) (ys (Top_List_list Top_r)))
      (= (Top_List_size1 (tb2t2 (Top_List_clcl Top_r1 (t2tb3 y) (t2tb2 ys)))) (+ 1 
      (Top_List_size1
        ys))))))

;; "Top_List_size'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_size qta (Top_List_lbrb qta)) 0)
      (forall ((y uni) (ys uni))
        (= (Top_List_size qta (Top_List_clcl qta y ys)) (+ 1 (Top_List_size
                                                               qta
                                                               ys)))))))

;; "Top_eps"
(declare-fun Top_eps () Real)

;; "Top_Xreal_Rp_to_real"
(declare-fun Top_Xreal_Rp_to_real (Top_Xreal_Rp_realp) Real)

;; "Top_Xreal_Rp_*"
(declare-fun Top_Xreal_Rp_as (Top_Xreal_Rp_realp
  Top_Xreal_Rp_realp) Top_Xreal_Rp_realp)

;; "Top_Xreal_Rp_*'def"
(assert
  (forall ((x Top_Xreal_Rp_realp) (y Top_Xreal_Rp_realp))
    (= (Top_Xreal_Rp_as x y) (Top_Xreal_Rp_of_reald
                               (* (Top_Xreal_Rp_to_real x) (Top_Xreal_Rp_to_real
                                                             y))))))

;; "Top_dr"
(declare-fun Top_dr () (distr Top_r))

;; "Top_test"
(declare-fun Top_test (Top_r) Bool)

;; "Top_test_ho"
(declare-fun Top_test_ho () (Array Top_r Bool))

;; "Top_test_ho_spec"
(assert
  (forall ((x Top_r)) (= (= (select Top_test_ho x) true) (Top_test x))))

;; "Top_Xreal_Rp_+"
(declare-fun Top_Xreal_Rp_pl (Top_Xreal_Rp_realp
  Top_Xreal_Rp_realp) Top_Xreal_Rp_realp)

;; "Top_Xreal_Rp_+'def"
(assert
  (forall ((x Top_Xreal_Rp_realp) (y Top_Xreal_Rp_realp))
    (= (Top_Xreal_Rp_pl x y) (Top_Xreal_Rp_of_reald
                               (+ (Top_Xreal_Rp_to_real x) (Top_Xreal_Rp_to_real
                                                             y))))))

;; "Top_Xreal_`|`"
(declare-fun Top_Xreal_bqbrbq (Bool
  Top_Xreal_Rpbar_xreal) Top_Xreal_Rpbar_xreal)

;; "Top_Xreal_`|`'def"
(assert
  (forall ((b Bool) (x Top_Xreal_Rpbar_xreal))
    (ite (= b true)
      (= (Top_Xreal_bqbrbq b x) x)
      (= (Top_Xreal_bqbrbq b x) Top_Xreal_Rpbar_oo))))

;; "Top_Xreal_Rpbar_xle"
(declare-fun Top_Xreal_Rpbar_xle (Top_Xreal_Rpbar_xreal
  Top_Xreal_Rpbar_xreal) Bool)

;; "Top_Xreal_Rpbar_xle'def"
(assert
  (forall ((x Top_Xreal_Rpbar_xreal) (y Top_Xreal_Rpbar_xreal))
    (match y (((Top_Xreal_Rpbar_rp x1) (match x (((Top_Xreal_Rpbar_rp x2) 
                                                   (=
                                                     (Top_Xreal_Rpbar_xle
                                                       x
                                                       y)
                                                     (<= (Top_Xreal_Rp_to_real
                                                           x2) (Top_Xreal_Rp_to_real
                                                                 x1))))
                                                 (Top_Xreal_Rpbar_oo 
                                                   (not
                                                     (Top_Xreal_Rpbar_xle
                                                       x
                                                       y))))))
              (Top_Xreal_Rpbar_oo (match x (((Top_Xreal_Rpbar_rp x3) 
                                              (Top_Xreal_Rpbar_xle
                                                x
                                                y))
                                            (Top_Xreal_Rpbar_oo (Top_Xreal_Rpbar_xle
                                                                  x
                                                                  y)))))))))

;; Goal "goal"
(assert
  (not
  (=>
    (< Top_Q (Top_O_slc (proj2_1 ethr)))
    (Top_Xreal_Rpbar_xle
      (Top_Xreal_bqbrbq
        (ite (=>
               (= (Top_O_slbad (proj2_1 ethr)) true)
               (<= Top_Q (Top_O_slc (proj2_1 ethr))))
          true
          false)
        (ite (<= Top_Q (Top_O_slc (proj2_1 ethr)))
          (Top_Xreal_Rpbar_rp
            (Top_Xreal_Rp_of_reald
              (ite (= (Top_O_slbad (proj2_1 ethr)) true)
                (to_real 1)
                (to_real 0))))
          (Top_Xreal_Rpbar_rp
            (Top_Xreal_Rp_pl
              (Top_Xreal_Rp_as
                (Top_Xreal_Rp_of_reald
                  (to_real (Top_List_size1 (Top_O_sllog (proj2_1 ethr)))))
                (Top_Xreal_Rp_of_reald Top_eps))
              (Top_Xreal_Rp_as
                (Top_Xreal_Rp_of_reald
                  (to_real (+ Top_Q (- (Top_O_slc (proj2_1 ethr))))))
                (Top_Xreal_Rp_of_reald
                  (* Top_eps (/ 1.0 (mu1 Top_dr Top_test_ho)))))))))
      (Top_Xreal_bqbrbq
        (ite (=>
               (= (Top_O_slbad (proj2_1 ethr)) true)
               (<= Top_Q (Top_O_slc (proj2_1 ethr))))
          true
          false)
        (Top_Xreal_Rpbar_rp
          (Top_Xreal_Rp_of_reald
            (ite (= (Top_O_slbad (proj2_1 ethr)) true)
              (to_real 1)
              (to_real 0)))))))))

(check-sat)

