;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "Top_DH_GP_ZModE_exp"
(declare-fun Top_DH_GP_ZModE_exp () ty)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "x"
(declare-fun x () uni)

;; "x_sort"
(assert (sort Top_DH_GP_ZModE_exp x))

;; Goal "goal"
(assert
  (not true))

(check-sat)
(get-info :reason-unknown)

