;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "bool"
(declare-fun bool () ty)

(declare-sort Top_Array_array 1)

;; "Top_Array_array"
(declare-fun Top_Array_array1 (ty) ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "i"
(declare-fun i () Int)

;; "m"
(declare-fun m () Int)

;; "a1"
(declare-fun a1 () (Top_Array_array Bool))

;; "a2"
(declare-fun a2 () (Top_Array_array Bool))

;; "_"
(assert (<= 0 i))

;; "Top_Array_ofarray"
(declare-fun Top_Array_ofarray (ty
  uni) uni)

;; "Top_Array_ofarray_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_List_list1 qta) (Top_Array_ofarray qta x)))))

;; "Top_List_nth"
(declare-fun Top_List_nth (ty
  uni
  uni
  Int) uni)

;; "Top_List_nth_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni) (x2 Int))
      (sort qta (Top_List_nth qta x x1 x2)))))

;; "Top_List_nth'def"
(assert
  (forall ((qta ty))
    (forall ((x uni) (n Int))
      (=>
        (sort qta x)
        (and
          (= (Top_List_nth qta x (Top_List_lbrb qta) n) x)
          (forall ((y uni) (ys uni))
            (=>
              (sort qta y)
              (let ((xs (Top_List_clcl qta y ys)))
                (ite (= n 0)
                  (= (Top_List_nth qta x xs n) y)
                  (= (Top_List_nth qta x xs n) (Top_List_nth
                                                 qta
                                                 x
                                                 ys
                                                 (+ n (- 1)))))))))))))

;; "Top_Array___[_]"
(declare-fun Top_Array___lb_rb (ty
  uni
  Int) uni)

;; "Top_Array___[_]_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 Int)) (sort qta (Top_Array___lb_rb qta x x1)))))

;; "Top_Array___[_]"
(declare-fun Top_Array___lb_rb1 ((Top_Array_array Bool)
  Int) Bool)

;; "t2tb"
(declare-fun t2tb ((Top_List_list Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Bool))) (sort (Top_List_list1 bool) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_List_list Bool))

;; "BridgeL"
(assert
  (forall ((i1 (Top_List_list Bool)))
    (! (= (tb2t (t2tb i1)) i1) :pattern ((t2tb i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni)) (! (= (t2tb (tb2t j)) j) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 ((Top_Array_array Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Array_array Bool)))
    (sort (Top_Array_array1 bool) (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) (Top_Array_array Bool))

;; "BridgeL"
(assert
  (forall ((i1 (Top_Array_array Bool)))
    (! (= (tb2t1 (t2tb1 i1)) i1) :pattern ((t2tb1 i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (Top_Array_array1 bool) j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "t2tb"
(declare-fun t2tb2 (Bool) uni)

;; "t2tb_sort"
(assert (forall ((x Bool)) (sort bool (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) Bool)

;; "BridgeL"
(assert
  (forall ((i1 Bool)) (! (= (tb2t2 (t2tb2 i1)) i1) :pattern ((t2tb2 i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort bool j) (= (t2tb2 (tb2t2 j)) j)) :pattern ((t2tb2 (tb2t2 j))) )))

;; "Top_Array___[_]'def"
(assert
  (forall ((arr (Top_Array_array Bool)) (i1 Int))
    (= (Top_Array___lb_rb1 arr i1) (tb2t2
                                     (Top_List_nth
                                       bool
                                       (witness1 bool)
                                       (Top_Array_ofarray bool (t2tb1 arr))
                                       i1)))))

;; "Top_Array___[_]'def"
(assert
  (forall ((qta ty))
    (forall ((arr uni) (i1 Int))
      (= (Top_Array___lb_rb qta arr i1) (Top_List_nth
                                          qta
                                          (witness1 qta)
                                          (Top_Array_ofarray qta arr)
                                          i1)))))

;; "_"
(assert
  (and
    (forall ((iqt Int) (jqt Int))
      (=>
        (and (<= 0 iqt) (< iqt i))
        (=>
          (and (<= 0 jqt) (< jqt m))
          (=
            (= (Top_Array___lb_rb1 a1 (+ (* iqt m) jqt)) true)
            (= (Top_Array___lb_rb1 a2 (+ (* iqt m) jqt)) true)))))
    (forall ((jqt Int))
      (=>
        (and (<= 0 jqt) (< jqt m))
        (=
          (= (Top_Array___lb_rb1 a1 (+ (* i m) jqt)) true)
          (= (Top_Array___lb_rb1 a2 (+ (* i m) jqt)) true))))))

;; "i'"
(declare-fun iqt () Int)

;; "j'"
(declare-fun jqt () Int)

;; "_"
(assert (and (<= 0 iqt) (< iqt (+ i 1))))

;; "_"
(assert (and (<= 0 jqt) (< jqt m)))

;; Goal "goal"
(assert
  (not
  (=>
    (< iqt i)
    (=
      (= (Top_Array___lb_rb1 a1 (+ (* iqt m) jqt)) true)
      (= (Top_Array___lb_rb1 a2 (+ (* iqt m) jqt)) true)))))

(check-sat)

