;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "bool"
(declare-fun bool () ty)

(declare-sort memory 0)

;; "memory"
(declare-fun memory1 () ty)

(declare-sort Top_HMAC_SHA256_mK 0)

;; "Top_HMAC_SHA256_mK"
(declare-fun Top_HMAC_SHA256_mK1 () ty)

(declare-sort Top_Block_block 0)

;; "Top_Block_block"
(declare-fun Top_Block_block1 () ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-datatypes ((tuple2 2))
  ((par (a a1) ((Tuple2 (proj2_0 a)(proj2_1 a1))))))

;; "tuple2"
(declare-fun tuple21 (ty
  ty) ty)

;; "Tuple2"
(declare-fun Tuple21 (ty
  ty
  uni
  uni) uni)

;; "Tuple2_sort"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((x uni) (x1 uni)) (sort (tuple21 a3 a2) (Tuple21 a3 a2 x x1)))))

;; "proj2_0"
(declare-fun proj2_01 (ty
  ty
  uni) uni)

;; "proj2_0_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a3 (proj2_01 a3 a2 x)))))

;; "proj2_0'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a3 u) (= (proj2_01 a3 a2 (Tuple21 a3 a2 u u1)) u)))))

;; "proj2_1"
(declare-fun proj2_11 (ty
  ty
  uni) uni)

;; "proj2_1_sort"
(assert
  (forall ((a2 ty) (a3 ty)) (forall ((x uni)) (sort a2 (proj2_11 a3 a2 x)))))

;; "proj2_1'def"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni) (u1 uni))
      (=> (sort a2 u1) (= (proj2_11 a3 a2 (Tuple21 a3 a2 u u1)) u1)))))

;; "tuple2_inversion"
(assert
  (forall ((a2 ty) (a3 ty))
    (forall ((u uni))
      (=>
        (sort (tuple21 a3 a2) u)
        (= u (Tuple21 a3 a2 (proj2_01 a3 a2 u) (proj2_11 a3 a2 u)))))))

(declare-sort Top_Tag_tag 0)

;; "Top_Tag_tag"
(declare-fun Top_Tag_tag1 () ty)

(declare-sort Top_Logic_option 1)

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta ty)) (sort (Top_Logic_option1 qta) (Top_Logic_None qta))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_Logic_option1 qta) (Top_Logic_Some qta x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a2 (match_Top_Logic_option a2 qta x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a2 z)
        (= (match_Top_Logic_option a2 qta (Top_Logic_None qta) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty) (a2 ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a2 z1)
        (= (match_Top_Logic_option a2 qta (Top_Logic_Some qta u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty)) (= (index_Top_Logic_option qta (Top_Logic_None qta)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta (Top_Logic_Some qta u)) 1) :pattern (
      (Top_Logic_Some
        qta
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_Logic_Some_proj_1 qta x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Logic_Some_proj_1 qta (Top_Logic_Some qta u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta) u)
        (or
          (= u (Top_Logic_None qta))
          (= u (Top_Logic_Some qta (Top_Logic_Some_proj_1 qta u))))))))

(declare-sort Top_Octet_octet 0)

;; "Top_Octet_octet"
(declare-fun Top_Octet_octet1 () ty)

(declare-datatypes ((tuple19 19))
  ((par (a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19
   a20) ((Tuple19
         (proj19_0 a2)(proj19_1 a3)(proj19_2 a4)(proj19_3 a5)(proj19_4 a6)(proj19_5 a7)(proj19_6 a8)(proj19_7 a9)(proj19_8 a10)(proj19_9 a11)(proj19_10 a12)(proj19_11 a13)(proj19_12 a14)(proj19_13 a15)(proj19_14 a16)(proj19_15 a17)(proj19_16 a18)(proj19_17 a19)(proj19_18 a20))))))

;; "tuple19"
(declare-fun tuple191 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty) ty)

;; "Tuple19"
(declare-fun Tuple191 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni
  uni) uni)

;; "Tuple19_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni) (x1 uni) (x2 uni) (x3 uni) (x4 uni) (x5 uni) (x6 uni) (x7 uni) (x8 uni) (x9 uni) (x10 uni) (x11 uni) (x12 uni) (x13 uni) (x14 uni) (x15 uni) (x16 uni) (x17 uni) (x18 uni))
      (sort
        (tuple191
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21)
        (Tuple191
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x
          x1
          x2
          x3
          x4
          x5
          x6
          x7
          x8
          x9
          x10
          x11
          x12
          x13
          x14
          x15
          x16
          x17
          x18)))))

;; "proj19_0"
(declare-fun proj19_01 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_0_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a39
        (proj19_01
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_0'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a39 u)
        (= (proj19_01
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u)))))

;; "proj19_1"
(declare-fun proj19_19 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_1_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a38
        (proj19_19
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_1'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a38 u1)
        (= (proj19_19
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u1)))))

;; "proj19_2"
(declare-fun proj19_21 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_2_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a37
        (proj19_21
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_2'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a37 u2)
        (= (proj19_21
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u2)))))

;; "proj19_3"
(declare-fun proj19_31 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_3_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a36
        (proj19_31
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_3'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a36 u3)
        (= (proj19_31
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u3)))))

;; "proj19_4"
(declare-fun proj19_41 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_4_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a35
        (proj19_41
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_4'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a35 u4)
        (= (proj19_41
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u4)))))

;; "proj19_5"
(declare-fun proj19_51 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_5_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a34
        (proj19_51
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_5'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a34 u5)
        (= (proj19_51
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u5)))))

;; "proj19_6"
(declare-fun proj19_61 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_6_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a33
        (proj19_61
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_6'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a33 u6)
        (= (proj19_61
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u6)))))

;; "proj19_7"
(declare-fun proj19_71 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_7_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a32
        (proj19_71
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_7'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a32 u7)
        (= (proj19_71
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u7)))))

;; "proj19_8"
(declare-fun proj19_81 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_8_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a31
        (proj19_81
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_8'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a31 u8)
        (= (proj19_81
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u8)))))

;; "proj19_9"
(declare-fun proj19_91 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_9_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a30
        (proj19_91
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_9'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a30 u9)
        (= (proj19_91
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u9)))))

;; "proj19_10"
(declare-fun proj19_101 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_10_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a29
        (proj19_101
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_10'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a29 u10)
        (= (proj19_101
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u10)))))

;; "proj19_11"
(declare-fun proj19_111 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_11_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a28
        (proj19_111
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_11'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a28 u11)
        (= (proj19_111
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u11)))))

;; "proj19_12"
(declare-fun proj19_121 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_12_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a27
        (proj19_121
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_12'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a27 u12)
        (= (proj19_121
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u12)))))

;; "proj19_13"
(declare-fun proj19_131 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_13_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a26
        (proj19_131
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_13'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a26 u13)
        (= (proj19_131
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u13)))))

;; "proj19_14"
(declare-fun proj19_141 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_14_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a25
        (proj19_141
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_14'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a25 u14)
        (= (proj19_141
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u14)))))

;; "proj19_15"
(declare-fun proj19_151 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_15_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a24
        (proj19_151
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_15'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a24 u15)
        (= (proj19_151
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u15)))))

;; "proj19_16"
(declare-fun proj19_161 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_16_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a23
        (proj19_161
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_16'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a23 u16)
        (= (proj19_161
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u16)))))

;; "proj19_17"
(declare-fun proj19_171 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_17_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a22
        (proj19_171
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_17'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a22 u17)
        (= (proj19_171
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u17)))))

;; "proj19_18"
(declare-fun proj19_181 (ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  ty
  uni) uni)

;; "proj19_18_sort"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((x uni))
      (sort
        a21
        (proj19_181
          a39
          a38
          a37
          a36
          a35
          a34
          a33
          a32
          a31
          a30
          a29
          a28
          a27
          a26
          a25
          a24
          a23
          a22
          a21
          x)))))

;; "proj19_18'def"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni) (u1 uni) (u2 uni) (u3 uni) (u4 uni) (u5 uni) (u6 uni) (u7 uni) (u8 uni) (u9 uni) (u10 uni) (u11 uni) (u12 uni) (u13 uni) (u14 uni) (u15 uni) (u16 uni) (u17 uni) (u18 uni))
      (=>
        (sort a21 u18)
        (= (proj19_181
             a39
             a38
             a37
             a36
             a35
             a34
             a33
             a32
             a31
             a30
             a29
             a28
             a27
             a26
             a25
             a24
             a23
             a22
             a21
             (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               u
               u1
               u2
               u3
               u4
               u5
               u6
               u7
               u8
               u9
               u10
               u11
               u12
               u13
               u14
               u15
               u16
               u17
               u18)) u18)))))

;; "tuple19_inversion"
(assert
  (forall ((a21 ty) (a22 ty) (a23 ty) (a24 ty) (a25 ty) (a26 ty) (a27 ty) (a28 ty) (a29 ty) (a30 ty) (a31 ty) (a32 ty) (a33 ty) (a34 ty) (a35 ty) (a36 ty) (a37 ty) (a38 ty) (a39 ty))
    (forall ((u uni))
      (=>
        (sort
          (tuple191
            a39
            a38
            a37
            a36
            a35
            a34
            a33
            a32
            a31
            a30
            a29
            a28
            a27
            a26
            a25
            a24
            a23
            a22
            a21)
          u)
        (= u (Tuple191
               a39
               a38
               a37
               a36
               a35
               a34
               a33
               a32
               a31
               a30
               a29
               a28
               a27
               a26
               a25
               a24
               a23
               a22
               a21
               (proj19_01
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_19
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_21
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_31
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_41
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_51
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_61
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_71
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_81
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_91
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_101
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_111
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_121
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_131
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_141
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_151
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_161
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_171
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)
               (proj19_181
                 a39
                 a38
                 a37
                 a36
                 a35
                 a34
                 a33
                 a32
                 a31
                 a30
                 a29
                 a28
                 a27
                 a26
                 a25
                 a24
                 a23
                 a22
                 a21
                 u)))))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "_mk"
(declare-fun usmk () Top_HMAC_SHA256_mK)

;; "_ek"
(declare-fun usek () Top_Block_block)

;; "_c"
(declare-fun usc () (Top_List_list Top_Block_block))

;; "z"
(declare-fun z () Int)

;; "Top_List_size"
(declare-fun Top_List_size (ty
  uni) Int)

;; "Top_List_size"
(declare-fun Top_List_size1 ((Top_List_list Top_Block_block)) Int)

;; "t2tb"
(declare-fun t2tb ((Top_List_list Top_Block_block)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_Block_block)))
    (sort (Top_List_list1 Top_Block_block1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_List_list Top_Block_block))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_Block_block)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni)) (! (= (t2tb (tb2t j)) j) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_Block_block) uni)

;; "t2tb_sort"
(assert (forall ((x Top_Block_block)) (sort Top_Block_block1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_Block_block)

;; "BridgeL"
(assert
  (forall ((i Top_Block_block))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Block_block1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "Top_List_size'def"
(assert
  (and
    (= (Top_List_size1 (tb2t (Top_List_lbrb Top_Block_block1))) 0)
    (forall ((y Top_Block_block) (ys (Top_List_list Top_Block_block)))
      (= (Top_List_size1
           (tb2t (Top_List_clcl Top_Block_block1 (t2tb1 y) (t2tb ys)))) (+ 1 
      (Top_List_size1
        ys))))))

;; "Top_List_size'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_size qta (Top_List_lbrb qta)) 0)
      (forall ((y uni) (ys uni))
        (= (Top_List_size qta (Top_List_clcl qta y ys)) (+ 1 (Top_List_size
                                                               qta
                                                               ys)))))))

;; Goal "goal"
(assert
  (not
  (forall ((ethr (tuple2 (tuple19 (tuple2 Top_Block_block Top_HMAC_SHA256_mK) (Top_List_list Top_Block_block) Top_Block_block Top_HMAC_SHA256_mK Top_Tag_tag Top_Block_block Int Top_Block_block Top_Block_block (Top_List_list Top_Block_block) (Top_Logic_option (tuple2 (Top_List_list Top_Octet_octet) Top_Tag_tag)) (Top_List_list Top_Octet_octet) Bool (Top_Logic_option (Top_List_list Top_Octet_octet)) Top_Block_block Top_Block_block Top_HMAC_SHA256_mK (Top_List_list Top_Octet_octet) Top_Tag_tag) memory)))
    (=>
      (and
        (< (proj19_6 (proj2_0 ethr)) (Top_List_size1
                                       (proj19_1 (proj2_0 ethr))))
        (= (+ (Top_List_size1 (proj19_1 (proj2_0 ethr))) (- (proj19_6
                                                              (proj2_0 ethr)))) 
        z))
      (< (+ (Top_List_size1 (proj19_1 (proj2_0 ethr))) (- (+ (proj19_6
                                                               (proj2_0 ethr)) 1))) 
      z)))))

(check-sat)

