;; produced by cvc5.drv ;;
(set-logic ALL)
(set-info :smt-lib-version 2.6)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
;;; SMT-LIB2: real arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "real"
(declare-fun real () ty)

;; "bool"
(declare-fun bool () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort distr 1)

;; "distr"
(declare-fun distr1 (ty) ty)

(declare-sort Top_DiffieHellman_GP_ZModE_exp 0)

;; "Top_DiffieHellman_GP_ZModE_exp"
(declare-fun Top_DiffieHellman_GP_ZModE_exp1 () ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-sort Top_DiffieHellman_G_group 0)

;; "Top_DiffieHellman_G_group"
(declare-fun Top_DiffieHellman_G_group1 () ty)

(declare-sort Top_Logic_option 1)

;; "Top_Logic_option"
(declare-fun Top_Logic_option1 (ty) ty)

;; "Top_Logic_None"
(declare-fun Top_Logic_None (ty) uni)

;; "Top_Logic_None_sort"
(assert
  (forall ((qta ty)) (sort (Top_Logic_option1 qta) (Top_Logic_None qta))))

;; "Top_Logic_Some"
(declare-fun Top_Logic_Some (ty
  uni) uni)

;; "Top_Logic_Some_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_Logic_option1 qta) (Top_Logic_Some qta x)))))

;; "match_Top_Logic_option"
(declare-fun match_Top_Logic_option (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_Logic_option_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_Logic_option a qta x x1 x2)))))

;; "match_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_Logic_option a qta (Top_Logic_None qta) z z1) z)))))

;; "match_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni))
      (=>
        (sort a z1)
        (= (match_Top_Logic_option a qta (Top_Logic_Some qta u) z z1) z1)))))

;; "index_Top_Logic_option"
(declare-fun index_Top_Logic_option (ty
  uni) Int)

;; "index_Top_Logic_option_Top_Logic_None"
(assert
  (forall ((qta ty)) (= (index_Top_Logic_option qta (Top_Logic_None qta)) 0)))

;; "index_Top_Logic_option_Top_Logic_Some"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (! (= (index_Top_Logic_option qta (Top_Logic_Some qta u)) 1) :pattern (
      (Top_Logic_Some
        qta
        u)) ))))

;; "Top_Logic_Some_proj_1"
(declare-fun Top_Logic_Some_proj_1 (ty
  uni) uni)

;; "Top_Logic_Some_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_Logic_Some_proj_1 qta x)))))

;; "Top_Logic_Some_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort qta u)
        (= (Top_Logic_Some_proj_1 qta (Top_Logic_Some qta u)) u)))))

;; "Top_Logic_option_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (=>
        (sort (Top_Logic_option1 qta) u)
        (or
          (= u (Top_Logic_None qta))
          (= u (Top_Logic_Some qta (Top_Logic_Some_proj_1 qta u))))))))

(declare-sort Top_FSet_fset 1)

;; "Top_FSet_fset"
(declare-fun Top_FSet_fset1 (ty) ty)

(declare-sort Top_Bits_bits 0)

;; "Top_Bits_bits"
(declare-fun Top_Bits_bits1 () ty)

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a x x1)))))

;; "mu"
(declare-fun mu (ty
  uni
  uni) Real)

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "CompatOrderMult"
(assert
  (forall ((x Int) (y Int) (z Int))
    (=> (<= x y) (=> (<= 0 z) (<= (* x z) (* y z))))))

;; "Mod_0"
(assert (forall ((y Int)) (=> (not (= y 0)) (= (mod 0 y) 0))))

;; "Mod_1_left"
(assert (forall ((y Int)) (=> (< 1 y) (= (mod 1 y) 1))))

;; "Mod_minus1_left"
(assert (forall ((y Int)) (=> (< 1 y) (= (mod (- 1) y) (- y 1)))))

;; "Mod_mult"
(assert
  (forall ((x Int) (y Int) (z Int))
    (! (=> (< 0 x) (= (mod (+ (* x y) z) x) (mod z x))) :pattern ((mod (+ (* x y) z) x)) )))

;; "Top_DiffieHellman_G_elems"
(declare-fun Top_DiffieHellman_G_elems () (Top_List_list Top_DiffieHellman_G_group))

;; "Top_List_size"
(declare-fun Top_List_size (ty
  uni) Int)

;; "Top_List_size"
(declare-fun Top_List_size1 ((Top_List_list Top_DiffieHellman_G_group)) Int)

;; "t2tb"
(declare-fun t2tb ((Top_List_list Top_DiffieHellman_G_group)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_DiffieHellman_G_group)))
    (sort (Top_List_list1 Top_DiffieHellman_G_group1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_List_list Top_DiffieHellman_G_group))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_DiffieHellman_G_group)))
    (! (= (tb2t (t2tb i)) i) :pattern ((t2tb i)) )))

;; "BridgeR"
(assert
  (forall ((j uni)) (! (= (t2tb (tb2t j)) j) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_DiffieHellman_G_group) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_DiffieHellman_G_group))
    (sort Top_DiffieHellman_G_group1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_DiffieHellman_G_group)

;; "BridgeL"
(assert
  (forall ((i Top_DiffieHellman_G_group))
    (! (= (tb2t1 (t2tb1 i)) i) :pattern ((t2tb1 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_DiffieHellman_G_group1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "Top_List_size'def"
(assert
  (and
    (= (Top_List_size1 (tb2t (Top_List_lbrb Top_DiffieHellman_G_group1))) 0)
    (forall ((y Top_DiffieHellman_G_group) (ys (Top_List_list Top_DiffieHellman_G_group)))
      (= (Top_List_size1
           (tb2t
             (Top_List_clcl Top_DiffieHellman_G_group1 (t2tb1 y) (t2tb ys)))) (+ 1 
      (Top_List_size1
        ys))))))

;; "Top_List_size'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_size qta (Top_List_lbrb qta)) 0)
      (forall ((y uni) (ys uni))
        (= (Top_List_size qta (Top_List_clcl qta y ys)) (+ 1 (Top_List_size
                                                               qta
                                                               ys)))))))

;; "Top_DiffieHellman_GP_ZModE_Sub_insub"
(declare-fun Top_DiffieHellman_GP_ZModE_Sub_insub (Int) (Top_Logic_option Top_DiffieHellman_GP_ZModE_exp))

;; "Top_Logic_odflt"
(declare-fun Top_Logic_odflt (ty
  uni
  uni) uni)

;; "Top_Logic_odflt_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni)) (sort qta (Top_Logic_odflt qta x x1)))))

;; "Top_Logic_odflt'def"
(assert
  (forall ((qta ty))
    (forall ((d uni))
      (=>
        (sort qta d)
        (and
          (= (Top_Logic_odflt qta d (Top_Logic_None qta)) d)
          (forall ((x uni))
            (=>
              (sort qta x)
              (= (Top_Logic_odflt qta d (Top_Logic_Some qta x)) x))))))))

;; "Top_DiffieHellman_GP_ZModE_Sub_insubd"
(declare-fun Top_DiffieHellman_GP_ZModE_Sub_insubd (Int) Top_DiffieHellman_GP_ZModE_exp)

;; "t2tb"
(declare-fun t2tb2 ((Top_Logic_option Top_DiffieHellman_GP_ZModE_exp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_DiffieHellman_GP_ZModE_exp)))
    (sort (Top_Logic_option1 Top_DiffieHellman_GP_ZModE_exp1) (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Top_Logic_option Top_DiffieHellman_GP_ZModE_exp))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_DiffieHellman_GP_ZModE_exp)))
    (! (= (tb2t2 (t2tb2 i)) i) :pattern ((t2tb2 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_DiffieHellman_GP_ZModE_exp1) j)
         (= (t2tb2 (tb2t2 j)) j)) :pattern ((t2tb2 (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 (Top_DiffieHellman_GP_ZModE_exp) uni)

;; "t2tb_sort"
(assert
  (forall ((x Top_DiffieHellman_GP_ZModE_exp))
    (sort Top_DiffieHellman_GP_ZModE_exp1 (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) Top_DiffieHellman_GP_ZModE_exp)

;; "BridgeL"
(assert
  (forall ((i Top_DiffieHellman_GP_ZModE_exp))
    (! (= (tb2t3 (t2tb3 i)) i) :pattern ((t2tb3 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_DiffieHellman_GP_ZModE_exp1 j) (= (t2tb3 (tb2t3 j)) j)) :pattern (
    (t2tb3
      (tb2t3 j))) )))

;; "Top_DiffieHellman_GP_ZModE_Sub_insubd'def"
(assert
  (forall ((x Int))
    (= (Top_DiffieHellman_GP_ZModE_Sub_insubd x) (tb2t3
                                                   (Top_Logic_odflt
                                                     Top_DiffieHellman_GP_ZModE_exp1
                                                     (witness1
                                                       Top_DiffieHellman_GP_ZModE_exp1)
                                                     (t2tb2
                                                       (Top_DiffieHellman_GP_ZModE_Sub_insub
                                                         x)))))))

;; "Top_DiffieHellman_GP_ZModE_inzmod"
(declare-fun Top_DiffieHellman_GP_ZModE_inzmod (Int) Top_DiffieHellman_GP_ZModE_exp)

;; "Top_DiffieHellman_GP_ZModE_inzmod'def"
(assert
  (forall ((z Int))
    (= (Top_DiffieHellman_GP_ZModE_inzmod z) (Top_DiffieHellman_GP_ZModE_Sub_insubd
                                               (mod z (Top_List_size1
                                                        Top_DiffieHellman_G_elems))))))

;; "Top_DiffieHellman_GP_ZModE_inzmod_ho"
(declare-fun Top_DiffieHellman_GP_ZModE_inzmod_ho () (Array Int Top_DiffieHellman_GP_ZModE_exp))

;; "Top_DiffieHellman_GP_ZModE_inzmod_ho_spec"
(assert
  (forall ((x Int))
    (= (select Top_DiffieHellman_GP_ZModE_inzmod_ho x) (Top_DiffieHellman_GP_ZModE_inzmod
                                                         x))))

;; "Top_List_Iota_iota_"
(declare-fun Top_List_Iota_iota_ (Int
  Int) (Top_List_list Int))

;; "Top_List_Range_range"
(declare-fun Top_List_Range_range (Int
  Int) (Top_List_list Int))

;; "Top_List_Range_range'def"
(assert
  (forall ((m Int) (n Int))
    (= (Top_List_Range_range m n) (Top_List_Iota_iota_ m (+ n (- m))))))

;; "Top_List_map"
(declare-fun Top_List_map (ty
  ty
  uni
  uni) uni)

;; "Top_List_map_sort"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qtb) (Top_List_map qta qtb x x1)))))

;; "Top_List_map"
(declare-fun Top_List_map1 ((Array Int Top_DiffieHellman_GP_ZModE_exp)
  (Top_List_list Int)) (Top_List_list Top_DiffieHellman_GP_ZModE_exp))

;; "Top_List_map"
(declare-fun Top_List_map2 ((Array (Top_List_list Bool) Top_Bits_bits)
  (Top_List_list (Top_List_list Bool))) (Top_List_list Top_Bits_bits))

;; "t2tb"
(declare-fun t2tb4 ((Top_List_list Top_Bits_bits)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_Bits_bits)))
    (sort (Top_List_list1 Top_Bits_bits1) (t2tb4 x))))

;; "tb2t"
(declare-fun tb2t4 (uni) (Top_List_list Top_Bits_bits))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_Bits_bits)))
    (! (= (tb2t4 (t2tb4 i)) i) :pattern ((t2tb4 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb4 (tb2t4 j)) j) :pattern ((t2tb4 (tb2t4 j))) )))

;; "t2tb"
(declare-fun t2tb5 (Top_Bits_bits) uni)

;; "t2tb_sort"
(assert (forall ((x Top_Bits_bits)) (sort Top_Bits_bits1 (t2tb5 x))))

;; "tb2t"
(declare-fun tb2t5 (uni) Top_Bits_bits)

;; "BridgeL"
(assert
  (forall ((i Top_Bits_bits))
    (! (= (tb2t5 (t2tb5 i)) i) :pattern ((t2tb5 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Bits_bits1 j) (= (t2tb5 (tb2t5 j)) j)) :pattern (
    (t2tb5
      (tb2t5 j))) )))

;; "t2tb"
(declare-fun t2tb6 ((Top_List_list (Top_List_list Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list (Top_List_list Bool))))
    (sort (Top_List_list1 (Top_List_list1 bool)) (t2tb6 x))))

;; "tb2t"
(declare-fun tb2t6 (uni) (Top_List_list (Top_List_list Bool)))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list (Top_List_list Bool))))
    (! (= (tb2t6 (t2tb6 i)) i) :pattern ((t2tb6 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb6 (tb2t6 j)) j) :pattern ((t2tb6 (tb2t6 j))) )))

;; "t2tb"
(declare-fun t2tb7 ((Top_List_list Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Bool))) (sort (Top_List_list1 bool) (t2tb7 x))))

;; "tb2t"
(declare-fun tb2t7 (uni) (Top_List_list Bool))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Bool)))
    (! (= (tb2t7 (t2tb7 i)) i) :pattern ((t2tb7 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb7 (tb2t7 j)) j) :pattern ((t2tb7 (tb2t7 j))) )))

;; "Top_List_map'def"
(assert
  (forall ((f (Array (Top_List_list Bool) Top_Bits_bits)))
    (and
      (= (Top_List_map2 f (tb2t6 (Top_List_lbrb (Top_List_list1 bool)))) 
      (tb2t4
        (Top_List_lbrb Top_Bits_bits1)))
      (forall ((y (Top_List_list Bool)) (ys (Top_List_list (Top_List_list Bool))))
        (= (Top_List_map2
             f
             (tb2t6
               (Top_List_clcl (Top_List_list1 bool) (t2tb7 y) (t2tb6 ys)))) 
        (tb2t4
          (Top_List_clcl
            Top_Bits_bits1
            (t2tb5 (select f y))
            (t2tb4 (Top_List_map2 f ys)))))))))

;; "t2tb"
(declare-fun t2tb8 ((Top_List_list Top_DiffieHellman_GP_ZModE_exp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_DiffieHellman_GP_ZModE_exp)))
    (sort (Top_List_list1 Top_DiffieHellman_GP_ZModE_exp1) (t2tb8 x))))

;; "tb2t"
(declare-fun tb2t8 (uni) (Top_List_list Top_DiffieHellman_GP_ZModE_exp))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Top_DiffieHellman_GP_ZModE_exp)))
    (! (= (tb2t8 (t2tb8 i)) i) :pattern ((t2tb8 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb8 (tb2t8 j)) j) :pattern ((t2tb8 (tb2t8 j))) )))

;; "t2tb"
(declare-fun t2tb9 ((Top_List_list Int)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Int))) (sort (Top_List_list1 int) (t2tb9 x))))

;; "tb2t"
(declare-fun tb2t9 (uni) (Top_List_list Int))

;; "BridgeL"
(assert
  (forall ((i (Top_List_list Int)))
    (! (= (tb2t9 (t2tb9 i)) i) :pattern ((t2tb9 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb9 (tb2t9 j)) j) :pattern ((t2tb9 (tb2t9 j))) )))

;; "t2tb"
(declare-fun t2tb10 (Int) uni)

;; "t2tb_sort"
(assert (forall ((x Int)) (sort int (t2tb10 x))))

;; "tb2t"
(declare-fun tb2t10 (uni) Int)

;; "BridgeL"
(assert
  (forall ((i Int)) (! (= (tb2t10 (t2tb10 i)) i) :pattern ((t2tb10 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb10 (tb2t10 j)) j) :pattern ((t2tb10 (tb2t10 j))) )))

;; "Top_List_map'def"
(assert
  (forall ((f (Array Int Top_DiffieHellman_GP_ZModE_exp)))
    (and
      (= (Top_List_map1 f (tb2t9 (Top_List_lbrb int))) (tb2t8
                                                         (Top_List_lbrb
                                                           Top_DiffieHellman_GP_ZModE_exp1)))
      (forall ((y Int) (ys (Top_List_list Int)))
        (= (Top_List_map1
             f
             (tb2t9 (Top_List_clcl int (t2tb10 y) (t2tb9 ys)))) (tb2t8
                                                                  (Top_List_clcl
                                                                    Top_DiffieHellman_GP_ZModE_exp1
                                                                    (t2tb3
                                                                    (select f y))
                                                                    (t2tb8
                                                                    (Top_List_map1
                                                                    f
                                                                    ys)))))))))

;; "Top_List_map'def"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((f uni))
      (and
        (= (Top_List_map qta qtb f (Top_List_lbrb qta)) (Top_List_lbrb qtb))
        (forall ((y uni) (ys uni))
          (= (Top_List_map qta qtb f (Top_List_clcl qta y ys)) (Top_List_clcl
                                                                 qtb
                                                                 (infix_at
                                                                   qtb
                                                                   qta
                                                                   f
                                                                   y)
                                                                 (Top_List_map
                                                                   qta
                                                                   qtb
                                                                   f
                                                                   ys))))))))

;; "Top_List_mem"
(declare-fun Top_List_mem (ty
  uni
  uni) Bool)

;; "Top_List_mem'def"
(assert
  (forall ((qta ty))
    (forall ((z uni))
      (=>
        (sort qta z)
        (and
          (not (Top_List_mem qta (Top_List_lbrb qta) z))
          (forall ((x uni) (sqt uni))
            (=>
              (sort qta x)
              (=
                (Top_List_mem qta (Top_List_clcl qta x sqt) z)
                (or (= z x) (Top_List_mem qta sqt z))))))))))

;; "Top_List_undup"
(declare-fun Top_List_undup (ty
  uni) uni)

;; "Top_List_undup_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_List_list1 qta) (Top_List_undup qta x)))))

;; "Top_List_undup'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_undup qta (Top_List_lbrb qta)) (Top_List_lbrb qta))
      (forall ((x uni) (sqt uni))
        (let ((s (Top_List_clcl qta x sqt)))
          (ite (Top_List_mem qta sqt x)
            (= (Top_List_undup qta s) (Top_List_undup qta sqt))
            (= (Top_List_undup qta s) (Top_List_clcl
                                        qta
                                        x
                                        (Top_List_undup qta sqt)))))))))

;; "Top_Logic_pred1_ho"
(declare-fun Top_Logic_pred1_ho (ty) uni)

;; "Top_Logic_pred1_ho_sort"
(assert
  (forall ((qta ty))
    (sort (infix_mngt qta (infix_mngt qta bool)) (Top_Logic_pred1_ho qta))))

;; "t2tb"
(declare-fun t2tb11 (Bool) uni)

;; "t2tb_sort"
(assert (forall ((x Bool)) (sort bool (t2tb11 x))))

;; "tb2t"
(declare-fun tb2t11 (uni) Bool)

;; "BridgeL"
(assert
  (forall ((i Bool)) (! (= (tb2t11 (t2tb11 i)) i) :pattern ((t2tb11 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort bool j) (= (t2tb11 (tb2t11 j)) j)) :pattern ((t2tb11
                                                                (tb2t11 j))) )))

;; "Top_Logic_pred1_ho_spec"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (=>
        (sort qta x)
        (=>
          (sort qta x1)
          (=
            (= (tb2t11
                 (infix_at
                   bool
                   qta
                   (infix_at
                     (infix_mngt qta bool)
                     qta
                     (Top_Logic_pred1_ho qta)
                     x)
                   x1)) true)
            (= x1 x)))))))

;; "Top_Int_b2i"
(declare-fun Top_Int_b2i (Bool) Int)

;; "Top_Int_b2i'def"
(assert
  (forall ((b Bool))
    (ite (= b true) (= (Top_Int_b2i b) 1) (= (Top_Int_b2i b) 0))))

;; "Top_List_count"
(declare-fun Top_List_count (ty
  uni
  uni) Int)

;; "Top_List_count'def"
(assert
  (forall ((qta ty))
    (forall ((p uni))
      (and
        (= (Top_List_count qta p (Top_List_lbrb qta)) 0)
        (forall ((y uni) (ys uni))
          (= (Top_List_count qta p (Top_List_clcl qta y ys)) (+ (Top_Int_b2i
                                                                  (tb2t11
                                                                    (infix_at
                                                                    bool
                                                                    qta
                                                                    p
                                                                    y))) 
          (Top_List_count
            qta
            p
            ys))))))))

;; "Top_Distr_MRat_mrat"
(declare-fun Top_Distr_MRat_mrat (ty
  uni
  uni) Real)

;; "t2tb"
(declare-fun t2tb12 ((Array Top_DiffieHellman_G_group Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_G_group Bool)))
    (sort (infix_mngt Top_DiffieHellman_G_group1 bool) (t2tb12 x))))

;; "tb2t"
(declare-fun tb2t12 (uni) (Array Top_DiffieHellman_G_group Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_G_group Bool)))
    (! (= (tb2t12 (t2tb12 i)) i) :pattern ((t2tb12 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_DiffieHellman_G_group1 bool) j)
         (= (t2tb12 (tb2t12 j)) j)) :pattern ((t2tb12 (tb2t12 j))) )))

;; "t2tb"
(declare-fun t2tb13 ((Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Bool))))
    (sort
      (infix_mngt
        Top_DiffieHellman_G_group1
        (infix_mngt Top_DiffieHellman_G_group1 bool))
      (t2tb13 x))))

;; "tb2t"
(declare-fun tb2t13 (uni) (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Bool)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Bool))))
    (! (= (tb2t13 (t2tb13 i)) i) :pattern ((t2tb13 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_DiffieHellman_G_group1
             (infix_mngt Top_DiffieHellman_G_group1 bool))
           j)
         (= (t2tb13 (tb2t13 j)) j)) :pattern ((t2tb13 (tb2t13 j))) )))

;; "Top_Distr_MRat_mrat'def"
(assert
  (forall ((s (Top_List_list Top_DiffieHellman_G_group)) (x Top_DiffieHellman_G_group))
    (= (Top_Distr_MRat_mrat Top_DiffieHellman_G_group1 (t2tb s) (t2tb1 x)) (* (to_real 
    (Top_List_count
      Top_DiffieHellman_G_group1
      (infix_at
        (infix_mngt Top_DiffieHellman_G_group1 bool)
        Top_DiffieHellman_G_group1
        (Top_Logic_pred1_ho Top_DiffieHellman_G_group1)
        (t2tb1 x))
      (t2tb s))) (/ 1.0 (to_real (Top_List_size1 s)))))))

;; "Top_Distr_MRat_mrat'def"
(assert
  (forall ((qta ty))
    (forall ((s uni) (x uni))
      (= (Top_Distr_MRat_mrat qta s x) (* (to_real (Top_List_count
                                                     qta
                                                     (infix_at
                                                       (infix_mngt qta bool)
                                                       qta
                                                       (Top_Logic_pred1_ho
                                                         qta)
                                                       x)
                                                     s)) (/ 1.0 (to_real 
      (Top_List_size
        qta
        s))))))))

;; "Top_Distr_MRat_mrat_ho"
(declare-fun Top_Distr_MRat_mrat_ho (ty) uni)

;; "Top_Distr_MRat_mrat_ho_sort"
(assert
  (forall ((qta ty))
    (sort
      (infix_mngt (Top_List_list1 qta) (infix_mngt qta real))
      (Top_Distr_MRat_mrat_ho qta))))

;; "t2tb"
(declare-fun t2tb14 (Real) uni)

;; "t2tb_sort"
(assert (forall ((x Real)) (sort real (t2tb14 x))))

;; "tb2t"
(declare-fun tb2t14 (uni) Real)

;; "BridgeL"
(assert
  (forall ((i Real)) (! (= (tb2t14 (t2tb14 i)) i) :pattern ((t2tb14 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb14 (tb2t14 j)) j) :pattern ((t2tb14 (tb2t14 j))) )))

;; "Top_Distr_MRat_mrat_ho_spec"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (= (tb2t14
           (infix_at
             real
             qta
             (infix_at
               (infix_mngt qta real)
               (Top_List_list1 qta)
               (Top_Distr_MRat_mrat_ho qta)
               x)
             x1)) (Top_Distr_MRat_mrat qta x x1)))))

;; "Top_Distr_mk"
(declare-fun Top_Distr_mk (ty
  uni) uni)

;; "Top_Distr_mk_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (distr1 qta) (Top_Distr_mk qta x)))))

;; "Top_Distr_MRat_drat"
(declare-fun Top_Distr_MRat_drat (ty
  uni) uni)

;; "Top_Distr_MRat_drat_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (distr1 qta) (Top_Distr_MRat_drat qta x)))))

;; "Top_Distr_MRat_drat'def"
(assert
  (forall ((qta ty))
    (forall ((s uni))
      (= (Top_Distr_MRat_drat qta s) (Top_Distr_mk
                                       qta
                                       (infix_at
                                         (infix_mngt qta real)
                                         (Top_List_list1 qta)
                                         (Top_Distr_MRat_mrat_ho qta)
                                         s))))))

;; "Top_Distr_MUniform_duniform"
(declare-fun Top_Distr_MUniform_duniform (ty
  uni) uni)

;; "Top_Distr_MUniform_duniform_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (distr1 qta) (Top_Distr_MUniform_duniform qta x)))))

;; "Top_Distr_MUniform_duniform"
(declare-fun Top_Distr_MUniform_duniform1 ((Top_List_list Top_DiffieHellman_GP_ZModE_exp)) (distr Top_DiffieHellman_GP_ZModE_exp))

;; "Top_Distr_MUniform_duniform"
(declare-fun Top_Distr_MUniform_duniform2 ((Top_List_list Top_Bits_bits)) (distr Top_Bits_bits))

;; "t2tb"
(declare-fun t2tb15 ((distr Top_Bits_bits)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (distr Top_Bits_bits)))
    (sort (distr1 Top_Bits_bits1) (t2tb15 x))))

;; "tb2t"
(declare-fun tb2t15 (uni) (distr Top_Bits_bits))

;; "BridgeL"
(assert
  (forall ((i (distr Top_Bits_bits)))
    (! (= (tb2t15 (t2tb15 i)) i) :pattern ((t2tb15 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (distr1 Top_Bits_bits1) j) (= (t2tb15 (tb2t15 j)) j)) :pattern (
    (t2tb15
      (tb2t15 j))) )))

;; "Top_Distr_MUniform_duniform'def"
(assert
  (forall ((s (Top_List_list Top_Bits_bits)))
    (= (Top_Distr_MUniform_duniform2 s) (tb2t15
                                          (Top_Distr_MRat_drat
                                            Top_Bits_bits1
                                            (Top_List_undup
                                              Top_Bits_bits1
                                              (t2tb4 s)))))))

;; "t2tb"
(declare-fun t2tb16 ((distr Top_DiffieHellman_GP_ZModE_exp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (distr Top_DiffieHellman_GP_ZModE_exp)))
    (sort (distr1 Top_DiffieHellman_GP_ZModE_exp1) (t2tb16 x))))

;; "tb2t"
(declare-fun tb2t16 (uni) (distr Top_DiffieHellman_GP_ZModE_exp))

;; "BridgeL"
(assert
  (forall ((i (distr Top_DiffieHellman_GP_ZModE_exp)))
    (! (= (tb2t16 (t2tb16 i)) i) :pattern ((t2tb16 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (distr1 Top_DiffieHellman_GP_ZModE_exp1) j)
         (= (t2tb16 (tb2t16 j)) j)) :pattern ((t2tb16 (tb2t16 j))) )))

;; "Top_Distr_MUniform_duniform'def"
(assert
  (forall ((s (Top_List_list Top_DiffieHellman_GP_ZModE_exp)))
    (= (Top_Distr_MUniform_duniform1 s) (tb2t16
                                          (Top_Distr_MRat_drat
                                            Top_DiffieHellman_GP_ZModE_exp1
                                            (Top_List_undup
                                              Top_DiffieHellman_GP_ZModE_exp1
                                              (t2tb8 s)))))))

;; "Top_Distr_MUniform_duniform'def"
(assert
  (forall ((qta ty))
    (forall ((s uni))
      (= (Top_Distr_MUniform_duniform qta s) (Top_Distr_MRat_drat
                                               qta
                                               (Top_List_undup qta s))))))

;; "Top_Distr_support"
(declare-fun Top_Distr_support (ty
  uni
  uni) Bool)

;; "Top_Distr_support"
(declare-fun Top_Distr_support1 ((distr Top_DiffieHellman_GP_ZModE_exp)
  Top_DiffieHellman_GP_ZModE_exp) Bool)

;; "Top_Distr_support"
(declare-fun Top_Distr_support2 ((distr Top_Bits_bits)
  Top_Bits_bits) Bool)

;; "t2tb"
(declare-fun t2tb17 ((Array Top_Bits_bits Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_Bits_bits Bool)))
    (sort (infix_mngt Top_Bits_bits1 bool) (t2tb17 x))))

;; "tb2t"
(declare-fun tb2t17 (uni) (Array Top_Bits_bits Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Top_Bits_bits Bool)))
    (! (= (tb2t17 (t2tb17 i)) i) :pattern ((t2tb17 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_Bits_bits1 bool) j)
         (= (t2tb17 (tb2t17 j)) j)) :pattern ((t2tb17 (tb2t17 j))) )))

;; "t2tb"
(declare-fun t2tb18 ((Array Top_Bits_bits (Array Top_Bits_bits Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_Bits_bits (Array Top_Bits_bits Bool))))
    (sort
      (infix_mngt Top_Bits_bits1 (infix_mngt Top_Bits_bits1 bool))
      (t2tb18 x))))

;; "tb2t"
(declare-fun tb2t18 (uni) (Array Top_Bits_bits (Array Top_Bits_bits Bool)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_Bits_bits (Array Top_Bits_bits Bool))))
    (! (= (tb2t18 (t2tb18 i)) i) :pattern ((t2tb18 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt Top_Bits_bits1 (infix_mngt Top_Bits_bits1 bool))
           j)
         (= (t2tb18 (tb2t18 j)) j)) :pattern ((t2tb18 (tb2t18 j))) )))

;; "Top_Distr_support'def"
(assert
  (forall ((d (distr Top_Bits_bits)) (x Top_Bits_bits))
    (=
      (Top_Distr_support2 d x)
      (< 0.0 (mu
               Top_Bits_bits1
               (t2tb15 d)
               (infix_at
                 (infix_mngt Top_Bits_bits1 bool)
                 Top_Bits_bits1
                 (Top_Logic_pred1_ho Top_Bits_bits1)
                 (t2tb5 x)))))))

;; "t2tb"
(declare-fun t2tb19 ((Array Top_DiffieHellman_GP_ZModE_exp Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_GP_ZModE_exp Bool)))
    (sort (infix_mngt Top_DiffieHellman_GP_ZModE_exp1 bool) (t2tb19 x))))

;; "tb2t"
(declare-fun tb2t19 (uni) (Array Top_DiffieHellman_GP_ZModE_exp Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_GP_ZModE_exp Bool)))
    (! (= (tb2t19 (t2tb19 i)) i) :pattern ((t2tb19 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt Top_DiffieHellman_GP_ZModE_exp1 bool) j)
         (= (t2tb19 (tb2t19 j)) j)) :pattern ((t2tb19 (tb2t19 j))) )))

;; "t2tb"
(declare-fun t2tb20 ((Array Top_DiffieHellman_GP_ZModE_exp (Array Top_DiffieHellman_GP_ZModE_exp Bool))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_GP_ZModE_exp (Array Top_DiffieHellman_GP_ZModE_exp Bool))))
    (sort
      (infix_mngt
        Top_DiffieHellman_GP_ZModE_exp1
        (infix_mngt Top_DiffieHellman_GP_ZModE_exp1 bool))
      (t2tb20 x))))

;; "tb2t"
(declare-fun tb2t20 (uni) (Array Top_DiffieHellman_GP_ZModE_exp (Array Top_DiffieHellman_GP_ZModE_exp Bool)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_GP_ZModE_exp (Array Top_DiffieHellman_GP_ZModE_exp Bool))))
    (! (= (tb2t20 (t2tb20 i)) i) :pattern ((t2tb20 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_DiffieHellman_GP_ZModE_exp1
             (infix_mngt Top_DiffieHellman_GP_ZModE_exp1 bool))
           j)
         (= (t2tb20 (tb2t20 j)) j)) :pattern ((t2tb20 (tb2t20 j))) )))

;; "Top_Distr_support'def"
(assert
  (forall ((d (distr Top_DiffieHellman_GP_ZModE_exp)) (x Top_DiffieHellman_GP_ZModE_exp))
    (=
      (Top_Distr_support1 d x)
      (< 0.0 (mu
               Top_DiffieHellman_GP_ZModE_exp1
               (t2tb16 d)
               (infix_at
                 (infix_mngt Top_DiffieHellman_GP_ZModE_exp1 bool)
                 Top_DiffieHellman_GP_ZModE_exp1
                 (Top_Logic_pred1_ho Top_DiffieHellman_GP_ZModE_exp1)
                 (t2tb3 x)))))))

;; "Top_Distr_support'def"
(assert
  (forall ((qta ty))
    (forall ((d uni) (x uni))
      (=
        (Top_Distr_support qta d x)
        (< 0.0 (mu
                 qta
                 d
                 (infix_at
                   (infix_mngt qta bool)
                   qta
                   (Top_Logic_pred1_ho qta)
                   x)))))))

;; "Top_qH"
(declare-fun Top_qH () Int)

;; "Top_FSet_elems"
(declare-fun Top_FSet_elems (ty
  uni) uni)

;; "Top_FSet_elems_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort (Top_List_list1 qta) (Top_FSet_elems qta x)))))

;; "Top_FSet_card"
(declare-fun Top_FSet_card (ty
  uni) Int)

;; "Top_FSet_card"
(declare-fun Top_FSet_card1 ((Top_FSet_fset Top_DiffieHellman_G_group)) Int)

;; "t2tb"
(declare-fun t2tb21 ((Top_FSet_fset Top_DiffieHellman_G_group)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_FSet_fset Top_DiffieHellman_G_group)))
    (sort (Top_FSet_fset1 Top_DiffieHellman_G_group1) (t2tb21 x))))

;; "tb2t"
(declare-fun tb2t21 (uni) (Top_FSet_fset Top_DiffieHellman_G_group))

;; "BridgeL"
(assert
  (forall ((i (Top_FSet_fset Top_DiffieHellman_G_group)))
    (! (= (tb2t21 (t2tb21 i)) i) :pattern ((t2tb21 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_FSet_fset1 Top_DiffieHellman_G_group1) j)
         (= (t2tb21 (tb2t21 j)) j)) :pattern ((t2tb21 (tb2t21 j))) )))

;; "Top_FSet_card'def"
(assert
  (forall ((s (Top_FSet_fset Top_DiffieHellman_G_group)))
    (= (Top_FSet_card1 s) (Top_List_size1
                            (tb2t
                              (Top_FSet_elems
                                Top_DiffieHellman_G_group1
                                (t2tb21 s)))))))

;; "Top_FSet_card'def"
(assert
  (forall ((qta ty))
    (forall ((s uni))
      (= (Top_FSet_card qta s) (Top_List_size qta (Top_FSet_elems qta s))))))

;; "unamed_lambda"
(declare-fun unamed_lambda () (Array Int Bool))

;; "t2tb"
(declare-fun t2tb22 ((Array Int Bool)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Int Bool))) (sort (infix_mngt int bool) (t2tb22 x))))

;; "tb2t"
(declare-fun tb2t22 (uni) (Array Int Bool))

;; "BridgeL"
(assert
  (forall ((i (Array Int Bool)))
    (! (= (tb2t22 (t2tb22 i)) i) :pattern ((t2tb22 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (infix_mngt int bool) j) (= (t2tb22 (tb2t22 j)) j)) :pattern (
    (t2tb22
      (tb2t22 j))) )))

;; "unamed_lambda_spec"
(assert
  (forall ((us Int))
    (not
      (= (tb2t11 (infix_at bool int (t2tb22 unamed_lambda) (t2tb10 us))) true))))

;; "Top_k"
(declare-fun Top_k () Int)

;; "Top_List_mkseq"
(declare-fun Top_List_mkseq (ty
  uni
  Int) uni)

;; "Top_List_mkseq_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 Int))
      (sort (Top_List_list1 qta) (Top_List_mkseq qta x x1)))))

;; "t2tb"
(declare-fun t2tb23 ((Array Int Top_DiffieHellman_GP_ZModE_exp)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Int Top_DiffieHellman_GP_ZModE_exp)))
    (sort (infix_mngt int Top_DiffieHellman_GP_ZModE_exp1) (t2tb23 x))))

;; "tb2t"
(declare-fun tb2t23 (uni) (Array Int Top_DiffieHellman_GP_ZModE_exp))

;; "BridgeL"
(assert
  (forall ((i (Array Int Top_DiffieHellman_GP_ZModE_exp)))
    (! (= (tb2t23 (t2tb23 i)) i) :pattern ((t2tb23 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt int Top_DiffieHellman_GP_ZModE_exp1) j)
         (= (t2tb23 (tb2t23 j)) j)) :pattern ((t2tb23 (tb2t23 j))) )))

;; "Top_List_mkseq'def"
(assert
  (forall ((f (Array Int Top_DiffieHellman_GP_ZModE_exp)) (n Int))
    (= (tb2t8 (Top_List_mkseq Top_DiffieHellman_GP_ZModE_exp1 (t2tb23 f) n)) 
    (Top_List_map1
      f
      (Top_List_Iota_iota_ 0 n)))))

;; "Top_List_mkseq'def"
(assert
  (forall ((qta ty))
    (forall ((f uni) (n Int))
      (= (Top_List_mkseq qta f n) (Top_List_map
                                    int
                                    qta
                                    f
                                    (t2tb9 (Top_List_Iota_iota_ 0 n)))))))

;; "Top_Bits_insub"
(declare-fun Top_Bits_insub ((Top_List_list Bool)) (Top_Logic_option Top_Bits_bits))

;; "Top_Bits_insubd"
(declare-fun Top_Bits_insubd ((Top_List_list Bool)) Top_Bits_bits)

;; "t2tb"
(declare-fun t2tb24 ((Top_Logic_option Top_Bits_bits)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_Logic_option Top_Bits_bits)))
    (sort (Top_Logic_option1 Top_Bits_bits1) (t2tb24 x))))

;; "tb2t"
(declare-fun tb2t24 (uni) (Top_Logic_option Top_Bits_bits))

;; "BridgeL"
(assert
  (forall ((i (Top_Logic_option Top_Bits_bits)))
    (! (= (tb2t24 (t2tb24 i)) i) :pattern ((t2tb24 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (Top_Logic_option1 Top_Bits_bits1) j)
         (= (t2tb24 (tb2t24 j)) j)) :pattern ((t2tb24 (tb2t24 j))) )))

;; "Top_Bits_insubd'def"
(assert
  (forall ((x (Top_List_list Bool)))
    (= (Top_Bits_insubd x) (tb2t5
                             (Top_Logic_odflt
                               Top_Bits_bits1
                               (witness1 Top_Bits_bits1)
                               (t2tb24 (Top_Bits_insub x)))))))

;; "Top_Bits_mkbits"
(declare-fun Top_Bits_mkbits ((Top_List_list Bool)) Top_Bits_bits)

;; "Top_Bits_mkbits'def"
(assert
  (forall ((x (Top_List_list Bool)))
    (= (Top_Bits_mkbits x) (tb2t5
                             (Top_Logic_odflt
                               Top_Bits_bits1
                               (t2tb5
                                 (Top_Bits_insubd
                                   (tb2t7
                                     (Top_List_mkseq
                                       bool
                                       (t2tb22 unamed_lambda)
                                       Top_k))))
                               (t2tb24 (Top_Bits_insub x)))))))

;; "Top_Bits_mkbits_ho"
(declare-fun Top_Bits_mkbits_ho () (Array (Top_List_list Bool) Top_Bits_bits))

;; "Top_Bits_mkbits_ho_spec"
(assert
  (forall ((x (Top_List_list Bool)))
    (= (select Top_Bits_mkbits_ho x) (Top_Bits_mkbits x))))

;; "unamed_lambda"
(declare-fun unamed_lambda1 (ty
  uni) uni)

;; "unamed_lambda_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort
        (infix_mngt (Top_List_list1 qta) (Top_List_list1 qta))
        (unamed_lambda1 qta x)))))

;; "unamed_lambda_spec"
(assert
  (forall ((qta ty))
    (forall ((x uni) (w uni))
      (= (infix_at
           (Top_List_list1 qta)
           (Top_List_list1 qta)
           (unamed_lambda1 qta x)
           w) (Top_List_clcl qta x w)))))

;; "Top_Bits_Enum_WordN_cross1"
(declare-fun Top_Bits_Enum_WordN_cross1 (ty
  uni
  uni) uni)

;; "Top_Bits_Enum_WordN_cross1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort
        (Top_List_list1 (Top_List_list1 qta))
        (Top_Bits_Enum_WordN_cross1 qta x x1)))))

;; "Top_Bits_Enum_WordN_cross1'def"
(assert
  (forall ((qta ty))
    (forall ((x uni) (s uni))
      (= (Top_Bits_Enum_WordN_cross1 qta x s) (Top_List_map
                                                (Top_List_list1 qta)
                                                (Top_List_list1 qta)
                                                (unamed_lambda1 qta x)
                                                s)))))

;; "unamed_lambda"
(declare-fun unamed_lambda2 (ty
  uni) uni)

;; "unamed_lambda_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort
        (infix_mngt qta (Top_List_list1 (Top_List_list1 qta)))
        (unamed_lambda2 qta x)))))

;; "unamed_lambda_spec"
(assert
  (forall ((qta ty))
    (forall ((a uni) (x uni))
      (= (infix_at
           (Top_List_list1 (Top_List_list1 qta))
           qta
           (unamed_lambda2 qta a)
           x) (Top_Bits_Enum_WordN_cross1 qta x a)))))

;; "Top_List_++"
(declare-fun Top_List_plpl (ty
  uni
  uni) uni)

;; "Top_List_++_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_plpl qta x x1)))))

;; "Top_List_++'def"
(assert
  (forall ((qta ty))
    (forall ((s2 uni))
      (and
        (= (Top_List_plpl qta (Top_List_lbrb qta) s2) s2)
        (forall ((x uni) (s1 uni))
          (= (Top_List_plpl qta (Top_List_clcl qta x s1) s2) (Top_List_clcl
                                                               qta
                                                               x
                                                               (Top_List_plpl
                                                                 qta
                                                                 s1
                                                                 s2))))))))

;; "Top_List_++_ho_ho"
(declare-fun Top_List_plpl_ho_ho (ty) uni)

;; "Top_List_++_ho_ho_sort"
(assert
  (forall ((qta ty))
    (sort
      (infix_mngt
        (Top_List_list1 qta)
        (infix_mngt (Top_List_list1 qta) (Top_List_list1 qta)))
      (Top_List_plpl_ho_ho qta))))

;; "Top_List_++_ho_ho_spec"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (= (infix_at
           (Top_List_list1 qta)
           (Top_List_list1 qta)
           (infix_at
             (infix_mngt (Top_List_list1 qta) (Top_List_list1 qta))
             (Top_List_list1 qta)
             (Top_List_plpl_ho_ho qta)
             x)
           x1) (Top_List_plpl qta x x1)))))

;; "Top_List_foldr"
(declare-fun Top_List_foldr (ty
  ty
  uni
  uni
  uni) uni)

;; "Top_List_foldr_sort"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort qtb (Top_List_foldr qta qtb x x1 x2)))))

;; "Top_List_foldr'def"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((f uni) (z0 uni))
      (=>
        (sort qtb z0)
        (and
          (= (Top_List_foldr qta qtb f z0 (Top_List_lbrb qta)) z0)
          (forall ((y uni) (ys uni))
            (= (Top_List_foldr qta qtb f z0 (Top_List_clcl qta y ys)) 
            (infix_at
              qtb
              qtb
              (infix_at (infix_mngt qtb qtb) qta f y)
              (Top_List_foldr qta qtb f z0 ys)))))))))

;; "Top_Bits_Enum_WordN_cross"
(declare-fun Top_Bits_Enum_WordN_cross (ty
  uni
  uni) uni)

;; "Top_Bits_Enum_WordN_cross_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort
        (Top_List_list1 (Top_List_list1 qta))
        (Top_Bits_Enum_WordN_cross qta x x1)))))

;; "Top_Bits_Enum_WordN_cross'def"
(assert
  (forall ((qta ty))
    (forall ((s uni) (a uni))
      (= (Top_Bits_Enum_WordN_cross qta s a) (Top_List_foldr
                                               (Top_List_list1
                                                 (Top_List_list1 qta))
                                               (Top_List_list1
                                                 (Top_List_list1 qta))
                                               (Top_List_plpl_ho_ho
                                                 (Top_List_list1 qta))
                                               (Top_List_lbrb
                                                 (Top_List_list1 qta))
                                               (Top_List_map
                                                 qta
                                                 (Top_List_list1
                                                   (Top_List_list1 qta))
                                                 (unamed_lambda2 qta a)
                                                 s))))))

;; "unamed_lambda"
(declare-fun unamed_lambda3 () (Array (Top_List_list (Top_List_list Bool)) (Array Int (Top_List_list (Top_List_list Bool)))))

;; "t2tb"
(declare-fun t2tb25 ((Array Int (Top_List_list (Top_List_list Bool)))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Int (Top_List_list (Top_List_list Bool)))))
    (sort (infix_mngt int (Top_List_list1 (Top_List_list1 bool))) (t2tb25 x))))

;; "tb2t"
(declare-fun tb2t25 (uni) (Array Int (Top_List_list (Top_List_list Bool))))

;; "BridgeL"
(assert
  (forall ((i (Array Int (Top_List_list (Top_List_list Bool)))))
    (! (= (tb2t25 (t2tb25 i)) i) :pattern ((t2tb25 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb25 (tb2t25 j)) j) :pattern ((t2tb25 (tb2t25 j))) )))

;; "t2tb"
(declare-fun t2tb26 ((Array (Top_List_list (Top_List_list Bool)) (Array Int (Top_List_list (Top_List_list Bool))))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array (Top_List_list (Top_List_list Bool)) (Array Int (Top_List_list (Top_List_list Bool))))))
    (sort
      (infix_mngt
        (Top_List_list1 (Top_List_list1 bool))
        (infix_mngt int (Top_List_list1 (Top_List_list1 bool))))
      (t2tb26 x))))

;; "tb2t"
(declare-fun tb2t26 (uni) (Array (Top_List_list (Top_List_list Bool)) (Array Int (Top_List_list (Top_List_list Bool)))))

;; "BridgeL"
(assert
  (forall ((i (Array (Top_List_list (Top_List_list Bool)) (Array Int (Top_List_list (Top_List_list Bool))))))
    (! (= (tb2t26 (t2tb26 i)) i) :pattern ((t2tb26 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb26 (tb2t26 j)) j) :pattern ((t2tb26 (tb2t26 j))) )))

;; "unamed_lambda_spec"
(assert
  (forall ((s (Top_List_list (Top_List_list Bool))) (i Int))
    (= (tb2t6
         (infix_at
           (Top_List_list1 (Top_List_list1 bool))
           int
           (infix_at
             (infix_mngt int (Top_List_list1 (Top_List_list1 bool)))
             (Top_List_list1 (Top_List_list1 bool))
             (t2tb26 unamed_lambda3)
             (t2tb6 s))
           (t2tb10 i))) (tb2t6
                          (Top_Bits_Enum_WordN_cross
                            bool
                            (Top_List_clcl
                              bool
                              (t2tb11 true)
                              (Top_List_clcl
                                bool
                                (t2tb11 false)
                                (Top_List_lbrb bool)))
                            (t2tb6 s))))))

;; "Top_List_foldl"
(declare-fun Top_List_foldl (ty
  ty
  uni
  uni
  uni) uni)

;; "Top_List_foldl_sort"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort qtb (Top_List_foldl qta qtb x x1 x2)))))

;; "t2tb"
(declare-fun t2tb27 ((Array (Top_List_list Bool) Top_Bits_bits)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array (Top_List_list Bool) Top_Bits_bits)))
    (sort (infix_mngt (Top_List_list1 bool) Top_Bits_bits1) (t2tb27 x))))

;; "tb2t"
(declare-fun tb2t27 (uni) (Array (Top_List_list Bool) Top_Bits_bits))

;; "BridgeL"
(assert
  (forall ((i (Array (Top_List_list Bool) Top_Bits_bits)))
    (! (= (tb2t27 (t2tb27 i)) i) :pattern ((t2tb27 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort (infix_mngt (Top_List_list1 bool) Top_Bits_bits1) j)
         (= (t2tb27 (tb2t27 j)) j)) :pattern ((t2tb27 (tb2t27 j))) )))

;; "t2tb"
(declare-fun t2tb28 ((Array Top_Bits_bits (Array (Top_List_list Bool) Top_Bits_bits))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_Bits_bits (Array (Top_List_list Bool) Top_Bits_bits))))
    (sort
      (infix_mngt
        Top_Bits_bits1
        (infix_mngt (Top_List_list1 bool) Top_Bits_bits1))
      (t2tb28 x))))

;; "tb2t"
(declare-fun tb2t28 (uni) (Array Top_Bits_bits (Array (Top_List_list Bool) Top_Bits_bits)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_Bits_bits (Array (Top_List_list Bool) Top_Bits_bits))))
    (! (= (tb2t28 (t2tb28 i)) i) :pattern ((t2tb28 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_Bits_bits1
             (infix_mngt (Top_List_list1 bool) Top_Bits_bits1))
           j)
         (= (t2tb28 (tb2t28 j)) j)) :pattern ((t2tb28 (tb2t28 j))) )))

;; "Top_List_foldl'def"
(assert
  (forall ((f (Array Top_Bits_bits (Array (Top_List_list Bool) Top_Bits_bits))) (z0 Top_Bits_bits))
    (and
      (= (tb2t5
           (Top_List_foldl
             (Top_List_list1 bool)
             Top_Bits_bits1
             (t2tb28 f)
             (t2tb5 z0)
             (Top_List_lbrb (Top_List_list1 bool)))) z0)
      (forall ((y (Top_List_list Bool)) (ys (Top_List_list (Top_List_list Bool))))
        (= (tb2t5
             (Top_List_foldl
               (Top_List_list1 bool)
               Top_Bits_bits1
               (t2tb28 f)
               (t2tb5 z0)
               (Top_List_clcl (Top_List_list1 bool) (t2tb7 y) (t2tb6 ys)))) 
        (tb2t5
          (Top_List_foldl
            (Top_List_list1 bool)
            Top_Bits_bits1
            (t2tb28 f)
            (t2tb5
              (select (tb2t27
                        (infix_at
                          (infix_mngt (Top_List_list1 bool) Top_Bits_bits1)
                          Top_Bits_bits1
                          (t2tb28 f)
                          (t2tb5 z0))) y))
            (t2tb6 ys))))))))

;; "t2tb"
(declare-fun t2tb29 ((Array Top_DiffieHellman_GP_ZModE_exp (Array Int Top_DiffieHellman_GP_ZModE_exp))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_GP_ZModE_exp (Array Int Top_DiffieHellman_GP_ZModE_exp))))
    (sort
      (infix_mngt
        Top_DiffieHellman_GP_ZModE_exp1
        (infix_mngt int Top_DiffieHellman_GP_ZModE_exp1))
      (t2tb29 x))))

;; "tb2t"
(declare-fun tb2t29 (uni) (Array Top_DiffieHellman_GP_ZModE_exp (Array Int Top_DiffieHellman_GP_ZModE_exp)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_GP_ZModE_exp (Array Int Top_DiffieHellman_GP_ZModE_exp))))
    (! (= (tb2t29 (t2tb29 i)) i) :pattern ((t2tb29 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_DiffieHellman_GP_ZModE_exp1
             (infix_mngt int Top_DiffieHellman_GP_ZModE_exp1))
           j)
         (= (t2tb29 (tb2t29 j)) j)) :pattern ((t2tb29 (tb2t29 j))) )))

;; "Top_List_foldl'def"
(assert
  (forall ((f (Array Top_DiffieHellman_GP_ZModE_exp (Array Int Top_DiffieHellman_GP_ZModE_exp))) (z0 Top_DiffieHellman_GP_ZModE_exp))
    (and
      (= (tb2t3
           (Top_List_foldl
             int
             Top_DiffieHellman_GP_ZModE_exp1
             (t2tb29 f)
             (t2tb3 z0)
             (Top_List_lbrb int))) z0)
      (forall ((y Int) (ys (Top_List_list Int)))
        (= (tb2t3
             (Top_List_foldl
               int
               Top_DiffieHellman_GP_ZModE_exp1
               (t2tb29 f)
               (t2tb3 z0)
               (Top_List_clcl int (t2tb10 y) (t2tb9 ys)))) (tb2t3
                                                             (Top_List_foldl
                                                               int
                                                               Top_DiffieHellman_GP_ZModE_exp1
                                                               (t2tb29 f)
                                                               (t2tb3
                                                                 (select 
                                                                 (tb2t23
                                                                   (infix_at
                                                                    (infix_mngt
                                                                    int
                                                                    Top_DiffieHellman_GP_ZModE_exp1)
                                                                    Top_DiffieHellman_GP_ZModE_exp1
                                                                    (t2tb29
                                                                    f)
                                                                    (t2tb3
                                                                    z0))) y))
                                                               (t2tb9 ys))))))))

;; "Top_List_foldl'def"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((f uni) (z0 uni))
      (=>
        (sort qtb z0)
        (and
          (= (Top_List_foldl qta qtb f z0 (Top_List_lbrb qta)) z0)
          (forall ((y uni) (ys uni))
            (= (Top_List_foldl qta qtb f z0 (Top_List_clcl qta y ys)) 
            (Top_List_foldl
              qta
              qtb
              f
              (infix_at qtb qta (infix_at (infix_mngt qta qtb) qtb f z0) y)
              ys))))))))

;; "Top_Bits_Enum_bitsn"
(declare-fun Top_Bits_Enum_bitsn (Int) (Top_List_list (Top_List_list Bool)))

;; "Top_Bits_Enum_bitsn'def"
(assert
  (forall ((n Int))
    (= (Top_Bits_Enum_bitsn n) (tb2t6
                                 (Top_List_foldl
                                   int
                                   (Top_List_list1 (Top_List_list1 bool))
                                   (t2tb26 unamed_lambda3)
                                   (Top_List_clcl
                                     (Top_List_list1 bool)
                                     (Top_List_lbrb bool)
                                     (Top_List_lbrb (Top_List_list1 bool)))
                                   (t2tb9 (Top_List_Iota_iota_ 0 n)))))))

;; "Top_DiffieHellman_G_g"
(declare-fun Top_DiffieHellman_G_g () Top_DiffieHellman_G_group)

;; "Top_DiffieHellman_GP_ZModE_Sub_val"
(declare-fun Top_DiffieHellman_GP_ZModE_Sub_val (Top_DiffieHellman_GP_ZModE_exp) Int)

;; "Top_CoreInt_absz"
(declare-fun Top_CoreInt_absz (Int) Int)

;; "Top_CoreInt_absz'def"
(assert
  (forall ((x Int))
    (ite (<= 0 x) (= (Top_CoreInt_absz x) x) (= (Top_CoreInt_absz x) (- x)))))

;; "Top_DiffieHellman_G_*"
(declare-fun Top_DiffieHellman_G_as (Top_DiffieHellman_G_group
  Top_DiffieHellman_G_group) Top_DiffieHellman_G_group)

;; "Top_DiffieHellman_G_*_ho"
(declare-fun Top_DiffieHellman_G_as_ho () (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group)))

;; "t2tb"
(declare-fun t2tb30 ((Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group)))
    (sort
      (infix_mngt Top_DiffieHellman_G_group1 Top_DiffieHellman_G_group1)
      (t2tb30 x))))

;; "tb2t"
(declare-fun tb2t30 (uni) (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group)))
    (! (= (tb2t30 (t2tb30 i)) i) :pattern ((t2tb30 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt Top_DiffieHellman_G_group1 Top_DiffieHellman_G_group1)
           j)
         (= (t2tb30 (tb2t30 j)) j)) :pattern ((t2tb30 (tb2t30 j))) )))

;; "t2tb"
(declare-fun t2tb31 ((Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group))) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group))))
    (sort
      (infix_mngt
        Top_DiffieHellman_G_group1
        (infix_mngt Top_DiffieHellman_G_group1 Top_DiffieHellman_G_group1))
      (t2tb31 x))))

;; "tb2t"
(declare-fun tb2t31 (uni) (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group)))

;; "BridgeL"
(assert
  (forall ((i (Array Top_DiffieHellman_G_group (Array Top_DiffieHellman_G_group Top_DiffieHellman_G_group))))
    (! (= (tb2t31 (t2tb31 i)) i) :pattern ((t2tb31 i)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=>
         (sort
           (infix_mngt
             Top_DiffieHellman_G_group1
             (infix_mngt
               Top_DiffieHellman_G_group1
               Top_DiffieHellman_G_group1))
           j)
         (= (t2tb31 (tb2t31 j)) j)) :pattern ((t2tb31 (tb2t31 j))) )))

;; "Top_DiffieHellman_G_*_ho_spec"
(assert
  (forall ((x Top_DiffieHellman_G_group) (x1 Top_DiffieHellman_G_group))
    (= (tb2t1
         (infix_at
           Top_DiffieHellman_G_group1
           Top_DiffieHellman_G_group1
           (infix_at
             (infix_mngt
               Top_DiffieHellman_G_group1
               Top_DiffieHellman_G_group1)
             Top_DiffieHellman_G_group1
             (t2tb31 Top_DiffieHellman_G_as_ho)
             (t2tb1 x))
           (t2tb1 x1))) (Top_DiffieHellman_G_as x x1))))

;; "Top_DiffieHellman_G_e"
(declare-fun Top_DiffieHellman_G_e () Top_DiffieHellman_G_group)

;; "unamed_lambda"
(declare-fun unamed_lambda4 (ty
  uni) uni)

;; "unamed_lambda_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (infix_mngt int (infix_mngt qta qta)) (unamed_lambda4 qta x)))))

;; "unamed_lambda_spec"
(assert
  (forall ((qta ty))
    (forall ((f uni) (i Int))
      (=>
        (sort (infix_mngt qta qta) f)
        (= (infix_at
             (infix_mngt qta qta)
             int
             (unamed_lambda4 qta f)
             (t2tb10 i)) f)))))

;; "Top_Int_IterOp_iteri"
(declare-fun Top_Int_IterOp_iteri (ty
  Int
  uni
  uni) uni)

;; "Top_Int_IterOp_iteri_sort"
(assert
  (forall ((qta ty))
    (forall ((x Int) (x1 uni) (x2 uni))
      (sort qta (Top_Int_IterOp_iteri qta x x1 x2)))))

;; "Top_Int_IterOp_iter"
(declare-fun Top_Int_IterOp_iter (ty
  Int
  uni
  uni) uni)

;; "Top_Int_IterOp_iter_sort"
(assert
  (forall ((qta ty))
    (forall ((x Int) (x1 uni) (x2 uni))
      (sort qta (Top_Int_IterOp_iter qta x x1 x2)))))

;; "Top_Int_IterOp_iter'def"
(assert
  (forall ((qta ty))
    (forall ((n Int) (f uni) (x0 uni))
      (= (Top_Int_IterOp_iter qta n f x0) (Top_Int_IterOp_iteri
                                            qta
                                            n
                                            (unamed_lambda4 qta f)
                                            x0)))))

;; "Top_DiffieHellman_G_^+"
(declare-fun Top_DiffieHellman_G_cfpl (Top_DiffieHellman_G_group
  Int) Top_DiffieHellman_G_group)

;; "Top_DiffieHellman_G_^+'def"
(assert
  (forall ((x Top_DiffieHellman_G_group) (k Int))
    (= (Top_DiffieHellman_G_cfpl x k) (tb2t1
                                        (Top_Int_IterOp_iter
                                          Top_DiffieHellman_G_group1
                                          (Top_CoreInt_absz k)
                                          (infix_at
                                            (infix_mngt
                                              Top_DiffieHellman_G_group1
                                              Top_DiffieHellman_G_group1)
                                            Top_DiffieHellman_G_group1
                                            (t2tb31
                                              Top_DiffieHellman_G_as_ho)
                                            (t2tb1 x))
                                          (t2tb1 Top_DiffieHellman_G_e))))))

;; "Top_DiffieHellman_G_inv"
(declare-fun Top_DiffieHellman_G_inv (Top_DiffieHellman_G_group) Top_DiffieHellman_G_group)

;; "Top_DiffieHellman_G_^"
(declare-fun Top_DiffieHellman_G_cf (Top_DiffieHellman_G_group
  Int) Top_DiffieHellman_G_group)

;; "Top_DiffieHellman_G_^'def"
(assert
  (forall ((x Top_DiffieHellman_G_group) (k Int))
    (ite (< k 0)
      (= (Top_DiffieHellman_G_cf x k) (Top_DiffieHellman_G_inv
                                        (Top_DiffieHellman_G_cfpl x k)))
      (= (Top_DiffieHellman_G_cf x k) (Top_DiffieHellman_G_cfpl x k)))))

;; "Top_DiffieHellman_GP_^"
(declare-fun Top_DiffieHellman_GP_cf (Top_DiffieHellman_G_group
  Top_DiffieHellman_GP_ZModE_exp) Top_DiffieHellman_G_group)

;; "Top_DiffieHellman_GP_^'def"
(assert
  (forall ((x Top_DiffieHellman_G_group) (k Top_DiffieHellman_GP_ZModE_exp))
    (= (Top_DiffieHellman_GP_cf x k) (Top_DiffieHellman_G_cf
                                       x
                                       (Top_DiffieHellman_GP_ZModE_Sub_val k)))))

;; "Top_DiffieHellman_GP_ZModE_*"
(declare-fun Top_DiffieHellman_GP_ZModE_as (Top_DiffieHellman_GP_ZModE_exp
  Top_DiffieHellman_GP_ZModE_exp) Top_DiffieHellman_GP_ZModE_exp)

;; "Top_DiffieHellman_GP_ZModE_*'def"
(assert
  (forall ((x Top_DiffieHellman_GP_ZModE_exp) (y Top_DiffieHellman_GP_ZModE_exp))
    (= (Top_DiffieHellman_GP_ZModE_as x y) (Top_DiffieHellman_GP_ZModE_inzmod
                                             (* (Top_DiffieHellman_GP_ZModE_Sub_val
                                                  x) (Top_DiffieHellman_GP_ZModE_Sub_val
                                                       y))))))

;; "Top_gt0_qH"
(assert (< 0 Top_qH))

;; "Top_DiffieHellman_GP_expM"
(assert
  (forall ((x Top_DiffieHellman_G_group) (a Top_DiffieHellman_GP_ZModE_exp) (b Top_DiffieHellman_GP_ZModE_exp))
    (= (Top_DiffieHellman_GP_cf x (Top_DiffieHellman_GP_ZModE_as a b)) 
    (Top_DiffieHellman_GP_cf
      (Top_DiffieHellman_GP_cf x a)
      b))))

;; Goal "goal"
(assert
  (not
  (forall ((xL Top_DiffieHellman_GP_ZModE_exp))
    (=>
      (Top_Distr_support1
        (Top_Distr_MUniform_duniform1
          (Top_List_map1
            Top_DiffieHellman_GP_ZModE_inzmod_ho
            (Top_List_Range_range
              0
              (Top_List_size1 Top_DiffieHellman_G_elems))))
        xL)
      (forall ((yL Top_DiffieHellman_GP_ZModE_exp))
        (=>
          (Top_Distr_support1
            (Top_Distr_MUniform_duniform1
              (Top_List_map1
                Top_DiffieHellman_GP_ZModE_inzmod_ho
                (Top_List_Range_range
                  0
                  (Top_List_size1 Top_DiffieHellman_G_elems))))
            yL)
          (and
            (<= 0 Top_qH)
            (=>
              (<= 0 Top_qH)
              (forall ((qs_R (Top_FSet_fset Top_DiffieHellman_G_group)))
                (=>
                  (<= (Top_FSet_card1 qs_R) Top_qH)
                  (forall ((hL Top_Bits_bits))
                    (=>
                      (Top_Distr_support2
                        (Top_Distr_MUniform_duniform2
                          (Top_List_map2
                            Top_Bits_mkbits_ho
                            (Top_Bits_Enum_bitsn Top_k)))
                        hL)
                      (= (Top_DiffieHellman_GP_cf
                           (Top_DiffieHellman_GP_cf Top_DiffieHellman_G_g xL)
                           yL) (Top_DiffieHellman_GP_cf
                                 Top_DiffieHellman_G_g
                                 (Top_DiffieHellman_GP_ZModE_as xL yL)))))))))))))))

(check-sat)
(get-info :reason-unknown)

