;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
(declare-sort uni 0)

(declare-sort ty 0)

;; "sort"
(declare-fun sort (ty
  uni) Bool)

;; "witness"
(declare-fun witness (ty) uni)

;; "witness_sort"
(assert (forall ((a ty)) (sort a (witness a))))

;; "int"
(declare-fun int () ty)

;; "infix ->"
(declare-fun infix_mngt (ty
  ty) ty)

(declare-sort Top_List_list 1)

;; "Top_List_list"
(declare-fun Top_List_list1 (ty) ty)

;; "Top_List_[]"
(declare-fun Top_List_lbrb (ty) uni)

;; "Top_List_[]_sort"
(assert (forall ((qta ty)) (sort (Top_List_list1 qta) (Top_List_lbrb qta))))

;; "Top_List_::"
(declare-fun Top_List_clcl (ty
  uni
  uni) uni)

;; "Top_List_::_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_clcl qta x x1)))))

;; "match_Top_List_list"
(declare-fun match_Top_List_list (ty
  ty
  uni
  uni
  uni) uni)

;; "match_Top_List_list_sort"
(assert
  (forall ((qta ty) (a ty))
    (forall ((x uni) (x1 uni) (x2 uni))
      (sort a (match_Top_List_list a qta x x1 x2)))))

;; "match_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni))
      (=>
        (sort a z)
        (= (match_Top_List_list a qta (Top_List_lbrb qta) z z1) z)))))

;; "match_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty) (a ty))
    (forall ((z uni) (z1 uni) (u uni) (u1 uni))
      (=>
        (sort a z1)
        (= (match_Top_List_list a qta (Top_List_clcl qta u u1) z z1) z1)))))

;; "index_Top_List_list"
(declare-fun index_Top_List_list (ty
  uni) Int)

;; "index_Top_List_list_Top_List_[]"
(assert
  (forall ((qta ty)) (= (index_Top_List_list qta (Top_List_lbrb qta)) 0)))

;; "index_Top_List_list_Top_List_::"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (! (= (index_Top_List_list qta (Top_List_clcl qta u u1)) 1) :pattern (
      (Top_List_clcl
        qta
        u
        u1)) ))))

;; "Top_List_::_proj_1"
(declare-fun Top_List_clcl_proj_1 (ty
  uni) uni)

;; "Top_List_::_proj_1_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni)) (sort qta (Top_List_clcl_proj_1 qta x)))))

;; "Top_List_::_proj_1'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (=>
        (sort qta u)
        (= (Top_List_clcl_proj_1 qta (Top_List_clcl qta u u1)) u)))))

;; "Top_List_::_proj_2"
(declare-fun Top_List_clcl_proj_2 (ty
  uni) uni)

;; "Top_List_::_proj_2_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni))
      (sort (Top_List_list1 qta) (Top_List_clcl_proj_2 qta x)))))

;; "Top_List_::_proj_2'def"
(assert
  (forall ((qta ty))
    (forall ((u uni) (u1 uni))
      (= (Top_List_clcl_proj_2 qta (Top_List_clcl qta u u1)) u1))))

;; "Top_List_list_inversion"
(assert
  (forall ((qta ty))
    (forall ((u uni))
      (or
        (= u (Top_List_lbrb qta))
        (= u (Top_List_clcl
               qta
               (Top_List_clcl_proj_1 qta u)
               (Top_List_clcl_proj_2 qta u)))))))

(declare-sort Top_Byte_byte 0)

;; "Top_Byte_byte"
(declare-fun Top_Byte_byte1 () ty)

;; "infix @"
(declare-fun infix_at (ty
  ty
  uni
  uni) uni)

;; "infix @_sort"
(assert
  (forall ((a ty) (b ty))
    (forall ((x uni) (x1 uni)) (sort b (infix_at b a x x1)))))

;; "witness"
(declare-fun witness1 (ty) uni)

;; "witness_sort"
(assert (forall ((ta ty)) (sort ta (witness1 ta))))

;; "m"
(declare-fun m () (Top_List_list Top_Byte_byte))

;; "i"
(declare-fun i () Int)

;; "h0i"
(assert (<= 0 i))

;; "Top_Poly_in_poly_in_size"
(declare-fun Top_Poly_in_poly_in_size () Int)

;; "Top_Poly_out_poly_out_size"
(declare-fun Top_Poly_out_poly_out_size () Int)

;; "Top_Extra_block_extra_block_size"
(declare-fun Top_Extra_block_extra_block_size () Int)

;; "hi"
(assert
  (< i (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) Top_Extra_block_extra_block_size)))

;; "Top_List_size"
(declare-fun Top_List_size (ty
  uni) Int)

;; "Top_List_size"
(declare-fun Top_List_size1 ((Top_List_list Top_Byte_byte)) Int)

;; "t2tb"
(declare-fun t2tb ((Top_List_list Top_Byte_byte)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Top_Byte_byte)))
    (sort (Top_List_list1 Top_Byte_byte1) (t2tb x))))

;; "tb2t"
(declare-fun tb2t (uni) (Top_List_list Top_Byte_byte))

;; "BridgeL"
(assert
  (forall ((i1 (Top_List_list Top_Byte_byte)))
    (! (= (tb2t (t2tb i1)) i1) :pattern ((t2tb i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni)) (! (= (t2tb (tb2t j)) j) :pattern ((t2tb (tb2t j))) )))

;; "t2tb"
(declare-fun t2tb1 (Top_Byte_byte) uni)

;; "t2tb_sort"
(assert (forall ((x Top_Byte_byte)) (sort Top_Byte_byte1 (t2tb1 x))))

;; "tb2t"
(declare-fun tb2t1 (uni) Top_Byte_byte)

;; "BridgeL"
(assert
  (forall ((i1 Top_Byte_byte))
    (! (= (tb2t1 (t2tb1 i1)) i1) :pattern ((t2tb1 i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort Top_Byte_byte1 j) (= (t2tb1 (tb2t1 j)) j)) :pattern (
    (t2tb1
      (tb2t1 j))) )))

;; "Top_List_size'def"
(assert
  (and
    (= (Top_List_size1 (tb2t (Top_List_lbrb Top_Byte_byte1))) 0)
    (forall ((y Top_Byte_byte) (ys (Top_List_list Top_Byte_byte)))
      (= (Top_List_size1
           (tb2t (Top_List_clcl Top_Byte_byte1 (t2tb1 y) (t2tb ys)))) (+ 1 
      (Top_List_size1
        ys))))))

;; "Top_List_size'def"
(assert
  (forall ((qta ty))
    (and
      (= (Top_List_size qta (Top_List_lbrb qta)) 0)
      (forall ((y uni) (ys uni))
        (= (Top_List_size qta (Top_List_clcl qta y ys)) (+ 1 (Top_List_size
                                                               qta
                                                               ys)))))))

;; "Top_Byte_zero"
(declare-fun Top_Byte_zero () Top_Byte_byte)

;; "Top_List_take"
(declare-fun Top_List_take (ty
  Int
  uni) uni)

;; "Top_List_take_sort"
(assert
  (forall ((qta ty))
    (forall ((x Int) (x1 uni))
      (sort (Top_List_list1 qta) (Top_List_take qta x x1)))))

;; "Top_List_take"
(declare-fun Top_List_take1 (Int
  (Top_List_list Top_Byte_byte)) (Top_List_list Top_Byte_byte))

;; "Top_List_take'def"
(assert
  (forall ((n Int))
    (and
      (= (Top_List_take1 n (tb2t (Top_List_lbrb Top_Byte_byte1))) (tb2t
                                                                    (Top_List_lbrb
                                                                    Top_Byte_byte1)))
      (forall ((y Top_Byte_byte) (ys (Top_List_list Top_Byte_byte)))
        (let ((xs (tb2t (Top_List_clcl Top_Byte_byte1 (t2tb1 y) (t2tb ys)))))
          (ite (<= n 0)
            (= (Top_List_take1 n xs) (tb2t (Top_List_lbrb Top_Byte_byte1)))
            (= (Top_List_take1 n xs) (tb2t
                                       (Top_List_clcl
                                         Top_Byte_byte1
                                         (t2tb1 y)
                                         (t2tb
                                           (Top_List_take1 (+ n (- 1)) ys)))))))))))

;; "Top_List_take'def"
(assert
  (forall ((qta ty))
    (forall ((n Int))
      (and
        (= (Top_List_take qta n (Top_List_lbrb qta)) (Top_List_lbrb qta))
        (forall ((y uni) (ys uni))
          (let ((xs (Top_List_clcl qta y ys)))
            (ite (<= n 0)
              (= (Top_List_take qta n xs) (Top_List_lbrb qta))
              (= (Top_List_take qta n xs) (Top_List_clcl
                                            qta
                                            y
                                            (Top_List_take
                                              qta
                                              (+ n (- 1))
                                              ys))))))))))

;; "Top_List_nth"
(declare-fun Top_List_nth (ty
  uni
  uni
  Int) uni)

;; "Top_List_nth_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 uni) (x2 Int))
      (sort qta (Top_List_nth qta x x1 x2)))))

;; "Top_List_nth"
(declare-fun Top_List_nth1 (Top_Byte_byte
  (Top_List_list Top_Byte_byte)
  Int) Top_Byte_byte)

;; "Top_List_nth'def"
(assert
  (forall ((x Top_Byte_byte) (n Int))
    (and
      (= (Top_List_nth1 x (tb2t (Top_List_lbrb Top_Byte_byte1)) n) x)
      (forall ((y Top_Byte_byte) (ys (Top_List_list Top_Byte_byte)))
        (let ((xs (tb2t (Top_List_clcl Top_Byte_byte1 (t2tb1 y) (t2tb ys)))))
          (ite (= n 0)
            (= (Top_List_nth1 x xs n) y)
            (= (Top_List_nth1 x xs n) (Top_List_nth1 x ys (+ n (- 1))))))))))

;; "Top_List_nth'def"
(assert
  (forall ((qta ty))
    (forall ((x uni) (n Int))
      (=>
        (sort qta x)
        (and
          (= (Top_List_nth qta x (Top_List_lbrb qta) n) x)
          (forall ((y uni) (ys uni))
            (=>
              (sort qta y)
              (let ((xs (Top_List_clcl qta y ys)))
                (ite (= n 0)
                  (= (Top_List_nth qta x xs n) y)
                  (= (Top_List_nth qta x xs n) (Top_List_nth
                                                 qta
                                                 x
                                                 ys
                                                 (+ n (- 1)))))))))))))

;; "unamed_lambda"
(declare-fun unamed_lambda () (Array Int Top_Byte_byte))

;; "unamed_lambda_spec"
(assert (forall ((us Int)) (= (select unamed_lambda us) Top_Byte_zero)))

;; "Top_List_Iota_iota_"
(declare-fun Top_List_Iota_iota_ (Int
  Int) (Top_List_list Int))

;; "Top_List_map"
(declare-fun Top_List_map (ty
  ty
  uni
  uni) uni)

;; "Top_List_map_sort"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((x uni) (x1 uni))
      (sort (Top_List_list1 qtb) (Top_List_map qta qtb x x1)))))

;; "t2tb"
(declare-fun t2tb2 ((Array Int Top_Byte_byte)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Array Int Top_Byte_byte)))
    (sort (infix_mngt int Top_Byte_byte1) (t2tb2 x))))

;; "tb2t"
(declare-fun tb2t2 (uni) (Array Int Top_Byte_byte))

;; "BridgeL"
(assert
  (forall ((i1 (Array Int Top_Byte_byte)))
    (! (= (tb2t2 (t2tb2 i1)) i1) :pattern ((t2tb2 i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (=> (sort (infix_mngt int Top_Byte_byte1) j) (= (t2tb2 (tb2t2 j)) j)) :pattern (
    (t2tb2
      (tb2t2 j))) )))

;; "t2tb"
(declare-fun t2tb3 ((Top_List_list Int)) uni)

;; "t2tb_sort"
(assert
  (forall ((x (Top_List_list Int))) (sort (Top_List_list1 int) (t2tb3 x))))

;; "tb2t"
(declare-fun tb2t3 (uni) (Top_List_list Int))

;; "BridgeL"
(assert
  (forall ((i1 (Top_List_list Int)))
    (! (= (tb2t3 (t2tb3 i1)) i1) :pattern ((t2tb3 i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb3 (tb2t3 j)) j) :pattern ((t2tb3 (tb2t3 j))) )))

;; "t2tb"
(declare-fun t2tb4 (Int) uni)

;; "t2tb_sort"
(assert (forall ((x Int)) (sort int (t2tb4 x))))

;; "tb2t"
(declare-fun tb2t4 (uni) Int)

;; "BridgeL"
(assert
  (forall ((i1 Int)) (! (= (tb2t4 (t2tb4 i1)) i1) :pattern ((t2tb4 i1)) )))

;; "BridgeR"
(assert
  (forall ((j uni))
    (! (= (t2tb4 (tb2t4 j)) j) :pattern ((t2tb4 (tb2t4 j))) )))

;; "Top_List_map'def"
(assert
  (forall ((f (Array Int Top_Byte_byte)))
    (and
      (= (tb2t
           (Top_List_map int Top_Byte_byte1 (t2tb2 f) (Top_List_lbrb int))) 
      (tb2t
        (Top_List_lbrb Top_Byte_byte1)))
      (forall ((y Int) (ys (Top_List_list Int)))
        (= (tb2t
             (Top_List_map
               int
               Top_Byte_byte1
               (t2tb2 f)
               (Top_List_clcl int (t2tb4 y) (t2tb3 ys)))) (tb2t
                                                            (Top_List_clcl
                                                              Top_Byte_byte1
                                                              (t2tb1
                                                                (select f y))
                                                              (Top_List_map
                                                                int
                                                                Top_Byte_byte1
                                                                (t2tb2 f)
                                                                (t2tb3 ys)))))))))

;; "Top_List_map'def"
(assert
  (forall ((qtb ty) (qta ty))
    (forall ((f uni))
      (and
        (= (Top_List_map qta qtb f (Top_List_lbrb qta)) (Top_List_lbrb qtb))
        (forall ((y uni) (ys uni))
          (= (Top_List_map qta qtb f (Top_List_clcl qta y ys)) (Top_List_clcl
                                                                 qtb
                                                                 (infix_at
                                                                   qtb
                                                                   qta
                                                                   f
                                                                   y)
                                                                 (Top_List_map
                                                                   qta
                                                                   qtb
                                                                   f
                                                                   ys))))))))

;; "Top_List_mkseq"
(declare-fun Top_List_mkseq (ty
  uni
  Int) uni)

;; "Top_List_mkseq_sort"
(assert
  (forall ((qta ty))
    (forall ((x uni) (x1 Int))
      (sort (Top_List_list1 qta) (Top_List_mkseq qta x x1)))))

;; "Top_List_mkseq"
(declare-fun Top_List_mkseq1 ((Array Int Top_Byte_byte)
  Int) (Top_List_list Top_Byte_byte))

;; "Top_List_mkseq'def"
(assert
  (forall ((f (Array Int Top_Byte_byte)) (n Int))
    (= (Top_List_mkseq1 f n) (tb2t
                               (Top_List_map
                                 int
                                 Top_Byte_byte1
                                 (t2tb2 f)
                                 (t2tb3 (Top_List_Iota_iota_ 0 n)))))))

;; "Top_List_mkseq'def"
(assert
  (forall ((qta ty))
    (forall ((f uni) (n Int))
      (= (Top_List_mkseq qta f n) (Top_List_map
                                    int
                                    qta
                                    f
                                    (t2tb3 (Top_List_Iota_iota_ 0 n)))))))

;; "Top_List_nth_mkseq"
(assert
  (forall ((x0 Top_Byte_byte) (f (Array Int Top_Byte_byte)) (n Int) (i1 Int))
    (=>
      (and (<= 0 i1) (< i1 n))
      (= (Top_List_nth1 x0 (Top_List_mkseq1 f n) i1) (select f i1)))))

;; "Top_List_nth_mkseq"
(assert
  (forall ((qta ty))
    (forall ((x0 uni) (f uni) (n Int) (i1 Int))
      (=>
        (and (<= 0 i1) (< i1 n))
        (= (Top_List_nth qta x0 (Top_List_mkseq qta f n) i1) (infix_at
                                                               qta
                                                               int
                                                               f
                                                               (t2tb4 i1)))))))

;; "Top_List_nth_take"
(assert
  (forall ((x0 Top_Byte_byte) (n Int) (s (Top_List_list Top_Byte_byte)) (i1 Int))
    (=>
      (<= 0 n)
      (=>
        (< i1 n)
        (= (Top_List_nth1 x0 (Top_List_take1 n s) i1) (Top_List_nth1 x0 s i1))))))

;; "Top_List_nth_take"
(assert
  (forall ((qta ty))
    (forall ((x0 uni) (n Int) (s uni) (i1 Int))
      (=>
        (<= 0 n)
        (=>
          (< i1 n)
          (= (Top_List_nth qta x0 (Top_List_take qta n s) i1) (Top_List_nth
                                                                qta
                                                                x0
                                                                s
                                                                i1)))))))

;; Goal "goal"
(assert
  (not
  (= (ite (< i (ite (< (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) 
                 Top_Extra_block_extra_block_size) (Top_List_size1 m))
                 (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) 
                 Top_Extra_block_extra_block_size)
                 (Top_List_size1 m)))
       (Top_List_nth1
         Top_Byte_zero
         (Top_List_take1
           (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) 
           Top_Extra_block_extra_block_size)
           m)
         i)
       (Top_List_nth1
         Top_Byte_zero
         (Top_List_mkseq1
           unamed_lambda
           (+ (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) 
           Top_Extra_block_extra_block_size) (- (Top_List_size1 m))))
         (+ i (- (ite (< (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) 
                   Top_Extra_block_extra_block_size) (Top_List_size1 m))
                   (+ (+ Top_Poly_in_poly_in_size Top_Poly_out_poly_out_size) 
                   Top_Extra_block_extra_block_size)
                   (Top_List_size1 m)))))) (ite (< i (Top_List_size1 m))
                                             (Top_List_nth1
                                               Top_Byte_zero
                                               m
                                               i)
                                             Top_Byte_zero))))

(check-sat)

